### ISSUE TITLE
[BUG] Commands not working on several hosts.

### ISSUE THREAD

**Issue by bladeRR** [magmafoundation/Magma#100]
**Describe the bug**
Test on 3 different hosts - Pebblehost, Mcprohosting, Sparkedhost, install the latest version of magma as it should normally be done and at the moment of putting the mode offline (non-premium people) the server was restarted, every time you write a command (for example: op my name) I don't know if it is the type of server or magma needs specifications to work properly.

**Video**

https://vimeo.com/405526238  

This is an explanation video with a server, in which we can see how the server fails 

**Info (please complete the following information):**

 - Magma Version: Magma Dev master-264f337

**Additional context**
 Intel Core i9-9900K CPU, DDR4 RAM, NVMe SSD's

**Comment by kwright02** [comment]
Please upload your server logs to https://mclo.gs this will help us debug your issue.

**Comment by bladeRR** [comment]
https://mclo.gs/9EKqtAT ---- Sparkedhost 
https://mclo.gs/5Ja6JpA ----- Pebblehost
https://mclo.gs/HphCIRs -----minecraft-hosting.pro/ 

try to collect debug from 3 host, with different plugins, but with same result

**Comment by Hexeption** [comment]
Working on fix soon

**Comment by Hexeption** [comment]
This has nothing to do with server hosting

**Comment by bladeRR** [comment]
I know, I just wanted it to show that they were different debug :)

**Comment by bladeRR** [comment]
https://mclo.gs/VKEzOD0

https://vimeo.com/407458558

**Comment by bladeRR** [comment]
post ignored

**Comment by kwright02** [comment]
It’s not being ignored, it’s being worked on. Please wait patiently for a fix. It will be done when it’s done.

**Comment by kwright02** [comment]
Also the video you sent is normal behavior

**Comment by bladeRR** [comment]
it was never resolved

**Comment by Hexeption** [comment]
not happening anymore
