### ISSUE TITLE
Opencomputer's  robots not working

### ISSUE THREAD

**Issue by Panderine** [magmafoundation/Magma#103]
When I create a robot in a magma server the robot doesn't work. When I do it in forge or sponge servers it does. Can't see any error on logs. Can somebody replicate this issue?

**Comment by johncsuti** [comment]
Just tried it and they work fine for me. Also your lack of mod list and plugin lists shows us to not bother helping

**Comment by Panderine** [comment]
Sorry about that. Was testing with Magma latest rev and OC latest available only. Also using openj9. Will try again using different versions and report back with more details. Thanks for testing this from your side.
