### ISSUE TITLE
[BUG] CraftScheduler / ForkJoinPool warnings when working with Skills Pro

### ISSUE THREAD

**Issue by SauROnmiKE** [magmafoundation/Magma#104]
**Describe the bug**
Happened when I tested the Skills Pro plugin. As soon as I joined my server I first got the Craft Scheduler warning as seen here: https://pastebin.com/zqtE3st6 and after that, I get about 5 ForkJoinPool warnings every second as seen in the same link, filling up the console. After a conversation with one of the developers, he/she suggested that this is a bug from Magma's side, providing this piece of code from Bukkit's playerConnection: https://pastebin.com/NuE7PveB

Warnings stop as soon as I disconnect from the server.

**To Reproduce**
1. Installed Skills Pro plugin
2. Joined the server
3. Warnings never stop coming

**Expected behavior**
Plugin should work as expected without all those warnings.

**Info (please complete the following information):**
 -  Plugin Name: Skills Pro (https://www.spigotmc.org/resources/skills-pro.8981/)
 -  Plugin Version: 16.1.0
 -  Magma Version: 1.12.2-magma45bb996
 -  OS: Windows 10 Pro 64Bit

**Comment by SauROnmiKE** [comment]
*UPDATE* Many more features of the plugin are missing, like its custom UI over MC's exp bar, or some behaviour like redirecting the player to immediately pick a class when first entering the server, which doesn't always happen.

Video link of how it should work (on fresh Paper): https://streamable.com/ylplza
Video link of how it actually works (on fresh Magma): https://streamable.com/395yyh

**Comment by Hexeption** [comment]
Sorry I can't fix this due to not owning the plugin

**Comment by kwright02** [comment]
So the plugin uses reflection, which is how they’re able to use nms and have the plugin work with multiple server versions. I’ll look into how they’re using the nms within the scheduler and see what I can find

**Comment by SauROnmiKE** [comment]
Thanks for your help @kwright02
