### ISSUE TITLE
[BUG] Factions plugin will not enable

### ISSUE THREAD

**Issue by Mobborn02** [magmafoundation/Magma#107]
I'm running Magma Dev master-0e43213, the latest version of 1.12.2, on both an Aternos server and a local sandbox server. I've recently tried to add [Factions](https://www.spigotmc.org/resources/factions.1900/) which unfortunately does not enable. The rest of the server runs fine, it's just that Factions will not enable. 

The log is provided below, not in its entirety as it exceeded the limit Pastebin gives to free users:
https://pastebin.com/0ym3UM69

Running other files from the same publisher gave the following output:

https://pastebin.com/Npubwk2j

The plugin is at the latest version (2.14.0) 

I hope the information I can give is enough, I am not entirely familiar with this process.

**Comment by johncsuti** [comment]
Possibly an issue with how the author codes plugins. Considering the author has marked it as archived I would suggest using an alternative to those plugins. No further action should be taken to an abandoned plugin.

**Comment by Hexeption** [comment]
This is known and will not be fixed due to the plugin being archived please use an alternative plugin like SavageFactions/FactionsX
