### ISSUE TITLE
[BUG] SkinsRestorer Plugin with Biomes Mod

### ISSUE THREAD

**Issue by NettiGamer** [magmafoundation/Magma#108]
**Describe the bug**

When you change the level-type of the server to a biomes mod level-type the plugin SkinsRestorer doesn't works

**To Reproduce**

It 's preferably to use a Premium minecraft account to reproduce this bug
 
Part 1

1. Download SkinsRestorer plugin
2. Put it on your server
3. Open server.properties and change online-mode=true to online-mode=false
4. Open the server
5. Connect to the server
6. Try to change your skin with /skin set or /skin

Part 2

1. Download Skinsrestorer plugin and any Biomes Mod
2. Put it on your server 
3. Change the level-type to the mod level type ( e.g. level-type=BIOMESOP )
4. Delete the world folder to generate a new world with the biomes mod level type
5. Open the server
6. Connect to the server
7. Try to change your skin
8. See the server console

**Download Links For Reproduce This Bug**

[Forge](https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-installer-win.exe)

[SkinsRestorer Plugin](https://www.spigotmc.org/resources/skinsrestorer.2124/download?version=306148)

[Biomes Mod](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty/download/2715506/file)

[Magma Server](https://github.com/magmafoundation/Magma/releases/download/vbeffc29/Magma-beffc29-server.jar)

[Java](https://javadl.oracle.com/webapps/download/AutoDL?BundleId=242060_3d5a2bb8f8d4428bbe94aed7ec7ae784)

**Expected behavior**

I expected to have my skin on the server 

**Screenshots**

With a Biome mod

![Captura de pantalla (5)](https://user-images.githubusercontent.com/64135032/79969931-75858e00-8492-11ea-9e1b-7549b2f953e5.png)

![Captura de pantalla (2)](https://user-images.githubusercontent.com/64135032/79980390-4f1c1e80-84a3-11ea-9846-e5ca2704b0fa.png)

Without a Biome mod

![Captura de pantalla (6)](https://user-images.githubusercontent.com/64135032/79970258-eb89f500-8492-11ea-997f-f45b77a11de6.png)

![Captura de pantalla (7)](https://user-images.githubusercontent.com/64135032/79980437-622eee80-84a3-11ea-83e9-9a38ae1d6a37.jpg)

**Info:**

 - Plugin Name: SkinsRestorer
 - Plugin Version: 13.7.5
 - Mod Name: Biomes O 'Plenty
 - Mod Version: BiomesOPlenty-1.12.2-7.0.1.2441-universal
 - Magma Version: Magma Dev master-beffc29
 - OS: Windows 10 Home 1909
 - Java: Version: 8 Update: 251
 - Forge Version: 1.12.2 - 14.23.5.2847
 - Minecraft Version: 1.12.2

**Comment by kwright02** [comment]
The level type has nothing to do with skins, it’s likely non functional because offline mode is active

**Comment by kwright02** [comment]
So I've done investigating, and it seems that the Biome mod overwrites that method which is why it's not working.
