### ISSUE TITLE
[BUG] FastAsyncWorldEdit incompitable due to missing NMS Block Placer

### ISSUE THREAD

**Issue by GuusLieben** [magmafoundation/Magma#11]
**Describe the bug**
FastAsyncWorldEdit does not work on Magma due to the missing/replaced Bukkit NMS Block Placer. This affects all of its functionality.

**To Reproduce**
1. Install FastAsyncWorldEdit as Spigot plugin ([Download](https://empcraft.com/fawe/download/?bukkit))
2. Use //wand (works)
3. Use the given wand to select a region
4. See error in console

**Expected behavior**
Expected FAWE to be able to send the player messages and create the selection.

**Info (please complete the following information):**
- Plugin Name: FastAsyncWorldEdit
 - Plugin Version: bukkit-19.07.25-58243b6-1278-22.3.1
 - Magma Version: Magma-9c838fd-server
 - OS: Windows 10 Pro N

**Log**
https://pastebin.com/KtCKDrqB

**Comment by Hexeption** [comment]
Working in the latest version
