### ISSUE TITLE
[BUG]actually additions worms

### ISSUE THREAD

**Issue by Jenssons** [magmafoundation/Magma#110]
**Describe the bug**
With the mod actually additions you cant place worms down it errors a task problem

**To Reproduce**
1. install actually additions on a magma server.
2. get worms from creative menu
3. place worms down on farmland or tilled soil
4. get error in server log/console

**Expected behavior**
place down worms on farmland to grow other plants around it

**Info (please complete the following information):**
Mod name: Actually Editions
Mod Version: ActuallyAdditions-1.12.2-r151-2
Magma Verson: Magma-0e43213-server
OS: Windows Server 2016 Standard 64-bit (10.0, build 14393)
[wormbug.txt](https://github.com/magmafoundation/Magma/files/4519222/wormbug.txt)

**Comment by johncsuti** [comment]
Is that the whole error log? Can you post a link on mclo.gs for the entire log from startup to issue?

**Comment by Jenssons** [comment]
i can do that after i sleep

**Comment by Jenssons** [comment]
every time i paste the log into mclo.gs then hit saves it gives me 404 log not found error so here is the file
[2020-04-22-1.log](https://github.com/magmafoundation/Magma/files/4533943/2020-04-22-1.log)
