### ISSUE TITLE
[BUG] dose not work with bungee

### ISSUE THREAD

**Issue by MeatSh1eld** [magmafoundation/Magma#111]
**Describe the bug**
if your server is not portforwed you cannot join it though bungee

**To Reproduce**
1. make bugee server
2. make a magma server
3. connect bungee to magma
4. try to join magma server
5. it has to be a LAN and not forwarded

**Expected behavior**
[01:28:25 INFO]: UUID of player creeper_king0509 is ########################
[01:28:55 ERROR]: NetworkDispatcher exception
 io.netty.handler.timeout.ReadTimeoutException: null
[01:28:55 INFO]: creeper_king0509 lost connection: Timed out

**Info (please complete the following information):**
 - Magma Version: Magma Dev master-0e43213
 - OS: windows 10

**Comment by johncsuti** [comment]
try using hexacord as there is better support for modded servers using that

**Comment by UeberallGebannt** [comment]
use hexacord and enable forge support

**Comment by Hexeption** [comment]
Use HexaCord works fine
