### ISSUE TITLE
Crash when connecting to magma server Magma-0e43213

### ISSUE THREAD

**Issue by tanker122** [magmafoundation/Magma#113]
**Describe the bug**
When i try to join my Magma server running on my computer, it simply crashes for an unknown reason, i've tried a few things to solve the issue like removing a plugin that wasn't being loaded, creating a fresh world, and even asking those who know more about servers then i do to look at my logs, but nothing worked. so im uploading it.

**To Reproduce**
1. log onto minecraft forge 1.12.2 with mods
2. try to load onto server with the same mods and plugin "LaggRemover-2.0.4" and the exception of optifine on the server, client does have it
3. server crash

**Screenshots**
[Screenshot (26)](https://user-images.githubusercontent.com/40444856/80755111-1bfe0e80-8ae5-11ea-8b53-098a0ba0f43d.png)

**Info (please complete the following information):**
- Mod Name: to many
 - Mod Version: 1.12.2
 - Magma Version: Magma-0e43213
 - OS: Windows 10 

**Additional context**
log): https://mclo.gs/bXDyt3a
Crash log): https://mclo.gs/2hBa1cp

**Comment by tanker122** [comment]
i believe i figured out what caused it, but dont know why or how, its the mod fastworkbench, i removed it and it stops crashing

**Comment by UeberallGebannt** [comment]
fastworkbench doesnt completely work with magma, use the config provided on the discord and it will work ^^

**Comment by motherboard1999** [comment]
For all people which havent Discord:
[fastbench.cfg.zip](https://github.com/magmafoundation/Magma/files/5194549/fastbench.cfg.zip)

**Comment by cmod31** [comment]
could you maybe let us know about it when the server is starting and not when the player is joining? its a bit annoying with giant modpacks when the server crashes on join

**Comment by kwright02** [comment]
> could you maybe let us know about it when the server is starting and not when the player is joining? its a bit annoying with giant modpacks when the server crashes on join

We do actually

**Comment by cmod31** [comment]
> > could you maybe let us know about it when the server is starting and not when the player is joining? its a bit annoying with giant modpacks when the server crashes on join
> 
> We do actually

The server doesn't crash until a player joins you get the message as a kick message i think it should crash at server start not 20 minutes after my atm3r modpack has been loaded
