### ISSUE TITLE
[Issue]  Incompatibility with function / DiscordSRV - transmission console.

### ISSUE THREAD

**Issue by AsesinaGatitos** [magmafoundation/Magma#114]
DiscordSRV plugin function called **"server console streaming channel"** does not work properly.

I did a test without any plugin and mod to avoid any external problem, besides checking that the configuration is faithful to avoid errors with the plugin and the server.

We contacted the author of the plugin and after testing we concluded that the error was occurring ### because the logger was different from the one used by the magma server, the DiscordSRV console channel is based on the log4j attachments.

The question is, do they use the logger based on the log4j attachments? or use another registrar what would that be?

**is there an option to change the magma server registrar optionally?**

URL: https://github.com/DiscordSRV/DiscordSRV/issues/699

**Comment by kwright02** [comment]
There isn’t an option to change the registrar, however we can look into providing support for DiscordSRV specifically. I’m going to close this for now while we work through our list of issues and bugs. Feel free to reopen this if you have more info to add
