### ISSUE TITLE
[Issue] Tekxit 3 not working with Magma

### ISSUE THREAD

**Issue by Motzkiste** [magmafoundation/Magma#115]
**Describe the issue**
Can't run Magma with Tekxit 3

**To Reproduce**
1. Create Clean installation of Magma.
2. Download and "install" Server-Files from [Tekxit 3](https://www.technicpack.net/modpack/tekxit-3-official-1122.1253751)
3. Start Magma

**Expected behavior**
Magma crashes a few seconds after starting with Message:
"A problem occurred running the Server launcher."

**Info (please complete the following information):**
- Modpack Name: Tekxit 3
 - Modpack Version:  latest (0.972)
 - Magma Version: latest-release (beffc29)
 - OS: Linux Ubuntu 18.04 LTS Server with OpenJDK 64 bit

**Additional context**
[latest.log] (https://mclo.gs/wzpVYnU)

**Comment by Hexeption** [comment]
Remove LagGoggles and should work fine.

LagGoggles will be getting fixed soon

**Comment by Motzkiste** [comment]
Thank you very much. 

Without LagGoogles it's working perfect. ^^

Sry for my late answer D:
