### ISSUE TITLE
[BUG] Problem with Spigot Plugin Packet to Client Forge

### ISSUE THREAD

**Issue by Brasegon** [magmafoundation/Magma#116]
**Describe the bug**
When sending a packet with a spigot plugin, the client does not receive the packet from the spigot plugin

**To Reproduce**
1. Create a plugin with a packet
2. Create a Forge Channel client with handler 
3. Connect packet with an event
4. Add a message in MessageHandler and check if will be receive on the client

**Expected behavior**
The packet is well received with a message that appears in the client console

**Info (please complete the following information):**
 - Magma Version: Magma-0e43213
 - OS: Windows 10 and Debian 10 64 bits

**Additional context**
It works on CatServer and Mohist

**Comment by kwright02** [comment]
This isn’t a bug so much as it’s an unimplemented feature. That being said, I’ll add it to our list
