### ISSUE TITLE
[BUG]Skript

### ISSUE THREAD

**Issue by MaxifeuxG** [magmafoundation/Magma#117]
**Describe the bug**
A clear and concise description of what the bug is:

**To Reproduce**
1. Run server
2. with mods & plugins
3. /skript

**Screenshots**
http://prntscr.com/sb92qf

**Info (please complete the following information):**
- Mod Name: Pixelmon
 - Mod Version: 7.2.2
 - Magma Version: Magma-d79f493-server
 - OS: windows

**Comment by thegamerbr1** [comment]
I'm having the exact same bug here.

**Comment by UeberallGebannt** [comment]
Skript doesn't work with any Forge/Spigot Hybrid as far as i know so it seems to be a general issue.
Please add a link to the skript version you're using.

**Comment by MaxifeuxG** [comment]
Hello this is possible because an API had debug but some mods encountered a problem and the Cauldron or thermos API it works on
