### ISSUE TITLE
[BUG] Mixins or something else, idk...

### ISSUE THREAD

**Issue by BlizzardLight** [magmafoundation/Magma#118]
**Describe the bug**
All description is in [the log](https://pastebin.com/raw/4sm5gKha)

**To Reproduce**
Just run the server with all of detected mods...

**Expected behavior**
I want to see that my server is loaded and working fine, like with forge.

**Info:**
 - Magma Version: any

**Comment by Hexeption** [comment]
Remove Laggoogles

**Comment by BlizzardLight** [comment]
Thank you so much)
