### ISSUE TITLE
[BUG] exp and point problem for Corail Tombstone, Rough Mobs crashing the server and /home issues

### ISSUE THREAD

**Issue by Jenssons** [magmafoundation/Magma#124]
Describe the bug
i was suppose to post this a few days ago but totally forgot to till now, looking at the new release logs it doesnt seem it was address yet. in Rough Mobs 2 a mob and a hostile mob will spawn at the same time trying to mount and crash the server. also something is overruling corail tombstones' death handling config, you lose exp on death, and you lose all the spec'd points in the knoweldge of death, you dont lose the points, but you have to reassign them, oh and when you use /home from the nether it just teleports you to a portal then to where you set home, idk if this is a default forge command or a ftb utilities command

To Reproduce

install all the mods i listed before or install dungeons, dragons and space shuttles modpack on a magma server.
Bind the knowledge of death to a key
open the menu with the key and assign them and get some nomral minecraft exp
kill your self and see if you lose all your exp from your grave and see if your points are reset.

use luckperms to assign the commands for sethome and home and all that because you cant disable the perm thing in magma, then set a home
build a portal and go to the nether and make your way through the nether so you are some what far away from it
then /home and see if it works how it should

and for the rough mobs problem i think you just need to fly around and see if it happens its not really something you can recreate but it happen to us 3 times in no time

Info (please complete the following information):
Mod name: Corail Tombstone, FTB Utilities, Rough Mobs 2
Mod Version: tombstone-3.7.3-1.12.2, FTBUtilities-5.4.0.124, roughmobs2-1.12.2_2.0.15
Magma Verson: Magma-d79f493-server
OS: Windows Server 2016 Standard 64-bit (10.0, build 14393)
[2020-05-06-1.log.zip](https://github.com/magmafoundation/Magma/files/4635340/2020-05-06-1.log.zip)
[latestarchive.zip](https://github.com/magmafoundation/Magma/files/4635341/latestarchive.zip)

**Comment by Jenssons** [comment]
everytime i try that site i get this 
![image](https://user-images.githubusercontent.com/17034639/83979878-77ec5c00-a909-11ea-8cfb-de945aa9e046.png)

this is why i uploaded the logs that would be relevant on the original post

**Comment by kwright02** [comment]
Just click paste a new log

**Comment by Jenssons** [comment]
same thing happens it just instantly goes to that page after i click save, i can record my self doing it if you want to see

**Comment by kwright02** [comment]
Disable VPN or adblocker and make sure to use chrome.

**Comment by Jenssons** [comment]
i open up chrome i turn off bitdefender and got the same error, i went and booted up my server in France and tried the same thing that doesnt have a blocker and same error

**Comment by Jenssons** [comment]
i asked my american friend to also try it and also got the same error :C
[2020-05-06-1.log.zip](https://github.com/magmafoundation/Magma/files/4745679/2020-05-06-1.log.zip)
[latestarchive.zip](https://github.com/magmafoundation/Magma/files/4745681/latestarchive.zip)

**Comment by kwright02** [comment]
It looks like there might be mod conflicts or something. I'm going to need to ask you to dig further as there isn't any info related to your issue within the log. Please comment when you have more info
