### ISSUE TITLE
[BUG] Factions Error in Magma Software

### ISSUE THREAD

**Issue by Weaboomer** [magmafoundation/Magma#125]
So I been trying to open a server with the magma software (in Aternos in 1.12.2). Then tried to install the factions plugin but it wasn’t being detected and didn’t run, it also said something about permissions.yml. I’ve already looked for solutions and found out (right here) that people were having the same Issue. The solution they were giving was to download Some variables of the factions plugins (like SavageFactions) because it was archived. I just couldn’t solve it and not a single faction related plugin is working . Any help?

**Comment by UeberallGebannt** [comment]
Any archived/abandoned plugin isn't going to be supported.
Could you link the plugins you tried?

**Comment by Weaboomer** [comment]
Oh yes of course
Factions Spigot: https://aternos.org/addons/a/spigot/1900
Factions Bukkit: 
https://aternos.org/addons/a/bukkit/factions
SaberFactions:
https://aternos.org/addons/a/spigot/69771
SavageFactions:
https://aternos.org/addons/a/spigot/52891
Factions3:
https://aternos.org/addons/a/spigot/63602

Plus I also tried different versions of each one

**Comment by UeberallGebannt** [comment]
The problem is that i have to register on aternos to see the plugin.

**Comment by Weaboomer** [comment]
Well I can link you the website of each one in spigot and bukkit.

SavageFactions: https://www.spigotmc.org/resources/52891
SaberFactions:
https://www.spigotmc.org/resources/69771
Factions3:
https://www.spigotmc.org/resources/63602
Faction: Bukkit (original):
https://dev.bukkit.org/projects/factions
Factions Spigot (original):
https://www.spigotmc.org/resources/1900

**Comment by UeberallGebannt** [comment]
Factions3 is 1.13+ 
Factions is abandoned

Could you use SaberFactions and send us the logs and a mods/plugin list?

**Comment by Weaboomer** [comment]
Log: https://mclo.gs/CSm8s3p
I reinstalled the server so I don’t have any more mods or plugins.

**Comment by UeberallGebannt** [comment]
[05:23:13] [Server thread/INFO] []: You are missing dependencies!
[05:23:13] [Server thread/INFO] []: Please verify [Vault] is installed! 
 
Please install Vault

**Comment by Weaboomer** [comment]
It worked!!! Thank you so much!!
I thought it wouldn’t work because the other plugins weren’t asking for Vault obligatory, just to manage the economy.
