### ISSUE TITLE
Can not shift out of cameras on Security craft

### ISSUE THREAD

**Issue by ArraTheFox** [magmafoundation/Magma#128]
**Describe the issue**
A clear and concise description of what the bug is: at the time I noticed this I only had Magma, secret rooms, and security craft I attempted to use security craft cameras and can not shift to leave them

**To Reproduce**
I have attempted multiple times and every time I have had to disconnect I can give you my server as it is now if you want to try it on there
as said at the time only Magma which was available on aternos for 1.12.2 security craft and secret rooms mod
**Expected behavior**
A clear and concise description of what you expected to happen: I expect to use the monitor on Security craft to view my camera then be able to crouch to get out when I tried it would not let me the 5 times I tried I had to disconnect and and it happened the exact same way. The only time it worked is on a single player world with just fml secretrooms and security craft

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: Security craft
 - Mod Version: 1.8.18 for 1.12.2 Minecraft
 - Magma Version: v5fab8a3
 - OS: Windows 10 boot camped on a Mac

[latest.log] (Please upload your latest.log to https://mclo.gs and replace this text with the url)

**Comment by josephworks** [comment]
(Please upload your latest.log to https://mclo.gs and replace this text with the url)
you didn't follow that step...

**Comment by ArraTheFox** [comment]
Ok I'll do that in a couple but my comp crashed would the Atrenos end of things work?

**Comment by ArraTheFox** [comment]
https://mclo.gs/AbNgwMG

**Comment by josephworks** [comment]
please post full log

**Comment by ArraTheFox** [comment]
https://mclo.gs/yHqbK0Z

**Comment by josephworks** [comment]
Please share the full log

**Comment by ArraTheFox** [comment]
https://mclo.gs/fyf4cRY

**Comment by ArraTheFox** [comment]
I believe that one is full

**Comment by josephworks** [comment]
no, it isn't. Please post the full log.

**Comment by ArraTheFox** [comment]
https://mclo.gs/Vato8wT

this log is from a server with exactly the setup I had when I made the ticket

**Comment by josephworks** [comment]
Please send the full log.

**Comment by ArraTheFox** [comment]
... literally that was within a minute of starting that server and at that time it was the full log

**Comment by josephworks** [comment]
You cut off the error message, and there isn't any stopping server. Please start and stop the server, and send the full log.

**Comment by ArraTheFox** [comment]
I have completely reset my server and will be adding everything again, sc team said they believe the bug was on their end and has been fixed
