### ISSUE TITLE
[BUG]EnderIO farming station doesnt work on magma server if the owner of the station is offline while chunk is loaded

### ISSUE THREAD

**Issue by upexx** [magmafoundation/Magma#132]
Description of the bug:
Place an EnderIO farming station, load the chunk, go offline. The corps will grow  but the station wont farm them as long as the owner of the station is offline.

Reproduction:

1. Setup a magma server
2. Place a farming station from EnderIO
3. Load the chunk, connect water and energy to the station
4. Go offline

Expected behavior:
When I use the forge server the farming station is working without issues, even when the owner is offline while the chunk is loaded.

Screenshots
-/-
Info (please complete the following information):
- Mod Name: EnderIO
 - Mod Version: EnderIO-1.12.2-5.1.55
 - Magma Version: Magma-aed4e40-server
 - OS: Windows 10, Debian 9

Additional context
-/-

**Comment by kwright02** [comment]
Soloution: Use the spigot plugin extensions instead.
