### ISSUE TITLE
[BUG]servers menu

### ISSUE THREAD

**Issue by DarkStarOrion** [magmafoundation/Magma#133]
I  have problem with server magma81086e0 1.12.2 look: https://imgur.com/f3EaD0t
I don't know why i have this message in servers menu,but i can normal join in this server. please can you fix this problem ;/? This does not look good compared to other servers :(

**Comment by kwright02** [comment]
Are you talking about changing the MOTD in server.properties?

**Comment by Redd56** [comment]
i get it i think, its the unknown version thingy, if im guessing right

**Comment by kwright02** [comment]
This is not Magma's Fault, this has to do with your setup.
