### ISSUE TITLE
libraries unable to be updated unless magma jar is in server directory

### ISSUE THREAD

**Issue by Redd56** [magmafoundation/Magma#134]
**Describe the bug**
unless magma jar is in directory of server it is unable to edit libraries.

Start server without libraries downloaded/old libraries

**Expected behavior**
it to download and update libraries on its own

**Info (please complete the following information):**
magma version: any
os: mx linux 19.1

**Comment by kwright02** [comment]
It’s not designed to work more than 1 level in or  out of the base server directory

**Comment by Redd56** [comment]
welp this will be easy to fix

**Comment by Redd56** [comment]
then this

**Comment by Redd56** [comment]
tackling

**Comment by Redd56** [comment]
fixed by latest commit on kyles bugfix branch 
https://github.com/kwright02/Magma/commit/2a106a1e59592882d2f13eaae94a825ae1ddf4c9
