### ISSUE TITLE
Tardis Plugin Issue (Fixed Format) 

### ISSUE THREAD

**Issue by QueenOfTheHours** [magmafoundation/Magma#136]
Describe the issue:
So Im using the tardis Plugin on the latest version of Magma and tardis plugins latest 1.12.2 version The Plugin requires the TardisChunckGenerator plugin to function It is in the Plugins folder with it and works fine on vanilla servers But despite being in the folder Magma can't seem to find it

To Reproduce
1. Create a server with Magma Dev HEAD-33f031e
2. Install these two plugins https://dev.bukkit.org/projects/tardis/files/2594118
https://dev.bukkit.org/projects/tardis/files/2594119
3. Run the server
4. At this point you can see the commands for the Tardis Plugin but when trying to create a tardis nothing happens.
5. Look into the Latest log
6. Near the end it will say the tardis Chunk Generator could not be found, despite being installed in the plugins folder.

Without this core plugin being recognized the tardis Plugin has no function to it and you can't use any of the plugins recipes. 

Info (please complete the following information):

Magma Version:Magma Dev HEAD-33f031e
OS: Windows 10 

[latest.log] https://mclo.gs/EdITb4e

**Comment by UeberallGebannt** [comment]
The log seems to be deleted. Could you post a new link please?

**Comment by QueenOfTheHours** [comment]
https://mclo.gs/9kG5jHG

**Comment by QueenOfTheHours** [comment]
That should be the same log as the first time but with a new link

**Comment by UeberallGebannt** [comment]
Seems like the plugin couldnt be loaded.

`
  | [22:07:57] [Server thread/ERROR] [Minecraft]: Could not load 'plugins\TARDISChunkGenerator.jar' in folder 'plugins'
`

**Comment by QueenOfTheHours** [comment]
Yes that is the problem, the plugin is in the plugins folder and should be loading. For some reason the server won't load it.

**Comment by QueenOfTheHours** [comment]
Any Idea how I would go about resolving this issue?

**Comment by QueenOfTheHours** [comment]
I'm sorry I've never used Git Hub has this been closed?

**Comment by kwright02** [comment]
It should provide a stack trace underneath the couldn’t load line. Can you send that here?

**Comment by kwright02** [comment]
I'm going to close this issue as this seems to be purely on the plugin side. If you can provide more information or are able to prove it's on Magma, please re open.
