### ISSUE TITLE
[BUG] Can't seralise unregistered packet

### ISSUE THREAD

**Issue by blalp** [magmafoundation/Magma#140]
**Describe the bug**
A clear and concise description of what the bug is:
About 1/30 times when you try to login, the connection is refused with the error on console:
```
[17:23:12 INFO]: SET_PROTOCOL 0 com.comphenix.protocol.injector.netty.ProtocolInjector@9913ca
[17:23:12 INFO]: START 255 com.comphenix.protocol.injector.netty.ProtocolInjector@9913ca
[17:23:12 INFO]: UUID of player blalp is 61d9e6b2-d205-445a-b504-79309042a01e
[17:23:12 INFO]: DEBUG: Player: 'CraftPlayer{name=blalp}' LoginRes: ALLOWED / Reason:  / EventName: PlayerLoginEvent
[17:23:12 INFO]: blalp lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet
```
(The SET_PROTOCOL and START lines are from a protocolib packet sniffer, included for your convenience)
This happens on some joins with just magma (no mods, no plugins, latest build), and a clean client. Could be some thread syncing issues right after craftbukkit. It gets to the part in the join where the PlayerJoin event is called, but doesn't get to the FML forge agreement on mods. 

**To Reproduce**
1. Attempt to login
2. Check console for `lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet`
3. If it didn't happen, repeat. Could take 30+ tries. Not a fun bug to debug.
4. See `lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet` and the kick message is `Disconnected` (aka default fail message from netty handler)

**Expected behavior**
A clear and concise description of what you expected to happen:
Join is allowed every time consistently

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: None
 - Mod Version: N/A
- MC version: 1.12
 - Magma Version: aed4e40, f47bd92, and 3d116a0
 - OS: linux. openjdk 1.8.0_252-b09 and 1.8.0_251-b08

**Additional context**
Add any other context about the problem here:
I also used packet capture on the client, and it looks like the server is terminating the TCP connection prematurly, but then forggeting to notify itself or the client. 

This error happens both on online mode and offline mode. Happens both directly connecting and behind Waterfall/Travertine/Hexacord (all three have problem).

Force metadata rewrite is off in waterfall's config.

Trying to find error, then fix and push upstream.

Connection throttling all disabled

# Things I tried
## Patching NetworkManager.java.patch closeChannel
```java
this.channel.close().awaitUninterruptibly();
// We can't wait as this may be called from an event loop.
// this.channel.close().awaitUninterruptibly();
this.channel.close();
``` switched this so it waited, issue still happened
## Throwing an error to get stacktrace
Temp patched the NetHandlerPlayServer to add an execption. THIS IS NOT A REAL EXECPTION, just to show stacktrace for debugging purposes
``` 
```
java.lang.IllegalArgumentException: placeholder
    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:1300) ~[pa.class:?]
    at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:467) ~[gw.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:231) ~[oz.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1011) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) ~[nz.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:734) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
and de-obfuscated for you:
```
java.lang.IllegalArgumentException: placeholder
        at net.minecraft.network.NetHandlerPlayServer.onDisconnect(NetHandlerPlayServer.java:1300) ~[pa.class:?]
        at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:467) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:231) ~[oz.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:1011) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:456) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:862) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:734) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
## Reverting a edit in NetworkManager.java.patch
Tried to revert https://github.com/magmafoundation/Magma/blob/3eac2e60254864f77aede1672b8b9f7e24f5fd30/patches/net/minecraft/network/NetworkManager.java.patch#L85

**Comment by Redd56** [comment]
can confirm that this happens from time to time to me as well alot, usually only takes a few re-attempts

**Comment by kwright02** [comment]
Is there an actual error in console when you get this Cannot Serialize Unregistered packet?

**Comment by blalp** [comment]
"blalp lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet" That is an error, just not displayed as a stacktrace. From what I saw it looked like the server was sending a FIN packet when it shouldn't have. Maybe an underlying netty mis-configuration?

**Comment by kwright02** [comment]
I can't really do much without a stack trace because I have no idea where the error originates from

**Comment by blalp** [comment]
I added a throw where it prints the statement, and got the stack trace of:
> ```
> java.lang.IllegalArgumentException: placeholder
>    at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:1300) ~[pa.class:?]
>    at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:467) ~[gw.class:?]
>    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:231) ~[oz.class:?]
>    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1011) ~[MinecraftServer.class:?]
>    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456) ~[nz.class:?]
>    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862) ~[MinecraftServer.class:?]
>    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:734) [MinecraftServer.class:?]
>    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
> ```
> And de-obfusaceted for you:
> ```
> java.lang.IllegalArgumentException: placeholder
>         at net.minecraft.network.NetHandlerPlayServer.onDisconnect(NetHandlerPlayServer.java:1300) ~[pa.class:?]
>        at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:467) ~[gw.class:?]
>        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:231) ~[oz.class:?]
>        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:1011) ~[MinecraftServer.class:?]
>        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:456) ~[nz.class:?]
>        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:862) ~[MinecraftServer.class:?]
>        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:734) [MinecraftServer.class:?]
>        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
> ```

Looks like the connection closes unexpectedly. 
> I also used packet capture on the client, and it looks like the server is terminating the TCP connection prematurly, but then forggeting to notify itself or the client.

Maybe there is an underlying netty miss configuration, where TCP sessions are getting dropped for some reason?

**Comment by kwright02** [comment]
The thing is there isn’t anything at line 1300. It’s just a commented out line. I’ll keep looking deeper

**Comment by blalp** [comment]
> The thing is there isn’t anything at line 1300. It’s just a commented out line. I’ll keep looking deeper

I added a `throw new IllegalArgumentExepction` there, just to get the stack trace. Ignore the first call, all calls below are an accurate stack trace.

**Comment by kwright02** [comment]
I've figured out the root of this issue and the fix will be rolled out soon
