### ISSUE TITLE
/tps gone after reload

### ISSUE THREAD

**Issue by Redd56** [magmafoundation/Magma#141]
after /reload the in game command /tps is broken and unable to be seen

**To Reproduce**
do /tps
see fancy tps graph
do /reload confirm
do /tps
and its gone... bye then

**Expected behavior**
/reload not to break a base integrated feature

 - Magma Version:  26894630

**Comment by Neewen** [comment]
Hello,
and I would like to add that the "/version" or "/ver" also disappears after "/reload" ^^

 Magma Version: 
Magma version 3d116a0 (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge Version 14.23.5.2854)

**Comment by Amgelo563** [comment]
On my experience (Spigot & Paper), `/reload` tends to break a lot of stuff, that's why I would recommend a full stop and start.

**Comment by kwright02** [comment]
> On my experience (Spigot & Paper), `/reload` tends to break a lot of stuff, that's why I would recommend a full stop and start.

Exactly as is said here, /reload is a feature built into Spigot/Bukkit and it is NOT RECOMMENDED to be used AT ALL
