### ISSUE TITLE
when essentialsx is installed you suddently contract insomnia

### ISSUE THREAD

**Issue by Redd56** [magmafoundation/Magma#142]
when the plugin essentials x is installed you can not sleep though the night. ever

**To Reproduce**
add essentials x
try to sleep the night away

**Expected behavior**
to be able to sleep though the night when in a bed lmao

**Info (please complete the following information):**
 - Magma Version:

**Comment by kwright02** [comment]
What mods do you have installed when you are encountering this issue? Also any logs you could provide would be helpful. https://mclo.gs

**Comment by Hexeption** [comment]
Tried to reproduce using your steps and it works fine?

more information would be great on this issue.

**Comment by Redd56** [comment]
go afk and it happens, it just happened to happen before i went afk

**Comment by Redd56** [comment]
that one was probably a freak ocuurance
is best experienced with multiple players

**Comment by Hexeption** [comment]
Were all users sleeping

**Comment by Redd56** [comment]
yes

**Comment by Redd56** [comment]
hold on let me get on the discord so we dont clog things here

**Comment by Redd56** [comment]
me and kyle are on it

**Comment by kwright02** [comment]
We have investigated and found that this isn't an issue with magma but is an issue with EssentialsX itself. Its check that sets whether the player is ignored for sleeping based on their permissions or op status. In any case, normal players without permission do not encounter the error regularly.

**Comment by Redd56** [comment]
we are re investigating and finding out the exact issue
as in me and kyle

**Comment by kwright02** [comment]
Issue update: We finally figured out the issue had to do with wacky handling of AFK/spectating players in the craftbukkit sleep checks. Will be fixed in next release
