### ISSUE TITLE
[BUG] Failed to Download Libraries during install

### ISSUE THREAD

**Issue by salomj** [magmafoundation/Magma#143]
**Describe the bug**
Running the installer fails to download all libraries

**To Reproduce**
1. Run `java -Xms32G -Xmx32G -jar Magma-3d116a0-installer.jar --installServer`

**Expected behavior**
Installation is successful 

**Additional context**

These libraries failed to download, try again.
com.typesafe:config:1.3.1
mysql:mysql-connector-java:8.0.18
co.aikar:fastutil-lite:1.0

All those packages return 404s.
http://files.minecraftforge.net/maven/com/typesafe/config/1.3.1/config-1.3.1.jar
http://files.minecraftforge.net/maven/mysql/mysql-connector-java/8.0.18/mysql-connector-java-8.0.18.jar
http://files.minecraftforge.net/maven/co/aikar/fastutil-lite/1.0/fastutil-lite-1.0.jar

**Comment by UeberallGebannt** [comment]
Dont use the installed, just download the server from magmafoundation.org and run it.
