### ISSUE TITLE
[Issue] Magma closes if folder name contains invalid characters

### ISSUE THREAD

**Issue by UeberallGebannt** [magmafoundation/Magma#144]
**Describe the issue**
The magma server closes itself after the auto update check if the folder name contains a '+'.
It also seems like the libraries are downloaded again.

**To Reproduce**
1. Create a folder with a '+' in name
2. Run magma in it

**Expected behavior**
The server should start.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50475262/83396178-e017db00-a3fb-11ea-834e-d0cc75ef05ba.png)

**Info (please complete the following information):**
- Magma Version: 3d116a0
- OS: Win10

[latest.log](https://mclo.gs/JtTDBAb)

**Comment by kwright02** [comment]
Fix: Don't include invalid characters in your folder name
