### ISSUE TITLE
[Issue] I cannot install Magma. I dont know why.

### ISSUE THREAD

**Issue by ThePocketMob** [magmafoundation/Magma#147]
So, I have been trying to install Magma Version Magma-3d116a0, but I run the .jar file, Select Install Client,  It starts downloading but Magma doesnt install and I get this in my log:
https://hasteb.in/ipuzumij.rb

Anyone know why this is happening?

**Comment by UeberallGebannt** [comment]
1. Magma is just a server, the client uses normal forge.
2. Dont use the installer, download the newest server jar from magmafoundation.org

Done
