### ISSUE TITLE
[BUG] Can't start server with Magma f36d5dd

### ISSUE THREAD

**Issue by BayyOuro** [magmafoundation/Magma#149]
**Describe the bug**

I can't start the server. At its start, a message appears saying that my version of Magma (f36d5dd) is not the latest and the new version will download. The following information appears in the console: Starting Magma
Downloading Server Libraries ...
Extracting Zip
Checking for new version...
_The latest Magma version is (cf1e2d5) but you have (f36d5dd). The latest version was built on 2020-06-07 at 23:19:12._
Updating Magma Jar ...
java.io.FileNotFoundException: https://ci.hexeption.dev/job/Magma%20Foundation/job/Magma/job/master/lastSuccessfulBuild/artifact/build/distributions/Magma-cf1e2d5-server.jar
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
at java.net.URL.openStream(URL.java:1045)
at org.magmafoundation.magma.downloads.MagmaUpdater.downloadJar(MagmaUpdater.java:68)
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:58)
Download Complete! Please restart the server.. After server restart the same is still displayed.

**To Reproduce**

Install Magma xxx on the server. Start the server and go to the console.

**Expected behavior**

I would like to start the server.

**Screenshots**

**Info (please complete the following information):**
- Mod Name:
 - Mod Version: 
 - Magma Version: f36d5dd
 - OS: Windows 10 Home 64 Bit

**Additional context**

**Comment by raed21** [comment]
same thing, on Ubuntu 16.04.6 LTS

**Comment by raed21** [comment]
https://ci.hexeption.dev/job/Magma%20Foundation/job/Magma/job/master/lastSuccessfulBuild/artifact/build/distributions/Magma-cf1e2d5-server.jar returns error 404

**Comment by raed21** [comment]
@Hexeption Thanks. commit b26b74a should be out in 3 minutes

**Comment by RiskerDegree87** [comment]
same thing as me using ubuntu 20.04, there is a problem with this os.

**Comment by halk6000** [comment]
sorry i have this same problem why i cant run serwer look my screan
![image](https://user-images.githubusercontent.com/45394417/97778158-8e73a800-1b75-11eb-895d-5678c5a3f0c7.png)

**Comment by RiskerDegree87** [comment]
can u type english, it would be better, i can't understand what is showing
in your terminal

**Comment by RiskerDegree87** [comment]
you can use vpn, it would fix it, or wait, because their servers are using
only one route which takes a long time to compile the server and pack it
into a jar file
