### ISSUE TITLE
Static Mobs/NPCs despawn from Pixelmon

### ISSUE THREAD

**Issue by OofbOye** [magmafoundation/Magma#15]
Hello, I'm attempting to test this with Pixelmon Reforged 7.0.8, and every time I unload the chunk then go back to it, any NPC that I placed down/spawned had despawned/disappeared.  If I try it on just a default forge server, the issue doesn't persist. I appreciate your work on the Magma project!

-OoFbOye

**Comment by Hexeption** [comment]
No longer applicable
