### ISSUE TITLE
Pixelmon Reforged - NPC's despawning.

### ISSUE THREAD

**Issue by SirMerijn** [magmafoundation/Magma#153]
So, for the past couple of days I've beens setting up a new Pixelmon server. I decided to go with Magma instead of Sponge because I wanted to use plugins and mods at the same time. Everything worked fine until I started setting up the NPC's. When the player is out of range of the NPC they will despawn.  I tried the same thing after with Sponge and that worked fine, the NPC's didn't despawn. Also on Magma I tried making them a persistent entity with a nametag, but that didn't help because nametags don't work on NPC's. 

I truely do hope they'll be able to fix this issue, Magma is just perfect for servers like these.

**Comment by kwright02** [comment]
You need to edit this to be the proper format.

**Comment by SirMerijn** [comment]
> You need to edit this to be the proper format.

What do you mean if I may ask?
