### ISSUE TITLE
[BUG] Voicechat Mod Issue

### ISSUE THREAD

**Issue by link1107** [magmafoundation/Magma#162]
I use Gliby's voicechat Reloaded mod for 1.12.2.
It works perfectly on pure Forge server.
But here is a bug which i've found while running this mod on Magma:
If i connect first time to the server - everything is fine.
If i disconnect and connect again - mod says thet Voicechat on this server is disabled, however other players, who had not reconnected, can use voicechat and have no problems with it.
This problem can be solved in 2 ways:
1) By connecting without Voicechat mod, getting error while connecting (Voicechat mod is missing), and then connecting with mod. Then it works until next disconnect.
2) By restarting server. Then you can connect and everything will work until you disconnect and connect again. After that mod is not working again, saying that mod is disabled on server, however it is not.

Here is the mod sources - https://github.com/IvasikDev/GlibysVoiceChat

**Comment by UeberallGebannt** [comment]
The post said Mohist at first, was that just a typo or doesn't it work on Mohist too?

**Comment by link1107** [comment]
Yep, i've tested on Mohist while trying to resolve this issue. Made similar post to their Issues section as well.

**Comment by kwright02** [comment]
After looking through the source I have some questions about your setup. Are you using a hosting service? If not, are you hosting locally or port forwarding? Do you have the issue locally still if so?

**Comment by link1107** [comment]
Yes, we use dedicated server. The network setup in mod is Minecraft network, not UDP. However when we tried UDP, there were no changes.
We also use waterfall and ServerBehindProxy option in mod's config. 

But during my tests i've tried to run magma locally on my PC without bungee or waterfall. And there was the same result. 

I've contacted with one of this mod's developer and he tries to fix this, but still without success.
I will let you know if we deal with it.

**Comment by Shawiizz** [comment]
I have this issue too. But I don't know what's the problem with this mod

**Comment by Redd56** [comment]
after testing it seems that it works for me, maybe its just the mod being wonk, or a misconfigureation, you do need to open the port you use for it

**Comment by kwright02** [comment]
After investigating, you need to make sure you have the port open that you're using as @Redd56 said above. This could involve port-forwarding and with some hosts, they won't give you an additional port.
