### ISSUE TITLE
[Issue] Certain crafting recipes do not work.

### ISSUE THREAD

**Issue by Krarma** [magmafoundation/Magma#163]
**Describe the issue**
A clear and concise description of what the bug is:
I'm running a modpack server with Magma and multiple players have reported that certain crafting recipes for the mods do not work.
**To Reproduce**
1. Create a Magma server
2. Install RLCraft
3. Try to craft for example, a string using a wool.
4. See error/issue

**Expected behavior**
A clear and concise description of what you expected to happen:
The block of wool is crafted into string.
**Screenshots**
If applicable, add screenshots to help explain your problem:
![Screenshot_8](https://user-images.githubusercontent.com/66957113/84666079-ee4c1800-af20-11ea-8210-86cfbe41eec3.png)

**Info (please complete the following information):**
- ModPack Name: RLCraft
 - Mod Version: 2.8.2 (Latest)
 - Magma Version: v8d2a711 (Latest at the time of writing)
 - OS: Windows

**Additional context**
Add any other context about the problem here:
Certain Crafting Recipes do not work as intended.
[latest.log] https://mclo.gs/vV93RlQ

**Comment by Amgelo563** [comment]
Try replicating the issue on a regular Forge server

**Comment by Krarma** [comment]
Will do.

**Comment by Krarma** [comment]
Everything was working as intended on a regular Forge server.
![image](https://user-images.githubusercontent.com/66957113/84673051-7f26f180-af29-11ea-9924-bd355f501d08.png)

**Comment by kwright02** [comment]
Is this error replicable outside of RLCraft?

**Comment by Krarma** [comment]
I'm not sure, I currently don't have any server to test it on.

**Comment by Amgelo563** [comment]
What about after performing `/gamerule doLimitCrafting false` ?

**Comment by Krarma** [comment]
Still not working

**Comment by Hexeption** [comment]
how did you get it to break I just launched the latest version of RLCraft with the latest version of magma and works fine?
@Krarma 
 ![](https://i.imgur.com/kAVXh3O.png)

**Comment by kwright02** [comment]
This has been determines to be a craft tweaker issue.
