### ISSUE TITLE
[BUG] Cannot install server

### ISSUE THREAD

**Issue by thepwrtank18** [magmafoundation/Magma#168]
**Describe the bug**
A clear and concise description of what the bug is:
When I try to install the server, it gives me an error saying my libraries failed to download.

**To Reproduce**
1. Download the server installer
2. Click on the jar
3. Try to install it in your directory

**Expected behavior**
A clear and concise description of what you expected to happen:
What is supposed to happen is that the server installs correctly.

**Screenshots**
If applicable, add screenshots to help explain your problem:
![Capture](https://user-images.githubusercontent.com/57580668/85250538-dd217080-b424-11ea-982d-7f226197d760.PNG)

**Info (please complete the following information):**
- Mod Name: None
 - Mod Version: None
 - Magma Version: vd36c8c5
 - OS: Windows 10 x64 (Build 19041.329, version 2004)

**Comment by Hexeption** [comment]
Don't use the installer
