### ISSUE TITLE
[BUG] DiscordSRV doesn't works on 1.12.2 99cbd59 version

### ISSUE THREAD

**Issue by ZarkxWorld** [magmafoundation/Magma#174]
**Describe the bug**
DiscordSRV doesn't works on magma 1.12.2 99cbd59 version

When i charge server it make an error and doesn't works, it was working fine after this update

**Screenshots**

![image](https://user-images.githubusercontent.com/43546157/85631685-45b35c00-b676-11ea-96ab-eb91e005b947.png)

https://bin.scarsz.me/437ff290-7b07-4b76-8426-add782531aea#vI2zNsglVeu13peU7M3GExsvrDYPWIAv

 - Magma Version: 99cbd59

**Comment by kwright02** [comment]
Have you tried on the newest version?

**Comment by kwright02** [comment]
Fixed in latest version

**Comment by nacjm** [comment]
FYI I just tested this on the latest version of magma and got the same issue: https://bin.scarsz.me/905109e1-a40a-486f-b504-4796512c8e0a#dYk5oOvfcKm1qao1X6VXYwcPhxqZOenv

**Comment by kwright02** [comment]
Interesting, I didn't get the issue. I'll look into it further

**Comment by Amgelo563** [comment]
DiscordSRV 1.19.0 works perfectly fine for me. So maybe @kwright02 can check what changes have been made between those two versions. For example, latest introduced (officially) 1.16.1 support.

**Comment by kwright02** [comment]
Works on latest version.
