### ISSUE TITLE
[Issue] Tardis Plugin

### ISSUE THREAD

**Issue by WarriorGamingserv** [magmafoundation/Magma#175]
**Describe the issue**
A clear and concise description of what the bug is: Okay so, i'm wanting to use the tardis plugin in magma, both the TARDIS plugin load and so does TARDISChunkGenerator so they are loaded, however, none of the commands work but they do a normal paper server with the same exact versions and plugins.

**To Reproduce**
1. Go to https://dev.bukkit.org/projects/tardis/files/2594118/download and https://dev.bukkit.org/projects/tardis/files/2594119/download
2. Add the plugins to your plugin folder (you should be able to load the tardis plugin without essentials or anything, it does not require any aditional plugin)
3. boot up the server and try to run a command like /tardisgive [name] key 1 (this should give you a tardis key, but it doesn't for me
4. the issue is that no commands are working, and i would like some help

**Expected behavior**
A clear and concise description of what you expected to happen: when i for example run the command /tardisgive [name] key 1, i expect to be given a tardis key, or when i go to craft a tardis i expect it to craft, but neither of this happen

**Info (please complete the following information):**
- Mod Name: TARDIS (Plugin) TARDISChunkGenerator (Plugin)
 - Mod Version: TARDIS (v3.8.3) TARDISChunkGenerator (v2.5.5)
 - Magma Version: 44e91f6
 - OS: Windows10

[latest.log] https://mclo.gs/EYq2N42

**Comment by kwright02** [comment]
@WarriorGamingserv could you please re-upload your log, the MCLOGS link has broken since your posting

**Comment by kwright02** [comment]
Tardis commands seem to work, you just have to make sure that you have permission and are reading the proper usage for them.
