### ISSUE TITLE
[BUG] Incompatibility with Vivecraft Forge Extension

### ISSUE THREAD

**Issue by nacjm** [magmafoundation/Magma#177]
**Describe the bug**
A clear and concise description of what the bug is:
Server crashes before minecraft can even start with vivecraft forge installed.
**To Reproduce**
1. install vivecraft forge extension
2. try to start server
3. watch the server crash royally with a invocation exception
4. See the server say: A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException 

**Expected behavior**
A clear and concise description of what you expected to happen:
The server to start up
**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name:Vivecraft Forge Extension
 - Mod Version: v10
 - Magma Version: v44e91f6
 - OS: ubuntu

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
Is your minecraft_server.jar in the same directory as your Magma jar?

**Comment by nacjm** [comment]
Yes

**Comment by kwright02** [comment]
Are you sure that you're using the correct version of Vivecraft extensions? Which version are you using?

**Comment by nacjm** [comment]
When I tested it I was using the latest version for forge vivecraft servers. The server didn’t even get to start forge before causing a securitytrapped exception

**Comment by kwright02** [comment]
Soloution: Use the spigot plugin extensions instead.
