### ISSUE TITLE
[BUG] Incompatible with Terrarium (Crashes on Startup)

### ISSUE THREAD

**Issue by tinyds** [magmafoundation/Magma#180]
**Describe the bug**
Upon starting the server with Terrarium installed with the level-type in server properties set to terrarium.earth, the server crashes soon after the plugins are initialized. I tested this twice- once on a server with other mods and plugins, and again in a clean Magma server with only Terrarium. The crash occurred in both instances.

https://www.curseforge.com/minecraft/mc-mods/terrarium

**To Reproduce**
1. Install Terrarium.
2. Make sure that the dimension generated is using Terrarium in the properties file.
3. Start the server.
4. The server will crash.

**Expected behavior**
The server runs fine with Terrarium on a normal Forge 1.12.2 installation.

**Screenshots**
The crash in particular resulted in this:

```
java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:436)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:971)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:456)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:861)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:733)
	at java.lang.Thread.run(Thread.java:748)
```

**Info (please complete the following information):**
- Mod Name: Terrarium
 - Mod Version: 1.1.1
 - Magma Version: 1494887
 - OS: Tested on Windows 10 and Slothhost Server

**Additional context**
The crash report for the clean installation has been attached.
[crash-2020-07-03_12.17.24-server.txt](https://github.com/magmafoundation/Magma/files/4870579/crash-2020-07-03_12.17.24-server.txt)

**Comment by kwright02** [comment]
So it seems there's an issue that it causes with the WorldServer's process of ticking the village stuff. I have no idea what would be causing this error so i'm going to be labeling that mod as incompatible till we can investigate

**Comment by Gegy** [comment]
This seems to be a similar issue as to https://github.com/Mohist-Community/Mohist/issues/629. While Terrarium is wrong here by not initializing the village fields, something is much more wrong if Terrarium's fake world implementations are getting ticked. Terrarium has hacky code to make sure that the world does not get tracked by Forge's dimension manager on world initialization, but I imagine Magma must be doing something different in world initialization where that hack does not apply properly?
