### ISSUE TITLE
[Issue] Server is crashing when a Player connects.

### ISSUE THREAD

**Issue by Motzkiste** [magmafoundation/Magma#181]
**Describe the issue**
Server is crashing after a Player tries to connect.

**To Reproduce**
1. Load my Modpack (also Server) from: [TechnicPack.net](https://www.technicpack.net/modpack/ampilution.1411837)
2. Start Server and Client
3. Try to connect

Maybe you need to set-up a Proxy (Waterfall) too, because I am using one.

**Expected behavior**
Crash after Player attemts to connect and server tries a config sync.

**Info (please complete the following information):**
 - Magma Version: Dev HEAD-1494887
 - OS: Ubuntu 18.04

**Additional context**
[crashlog](https://mclo.gs/Sd073oC)
Can't upload my latest.log... Maybe it's too large. Let me know if you rly need it.

The Server is running with Sponge without any Crash, but
- I really like Magma, because it's extremly fast
- I wan't to use my Spigot/Paper-Plugins

Thank you for your Help and this fantastic Mixture of Forge and PaperSpigot ^^

**Comment by Hexeption** [comment]
Fastworkbench issue please use the config in the discord

**Comment by Motzkiste** [comment]
Thank you! It worked ^^
