### ISSUE TITLE
[BUG] Server crash with ImprovedMobs

### ISSUE THREAD

**Issue by Picono435** [magmafoundation/Magma#185]
**Describe the bug**
Magma is causing NoSuchMethodError with ImprovedMobs mod. 

**To Reproduce**
1. Download the mod ImprovedMobs
2. Start a server with it and Magma
3. Join in the server, if the server does not crash try find an entity
4. Server crash...

**Expected behavior**
I expect to the server don't get crashed....

**Screenshots**
No Screenshots.

**Info (please complete the following information):**
- Mod Name: ImprovedMobs
 - Mod Version: 1.12.2-1.6.9
 - Magma Version: f3a5280
 - OS: Linux

**Additional context**
[crash-2020-07-15_11.32.26-server.txt](https://github.com/magmafoundation/Magma/files/4924263/crash-2020-07-15_11.32.26-server.txt)

**Comment by kwright02** [comment]
Please ensure to check that you're not using incopmpatible mods. You have RandomPatches and FoamFix core. Try without these mods and see if the error presists.

**Comment by Picono435** [comment]
I will try, I will say something tomorow.
