### ISSUE TITLE
[BUG] Server freez?

### ISSUE THREAD

**Issue by Kennar** [magmafoundation/Magma#19]
I do not know if this is a Magma engine error, but after generating the map about 10k x 10k after leaving the spawn and passing 20 blocks, the server freezes, all threads of the processor and RAM work 100%.
Now, after a whole day the server got crash: https://pastebin.com/KwNFkkY6

 - Magma Version: Magma-a3e77ec-server

**Comment by Hexeption** [comment]
Not a magma problem.

How much ram? u got

**Comment by Kennar** [comment]
10GB on the server where I was alone
