### ISSUE TITLE
[BUG]Server Crash with Mod railcraft

### ISSUE THREAD

**Issue by xsibit666** [magmafoundation/Magma#190]
In the near of coking plant the Server Crashes

https://github.com/Railcraft/Railcraft/issues/1961

But on a normal Forge Server the Problem dosent exist.

Crash Log folow

**Comment by kwright02** [comment]
You haven't provided a crash log, and it's unclear what you're saying the issue is. Please consider seeking help VIA a ticket on the discord.

**Comment by xsibit666** [comment]
How is the Name of the discort Server

**Comment by UeberallGebannt** [comment]
> 
> 
> How is the Name of the discort Server

https://discord.gg/jy2YVx

**Comment by xsibit666** [comment]
Thx
