### ISSUE TITLE
[Issue] Spearbug

### ISSUE THREAD

**Issue by Krarma** [magmafoundation/Magma#191]
**Describe the issue**
A clear and concise description of what the bug is:
Whenever someone dies on my server, they drop multiple stacks of spears, despite them not having spears in their inventory at all. They also drop their loot, but it's incredibly hard for them to get it back when it's inbetween so many spears. I am pretty sure this only happens to people who've used a spear before, and it's only possible with the stonespear.
**To Reproduce**
1. Make a RLCraft Server with Magma
2. Use a stone spear
3. Die naturally
4. See error/issue

**Expected behavior**
A clear and concise description of what you expected to happen:
I expect the player to just die and only drop their loot, but what instead happens is that lots of spears drop.
**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: RLCraft
 - Mod Version: Latest
 - Magma Version: 
 - OS: Magma-40c88e5-server

**Additional context**
Add any other context about the problem here:
This has always been an issue for as long as I've used magma.
[latest.log] (Please upload your latest.log to https://mclo.gs and replace this text with the url)

**Comment by kwright02** [comment]
you haven't provided a crash log and it's unclear what you're claiming the issue to be. Please seek help via ticket on discord.
