### ISSUE TITLE
[Feature] Compatibility with BKCommonLib, TrainCarts & related mods

### ISSUE THREAD

**Issue by vico93** [magmafoundation/Magma#196]
**Describe the feature**
Personally, the main reason i would use an Forge/Spigot hybrid server is to have TrainCarts plugin to manage my railroads. But there is a problem: in all previous hybrids for 1.12 there isnt support for [BKCommonLib](https://github.com/bergerhealer/BKCommonLib), [TrainCarts](https://github.com/bergerhealer/TrainCarts) dependency, because it have a lot of reflection and other issues, rendering impossible to use TrainCarts here.

**Reason why this feature should exist**
It would be a great feature for Magma if it supports BKCommonLib, just having the chance to use TrainCarts with mods (i tried to ask myself a lot of times in some big modder discord servers about a possible reimplementation of TrainCarts directly on Forge, but nobody seems interested on do it) would be a nice incentive for several players and server owners, given the dork state minecarts behave on vanilla. I know railcraft exists, but it add too much complexity in comparision to TrainCarts (it goes straight to the point to add a basic routing system and linking minecarts together to form a train).

**Screenshots**
![a silly gif showing how traincarts change minecarts behavior](https://gamepedia.cursecdn.com/minecraft_gamepedia/7/70/TrainCarts_train_1.gif?version=ff94eee0109f0254f3335a72c5cdb588)

**Comment by Amgelo563** [comment]
I think it'd be better if you can open an issue reporting what exactly happens when you try those plugins (crashes, errors, etc), instead of a feature request.

**Comment by vico93** [comment]
@Amgelo563 right, will close that and try to run MAGMA just with BKCommonLib and TrainCarts to see what happens.

I made the issue that way because i assumed "by default" Forge/Spigot hybrids doesnt have compatibility with BKCommonLib.
