### ISSUE TITLE
Crashing after death

### ISSUE THREAD

**Issue by MacWhinny** [magmafoundation/Magma#2]
Ok so It's defo a Magma issue. 

I created a new test server. Tried it without Magma and the server or client didn't crash. The added Magma with plugins and the client crashed. Then removed all plugins and the server crashed, when i hit respawn.

Here's the crash report

https://hasteb.in/loxoqiwi.rb

**Comment by overclock22** [comment]
I too am getting these ticking player crash after death.

**Comment by MacWhinny** [comment]
> I too am getting these ticking player crash after death.

What modpack you using? Can you provide your logs and crash report for Hex
