### ISSUE TITLE
CMI compatibility problem.

### ISSUE THREAD

**Issue by ConflictKingdoms** [magmafoundation/Magma#204]
**Describe the bug**
I don`t know if its a bug or what this is. but its at least not normal behavior

**To Reproduce**
1. start the server and it will disable itself. nothing to reproduce you will see the error instantly in my pastebin.

**Expected behavior**
Not like this.

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Plugin Name: CMI
 - Plugin Version: 8.7.4.1
 - Magma Version: This server is running Magma version 2798a77 (Implementing API version 1.12.2-R0.1, Forge Version 14.23.5.2838)
 - OS:  Ubuntu 18.04.4 LTS [Using Pterodactyl Panel]

**Additional context**
LOG: https://pastebin.com/YeXKDEc6

**Comment by CloudeLecaw** [comment]
i dont know if this really is a feature to support one of the 1000tns forks outside there.....

[13:44:52] [Server thread/INFO] []: Your server version is not compatible with this plugins version! Plugin will be disabled: v1_12_R1

This line tells you you cant use a plugin with this fork. im sure there are more mod/plugin forks like sponge and co that have this problem too. The answer... no support for other forks.
Spigot, Paperspigot  and maybe.. but only maybe bukkit..
Thats all no other fork support

**Comment by nacjm** [comment]
I will point out that CMI works practically perfectly on Mohist which is another fork of bukkit/spigot. So if its just CMI disabling it because it doesn't recognize the core there should be a way to override it if the server owner can understand the risks of doing so.

**Comment by kwright02** [comment]
I'm going to recommend going into your magma.yml and enabling the server brand override so that Magma presents itself to plugins as being Spigot. After doing this please retest and see if the issue persists.

**Comment by CloudeLecaw** [comment]
Interesting workarround for this fork. But one think this entry cant change. Codechanges...  Well let see if this workarround works for you :)

**Comment by ConflictKingdoms** [comment]
> I'm going to recommend going into your magma.yml and enabling the server brand override so that Magma presents itself to plugins as being Spigot. After doing this please retest and see if the issue persists.
I will have to try this out just saw this message just now :D 





> Interesting workarround for this fork. But one think this entry cant change. Codechanges... Well let see if this workarround works for you :)

thanks i also hope it works :D

**Comment by ConflictKingdoms** [comment]
> I'm going to recommend going into your magma.yml and enabling the server brand override so that Magma presents itself to plugins as being Spigot. After doing this please retest and see if the issue persists.

IT WORKED! :D Even with latest magma that was updated :D
