### ISSUE TITLE
[BUG] Magma breaks maps and overloads the server.

### ISSUE THREAD

**Issue by LuciusKobel** [magmafoundation/Magma#206]
**Describe the bug**
Last time I reported a problem with players leaving and the subsequent crash of the server. Now the problem has only worsened. Incorrectly generated chunks were found on the same map as last time. When approaching them, the server was closed due to a crash. This happened when the block reached 3000 on one of the axes. We had to get the players out of there and ask them not to go beyond the conditional border. But then, because of something, the server started massively littering with the warning "[net.minecraft.world.storage.loot.LootTable]: Tried to over-fill a container". Immediately after this, the hosting service stopped working with the map. Even if there is no one on the server, the processor was always 100% full and the RAM was constantly filled with something. As a result, when the RAM limit was exhausted, the server was silenced and showed no signs of working properly. The processor was loaded at 0%, and all 4 GB of RAM was fully occupied. I didn't respond to any commands, not even the power supply commands. It had to be turned off each time directly by disconnecting from the power supply. When restarting the server, everything is fine at first. Then, when the players joined the server, the chunks were updated and all the reservoirs in the area instantly disappeared. Those reservoirs that had not yet been updated were immediately emptied when approaching. The console again constantly began to display this warning. The server is loaded again at 100%. In the end, I got tired of it and decided to try to create a new world. I thought everything was going to be all right. I thought it was all because of a faulty world. When I joined the new map, everything was fine. I left the server running. After a while, I decided to look at the server status again, as immediately I saw how the RAM was completely full, and the server was stalled. The server did not respond to commands. Rebooted the server by disconnecting from the power supply. Obviously, this is due to Magma. To confirm my assumptions, I rebooted the server and went back to the map. All the reservoirs immediately disappeared. Left only the bottom of the river.

**To Reproduce**
1. Install the server.
2. Put mods.
3. Create a map with this list of mods.
4. Join the game.
5. After loading the world, exit.
6. Keep the server running for two to three hours.
7. Trying to connect to. (It does not, the server may not respond.)
8. If necessary perform a restart of the server.
9. Connect to the server.

**Expected behavior**
After connecting the player to the server, he will see the absence of any water in the area. (With some exceptions, only a small amount of water will remain.) After two hours, the server will not respond to commands.

**Screenshots**
(The graph on the left shows RAM usage. The graph on the right shows CPU usage.)
Use of server resources on the new map two hours after the server is started.
![изображение](https://user-images.githubusercontent.com/68869618/89099787-70719c80-d3fa-11ea-8875-ba5b9ba3a058.png)
Using server resources on the old map.
![изображение](https://user-images.githubusercontent.com/68869618/89100535-52a73600-d400-11ea-83c9-dada5cc8c57a.png)
Drained rivers on the old map.
![изображение](https://user-images.githubusercontent.com/68869618/89100172-c0059780-d3fd-11ea-9457-93fc6d236daf.png)

**Info:**
- Mod Name: (The list of mods is located below.)
- Magma Version: 2c7ce42
- OS: Linux

**Additional context**
Logs:
https://mclo.gs/kPKGNow
(The most recent crash report with a list of mods:)
https://mclo.gs/cb3AQVg

**Comment by kwright02** [comment]
btw EnderIO doesn't work with Offline mode

**Comment by LuciusKobel** [comment]
> 
> 
> btw EnderIO doesn't work with Offline mode

I don't think this is the source of the problem, as there are no problems on the other core.

**Comment by kwright02** [comment]
@LuciusKobel can you please provide a new server log, the link from before has died

**Comment by kwright02** [comment]
This has been determined to be user hardware

**Comment by LuciusKobel** [comment]
I can re-attach the old log since I haven't used Magma since. But what does "this has been determined to be user hardware" mean?

**Comment by UeberallGebannt** [comment]
Im not 100% sure but it seems like it is because of your hardware

**Comment by LuciusKobel** [comment]
I don't understand how this could be related to my server hardware? When I use other cores, there are no problems with the map. What should I do?

**Comment by kwright02** [comment]
"When I use other cores, there are no problems with the map." You solved your own problem it seems.

**Comment by LuciusKobel** [comment]
But I would like to use your core. So I would like to know how this can be fixed.

**Comment by UeberallGebannt** [comment]
I think kwright02 thought about the cpu cores
