### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ghosty366** [magmafoundation/Magma#207]
**Describe the bug**
every time my friend tries to join with all correct mods he gets a thing saying fatally missing registry entries

**To Reproduce**
1. join a server

**Expected behavior**
him joining the game successfully

**Screenshots**
![bug](https://user-images.githubusercontent.com/32891973/89205083-c3735d00-d57c-11ea-9786-04623306d8a4.png)

**Info (please complete the following information):**
 - Magma Version: Magma Dev HEAD-2c7ce42, also previous versions
 - OS: windows 10

**Additional context**
nope

**Comment by kwright02** [comment]
You need to provide us a server log for us to be able to figure anything out. https://mclo.gs

**Comment by kwright02** [comment]
@Ghosty366 please respond with more context/info or this will be closed.

**Comment by Ghosty366** [comment]
i can't get the log yet, i got to wait until 10

**Comment by Ghosty366** [comment]
pm

**Comment by kwright02** [comment]
@Ghosty366 please provide a log or this ticket will be closed

**Comment by SSKirillSS** [comment]
Share your server configs to friend. Looks like server configs different with a client. And, yea, provide a log.
