### ISSUE TITLE
[BUG] - ThaumicAugmentation Fractures doesn't work at all

### ISSUE THREAD

**Issue by SSKirillSS** [magmafoundation/Magma#214]
**Describe the bug**
I have emptiness world. It contains fractures, that linked with other fractures in other world. So, when I open one and go through it, I must be teleported to fracture in other dimension, but... It teleports me to coords of potentially fracture(I think, but not sure), but in same dimension
Original issue: https://github.com/TheCodex6824/ThaumicAugmentation/issues/81

**To Reproduce**
1. Use a casting gauntlet with an attached and charged Impetus Conductor augment on the fracture to open it
2. Go through fracture
3. If it works - try to go back trough it

**Expected behavior**
Described above.

**Screenshots**
https://www.youtube.com/watch?v=_nARKEyq6FA
https://www.youtube.com/watch?v=NvVKT4pfSrE

**Info (please complete the following information):**
Magma-2c7ce42-server
Baubles-1.12-1.5.2
CustomNPCs_1.12.2-(01Oct19) (Not needed, but I have it in my test modpack)
Thaumcraft-1.12.2-6.1.BETA26
ThaumicAugmentation-1.12.2-2.0.3

**Comment by kwright02** [comment]
It appears there is a minor issue in the way that dimension transfer is happening with the addition of craftbukkit dimension handling. Adding this to the list.

**Comment by kwright02** [comment]
I can't figure out how to open the gauntlet again, so please test this as it should be fixed.
