### ISSUE TITLE
[BUG] - BetterHurtTimer incompatibility?

### ISSUE THREAD

**Issue by SSKirillSS** [magmafoundation/Magma#216]
**Describe the bug**
This mod just prevents server startup.

**To Reproduce**
1. Install BetterHurtTimer to mods folder
2. Run the server

**Expected behavior**
Working mod, I think.

**Info:**
BetterHurtTimer-1.12.2 (any version of mod)
Magma-2c7ce42-server
Any mod with mixins installed. I've tried with Bewitchment and MixinBootstrap.

**Additional context**
Mod github: https://github.com/ArekkuusuJerii/BetterHurtTimer
Logs: https://pastebin.com/gYCXYtCV

**Comment by kwright02** [comment]
So it seems that the mod uses Mixins to achieve part of its functionality. This part of the code is throwing some kind of mixin injection error: `@Redirect(method = "attackEntityFrom(Lnet/minecraft/util/DamageSource;F)Z", at = @At(target = "Lnet/minecraft/entity/EntityLivingBase;damageShield(F)V", value = "INVOKE"))
    public void damageShield(EntityLivingBase entity, float damage) {
        HurtCapability capability = Capabilities.hurt(entity).orElse(null);
        if (capability != null) {
            if (capability.ticksToShieldDamage > 0) {
                if (Double.compare(Math.max(0, capability.lastShieldDamage + BHTConfig.CONFIG.damageFrames.nextAttackDamageDifference), damage) < 0) {
                    damageShield((float) (damage - capability.lastShieldDamage));
                    capability.lastShieldDamage = damage;
                }
            } else {
                damageShield(damage);
                capability.lastShieldDamage = damage;
                capability.ticksToShieldDamage = BHTConfig.CONFIG.damageFrames.shieldResistantTime;
            }
        } else {
            damageShield(damage);
        }
    }` and I have no clue how to go about fixing that

**Comment by SSKirillSS** [comment]
Maybe this thing can be fixed on a mod side?

**Comment by kwright02** [comment]
Hard to say because I don't know what the injector failure is

**Comment by kwright02** [comment]
Ah! Just read into the log a little further, it seems that when trying to inject it can't find the EntityLiving or EntityLivingBase classes to inject into.

**Comment by SSKirillSS** [comment]
So.. What we can do in this situation?

**Comment by kwright02** [comment]
(*What can we do in this situation) (Just helping you out)

I'm not entirely sure, it seems that there is an issue with class mapping at run time which is more of a Hex issue because he knows more about how that all works.

**Comment by ArekkuusuJerii** [comment]
The error message is actually a bug in the Mixin crash report, its practically impossible to find the actual issue just from the log.

**Comment by kwright02** [comment]
True, I still think that it has something to do with it finding the classes at runtime

**Comment by Hexeption** [comment]
I know the issue ive looked into this and I know what is wrong they will be a fix out asap

**Comment by kwright02** [comment]
Sounds good, i'll close this up then

**Comment by Hexeption** [comment]
Looked into this and due to how Bukkit handles damage fixing this would break plugins that use shields.

Due to this, we can't fix this without breaking plugin support.

**Comment by kwright02** [comment]
You should just make a config option so people can choose. That way people that don’t need plugins that use shields can use better hurt timer

**Comment by ArekkuusuJerii** [comment]
Ah no need I fixed it on my side, it runs fine on the server now, Kirill can testify. Thank you :>
