### ISSUE TITLE
[BUG] - Chatty (plugin) json formatting

### ISSUE THREAD

**Issue by SSKirillSS** [magmafoundation/Magma#217]
**Describe the bug**
Enabling JSON formatting in plugin config and writing something to chat causes that JSON doesn't work at all. If I try to reproduce this issue on mohist, it throws this stacktrace: https://pastebin.com/k23HXp9c
But on magma it just doesn't work without any errors.

**To Reproduce**
1. Enable JSON in Chatty config
2. Send message to chat
3. Try to click on nickname in chat, hover cursor on it

**Expected behavior**
Working JSON, maybe

**Info (please complete the following information):**
Chatty - https://github.com/Brikster/Chatty/actions/runs/192338972
Magma-2c7ce42-server

**Additional context**
Original issue (on Russian): https://github.com/Brikster/Chatty/issues/95

**Comment by kwright02** [comment]
So your expected behavior is to see things when hovering over names in chat?

**Comment by SSKirillSS** [comment]
Yup.
