### ISSUE TITLE
[BUG] Tablist Header/Footer Error

### ISSUE THREAD

**Issue by UeberallGebannt** [magmafoundation/Magma#22]
**Describe the bug**
If i use this plugin which edits the tablist header and footer, it wont work and there are errors in the console. The nametags work.

**To Reproduce**
1. Download https://www.spigotmc.org/resources/varo-odv-suro-titan-plugin-telegram-discordbot-backups-ranks-nametags-more.71075/
2. Join the server

**Expected behavior**
You should see the tablist header/footer.

**Screenshots**
-

**Info (please complete the following information):**
- Plugin Name: Varo, ODV, SuRo & Titan Plugin
 - Mod Version: 1.2
 - Magma Version: 4ade92a
 - OS: Windows 10

**Additional context**
-

**Comment by Hexeption** [comment]
![image](https://user-images.githubusercontent.com/4052647/69466224-58ca1a80-0d7b-11ea-84e3-2948d4bea8d2.png)
Looks working to me

**Comment by UeberallGebannt** [comment]
The nametags work, the header/footer doesn't work.

**Comment by Hexeption** [comment]
What should it be doing?

**Comment by UeberallGebannt** [comment]
It should look like this (customizable in messages.yml)
![2019-11-22_23 59 00](https://user-images.githubusercontent.com/50475262/69466405-3dafd880-0d84-11ea-8e0d-075cbebeb672.png)

**Comment by UeberallGebannt** [comment]
The plugin is open source btw https://github.com/CuukyOfficial/VaroPlugin

**Comment by Korne127** [comment]
As the developer of that plugin, I'm pretty sure this is cause by #33 
The plugin uses many methods from org.apache and other ones which aren't in the Magma.jar for whatever reason. This is not the only bug resulting from that, none of the times should work as well.
As my issue (#33) about this has been closed without any reasoning, I'm unsure on whether compatibility will be added.
