### ISSUE TITLE
[BUG] keepInventory doesnt work in other dimensions

### ISSUE THREAD

**Issue by Shumooo** [magmafoundation/Magma#220]
**Describe the bug**
When I use /gamerule keepInventory true, it only activates it for the overworld, it doesn't activate it in any other dimension (Nether,End,Twilight Forest)
Edit : If I do /gamerule keepInventory true while in the nether (or other dimensions) it works for the first time...but then it doesn't. 
I tested this in a modless and pluginless server but still using magma, it still happens, so the plugins or mods aren't causing it.
The server is hosted by aternos, I don't know if that can cause the bug, but this information could help.
AFTER THE NEW UPDATE: keepInventory works in all dimensions but the nether. Weird.
**To Reproduce**
1. Turn on keepInventory
2. Go to a dimension that isnt the overworld
3. Die

Alternative:
1. Go to another dimension
2. Turn on keepInventory
3. Die (this time it works)
4. Go to the same dimension again
5. Die again (this time it doesn't)

**Expected behavior**
Well, I expected keepInventory to work and for my items to be safe, but that just doesn't happen and I instead lose all my items.

**Info (please complete the following information):**
 - Magma Version: 1.12.2 (v4695040)

**Comment by LeviPawlak** [comment]
Weird, it looks like for some reason the individual worlds data for game rules doesn't get saved but the generic server game rule gets saved. But then the overworld uses the generic server game rule but for some reason the nether one doesn't. 

At least that's what I can tell from playing around myself. But to me it seems that the game rule is saved until the nether dimensions gets unloaded (because it automatically unloads when no players are in it). 

Looking into it more.

**Comment by Shumooo** [comment]
I've tried with the new update, and while it seems to work in all dimensions!... except the Nether!
I've tried it with the Aether and the Twilight, and it works there, but when I try in the nether...I just lose my items.
That's kinda weird.

**Comment by Amgelo563** [comment]
I believe there's an option on the magma.yml file about auto unloading dimensions, maybe try playing around with that option until you get something.

**Comment by Shumooo** [comment]
> 
> 
> I believe there's an option on the magma.yml file about auto unloading dimensions, maybe try playing around with that option until you get something.

I tried, apparently the nether is the only dimension that is automatically unloaded...but when I try to remove that option or just the dimension, it doesnt let me. Everytime I start the server it goes back to being -1 (which, if I remember correctly, is the nether)
