### ISSUE TITLE
Mod incompatibility - FastWorkbench

### ISSUE THREAD

**Issue by CrimsonXMC** [magmafoundation/Magma#221]
During trying to load a Magma server with the Skyfactory 4 modpack, it crashes with this message 
[crash-2020-08-17_07.06.24-server.txt](https://github.com/magmafoundation/Magma/files/5082426/crash-2020-08-17_07.06.24-server.txt)
It seems to be an incompatibility with FastWorkbench

    Mod Name and version: FastWorkbench-1.12.2-1.7.3
    Magma Version:
    Magma version  Magma Dev - Stable 1
    OS: Ubuntu 20.04.1 LTS

**Comment by UeberallGebannt** [comment]
Use the config from the #incompatible-mods channel on discord.

**Comment by Kurtoid** [comment]
For those coming from Google:
```
# Configuration file

crafting {
    # If the recipe book and all associated functionality are fully removed. [default: true]
    B:"Disable Recipe Book"=false

    # If a testing variant of shift-click crafting is enabled. [default: true]
    B:"Experiemental Shift Crafting"=true
}

```
