### ISSUE TITLE
[BUG] potions — 1.12.2

### ISSUE THREAD

**Issue by Denaris01** [magmafoundation/Magma#223]
Informations
The Minecraft Version is 1.12.2
Version Magma version 8e646d7

Description
when ever a player gets a modded potion, creative or survival, in their inventory, it turns into either a uncraftable or witch's brew potion.

How to reproduce
get any modded potion in to your inventory. if you can.

The Mohist Server has the same BUG: https://github.com/Mohist-Community/Mohist/issues/293
The catserver don't have this BUG, i have testet this.

Thank You.

**Comment by Hexeption** [comment]
What Mod have you tested so we can fix

**Comment by Denaris01** [comment]
This BUG are whit all Mod's, which have own potions. I' am use Thermal Expansion.

**Comment by Hexeption** [comment]
Okay ill take a look a potions

**Comment by Denaris01** [comment]
Very nice and fast. Modded potions works now. Please make a onetime donation link via PayPal on your Homepage. 
I don't like monthly patreon.
