### ISSUE TITLE
[BUG] ICE AND FIRE X NOT FINITE

### ISSUE THREAD

**Issue by GlitxhSenpai** [magmafoundation/Magma#224]
**Describe the bug**
A clear and concise description of what the bug is:
the bug happens when an ice and fire dragon latches you in their mouth, this causes the server to crash and your player data pos values to become NaN, to fix you either delete the playerdata or edit it back with nbtexplorer

**To Reproduce**
Steps to reproduce the behavior: find a dragon and let it bite you

**Expected behavior**
A clear and concise description of what you expected to happen:
it shouldnt crash lmao
**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: ice and fire
 - Mod Version: 1.9.1-1.12.2
 - Magma Version: idek it updates too much
 - OS: linux

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
Please share the crash log file as well

**Comment by GlitxhSenpai** [comment]
> Please share the crash log file as well

the crash report is the exact same as the one shown in the discord ticket
