### ISSUE TITLE
[Feature] Please add an option for disable ForgeGeneratorWorlds

### ISSUE THREAD

**Issue by Denaris01** [magmafoundation/Magma#225]
**Describe the feature**
Please add an option for disable ForgeGeneratorWorlds in the magma.yml like this:

![Screen-2020-08-19_16-38-46](https://user-images.githubusercontent.com/22527229/90649043-8a084600-e23a-11ea-87e2-3431ef755646.png)
It can also be a White- or Blacklist. I need only a single Forgeworld whit all Resources from all Mods: Farmworld

**Reason why this feature should exist**
Mods like Thaumcraft (has no option in Configfile) generate in every World your resources (trees and Ores) and it is impossible to make a clean flat world or a clean plotworld without deactivating the mods.

**Screenshots**
If applicable, add screenshots to help explain your feature:
![2020-08-18_18 55 36](https://user-images.githubusercontent.com/22527229/90648508-e6b73100-e239-11ea-96dd-1c1afe301a69.jpg)

Thank you.

**Comment by kwright02** [comment]
I don't have the knowledge to tackle this, but for now what I would suggest is just importing a world that you generated externally
