### ISSUE TITLE
[BUG] Impossible to go to the end

### ISSUE THREAD

**Issue by Sparky200** [magmafoundation/Magma#227]
**Describe the bug**
It's impossible to go to the end, as the title states. The portal lights and the sound plays, but you phase through it, and it doesn't teleport you.

**To Reproduce**
Install the latest magma version
Run server, join, and try to join the end

**Expected behavior**
Actually teleport you

**Screenshots**
https://cdn.discordapp.com/attachments/741036421304942683/746131690786652241/unknown.png

**Info (please complete the following information):**
(Removed Mods)
 - Magma Version: c5b3496
 - OS: Tested on both Windows and Linux

**Additional context**
Tried everything including deleting all mods. Used just forge and it was fine. It worked on earlier versions of Magma, don't know if this is the one that broke it. This needs to be fixed, you corrupted my server's world files.

**Comment by kwright02** [comment]
We have resolved this issue. Please also make sure that the dimension 1 is not listed in the autoUnloadDimensions list in the magma.yml
