### ISSUE TITLE
Cubic chunks mod support?

### ISSUE THREAD

**Issue by KweezyPlay** [magmafoundation/Magma#229]
**Describe the issue**
A clear and concise description of what the bug is:
can't run the server with cubic chunks mod

**To Reproduce**
1. install cubic chunks mod

**Expected behavior**
working server

**Info (please complete the following information):**
- Mod Name: cubic chunks
 - Mod Version: the latest
 - Magma Version: the latest
 - OS: ubuntu 20.04 LTS

latest.log:
https://mclo.gs/My2C5rI

**Comment by kwright02** [comment]
Sorry but this won't be added due to it not being compatible with bukkit in any way.
