### ISSUE TITLE
[BUG] Server crash related to Grimoire of Gaia 3 Horses

### ISSUE THREAD

**Issue by CmdrJane** [magmafoundation/Magma#232]
Server crash whenever mob from grimoire of gaia spawns on a horse from grimoire of gaia

**To Reproduce**
1. Install latest version of Grimoire of Gaia (1.7.2)
2. Fly around the world for some time or summon dullahan or centaur (what?) on horse
3. ???
4. Get crashed

**Expected behavior**
Server shouldn't crash 

**Info (please complete the following information):**
- Mod Name: Grimoire of Gaia 3
 - Mod Version: 1.7.2
 - Magma Version: d02c5b5
 - OS: Win 10

**Additional context**
Crash Log: https://pastebin.com/EX2K8qZ6

**Comment by CmdrJane** [comment]
Mohist-Community/Mohist #235

**Comment by CmdrJane** [comment]
The same issue on Mohist:
 Mohist-Community/Mohist#235
 Mohist-Community/Mohist#238

**Comment by Picono435** [comment]
It occurs to me too. Server crashes tons of times because of it.
