### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Quantelon** [magmafoundation/Magma#233]
**Describe the issue**
A clear and concise description of what the bug is:Cmd closes immediately when i open the start "folder".

**To Reproduce**
Steps to reproduce the behavior:So I watched a few youtube videos and decided to try it myself...so everything worked well until I put both "folders" in the "main folder"...the start folder didnt work(it closed cmd immediately).So I clicked the folder that I downloaded and suddenly all the things appeared...so I clicked on the Eula, set it to TRUE and saved it.I somehow got into minecraft and made a test server everything worked and I could do /pl.Then I decided to put a plugin and a mod (into the mod and plugin folder)it worked then I tried to start it with the "2 folders from the beginning)....and it didnt work.Disclaimer:no I didnt forget to name the foldersit or to change the options...I did everything you needed to do:(
4. See error/issue

**Expected behavior**
A clear and concise description of what you expected to happen:It should open cmd and start minecraft with all the mods but it doesnt.

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name:
 - Mod Version: 
 - Magma Version: 
 - OS:

**Additional context**
Add any other context about the problem here:

[latest.log] (Please upload your latest.log to https://mclo.gs and replace this text with the url)

**Comment by LeviPawlak** [comment]
What version of Magma? What mods and plugins did you add? Also could you upload your start script to https://mclo.gs .

**Comment by kwright02** [comment]
Please update your post to correctly fill out the format. Thanks.

**Comment by josephworks** [comment]
Please edit your issue and fill in the missing information (latest.log, Magma Version, OS).
