### ISSUE TITLE
[BUG] Problem generating chunks

### ISSUE THREAD

**Issue by Kennar** [magmafoundation/Magma#24]
There are problems with the generation of chunks on the server, the problem appears after resetting the server and moving to an area where nothing has been generated yet. Can you count on quick repair?
https://imgur.com/a/0Wdjjho

 - Magma Version: Magma-4ade92a-server

**Comment by Hexeption** [comment]
Can't Replicate this

**Comment by Kennar** [comment]
When it comes to seeing if it works, just go to the server, go somewhere and generate new sites, then save-all and stop. Start the server and go further to see what is happening, I do not know if it is the fault of some fashion or engine, but for singles there are no such problems.
