### ISSUE TITLE
[Issue]Autoupdate

### ISSUE THREAD

**Issue by mozomenku** [magmafoundation/Magma#240]
Hello, I would like to know if there is a way to turn off autoupdating as it made my server uplayable on the verison 9c5aa93(problem with LittleTiles and TinkersConstruct), and it was working before. When I take version 76d7610 it is being updated to 9c5aa93 and the same goes with other versions.

**Comment by Amgelo563** [comment]
I'ts on the magma.yml file, set `auto-update` to false.

**Comment by mozomenku** [comment]
Thanks
