### ISSUE TITLE
[Issue] Dead links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Yey007** [magmafoundation/Magma#241]
Minor issue but I guess important for beginners (such as myself) that want to take a look at the project.

**Describe the issue**
Most links to images appear to be dead

**To Reproduce**
1. Click on a link such as "import"

**Expected behavior**
It takes me to a valid image

**Screenshots**
![image](https://user-images.githubusercontent.com/55263178/92336812-a85fa580-f072-11ea-9189-b077e11f6c6e.png)

Some of these people can figure out but others aren't so obvious. I know what some of these images should be but not all so I can't really fix everything. If anyone can tell me what the links are/fix it that may help newcomers. Thanks!

**Comment by kwright02** [comment]
A new site is coming out soon
