### ISSUE TITLE
[BUG] CC:Tweaked turtles doesnt generate any sound when placing blocks

### ISSUE THREAD

**Issue by vico93** [magmafoundation/Magma#242]
**Describe the bug**
In [`ade7751`](https://github.com/magmafoundation/Magma/releases/tag/vade7751) seems like CC:Tweaked's turtles placing sounds became broken. I didnt remember to experience this issue on previous versions, and it works as intended in both singleplayer and "pure" Forge dedicated server.

**To Reproduce**
1. Install `cc-tweaked-1.12.2-1.89.2.jar` from [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked/files/all?filter-game-version=2020709689%3A6756) (latest version for 1.12.2);
1b. Also install [Plethora Peripherals](https://www.curseforge.com/minecraft/mc-mods/plethora-peripherals/files/all) (latest version for 1.12.2);
3. Boot up a magma instance from the reported build only with BKCommonLib ([build 899](https://ci.mg-dev.eu/job/BKCommonLib/)) and TrainCarts ([build 703](https://ci.mg-dev.eu/job/TrainCarts/)) and CC:T/Plethora
4. Get a turtle in creative menu, fuel it (using command `refuel all`) and try to use any program which place blocks (like stock `tunnel`, place it on a place without anything at bottom, load turtle inventory with stone and run `tunnel xx` - xx is the distance to cover)

**Expected behavior**
In singleplayer and "pure" Forge dedicated server, the turtles makes the same sounds players do when placing blocks.

**Info (please complete the following information):**
 - Mod Name: [CC:Tweaked](https://github.com/SquidDev-CC/CC-Tweaked) and [Plethora Peripherals](https://github.com/SquidDev-CC/plethora);
 - Mod Version: CC:T 1.89.2 and PP 1.2.3
 - Magma Version: `ade7751`
 - OS: Windows 10 x64 - build 2004

**Additional context**
If you cant reproduce the issue just with CC:T/Plethora/BKCL/TrainCarts installed, i can send you my server folder for further investigation.

**Comment by kwright02** [comment]
This has to do with the fact that Magma doesn't yet correctly handle Fake Players
