### ISSUE TITLE
[BUG] Chat and Name error

### ISSUE THREAD

**Issue by RobinNightWing** [magmafoundation/Magma#243]
**Describe the bug**
Forge mods are incapable of modifying the chat with forge functions. Mods like FTB Utilities, which uses Forge to change nicknames and to allow players to speak in _italics_ and **bold** in chat do not work

**To Reproduce**
1. Install Magma, and FTB Utils
2. Change your nickname
3. Speak in chat with *'s following the regular discord system to see the chat bug
4. Speak in chat normally to see the nickname bug

**Expected behavior**
Nicknames are supposed to change. You can see that the nicknames have indeed changed if you press tab and see the multiplayer tab, which shows the change in nicknames. Chat is supposed to change as the discord bold, italics, and underline changes if you use the same *'s. but they do not on magma 
**Screenshots**
If applicable, add screenshots to help explain your problem:
What is supposed to happen:
![2020-09-07_20 57 02](https://user-images.githubusercontent.com/27363790/92422848-d9140d80-f14c-11ea-9080-3c9c8771267f.png)

What happens:
![2020-09-07_20 55 20](https://user-images.githubusercontent.com/27363790/92422840-c8fc2e00-f14c-11ea-8976-df9b3801350e.png)

What happens:
![2020-09-07_20 55 46](https://user-images.githubusercontent.com/27363790/92422856-e630fc80-f14c-11ea-951e-6abb67638528.png)

What is supposed to happen:
![2020-09-07_20 57 13](https://user-images.githubusercontent.com/27363790/92422876-fd6fea00-f14c-11ea-830e-c30300042987.png)

**Info (please complete the following information):**
- Mod Name: FTBUtils
 - Mod Version: 1.12.2
 - Magma Version: Latest as of 9/7/20
 - OS: Linux

**Additional context**
Add any other context about the problem here: I found that the nickname function seems to just use the getDisplayName() function from forge and just overrides it, and saves the nickname in the player's NBT data and loads it up upon log in. Im not sure if magma loads this function on loadup, i dont know much about magma. Thats about the extent of what i know about FTBU, hope that helps (I was unable to find how FTBU does the italics in chat).

**Comment by kwright02** [comment]
This has to do with the way that bukkit name handling works, please use a plugin like essentials for nick-names.
