### ISSUE TITLE
[Issue] Load times

### ISSUE THREAD

**Issue by YuiiiPTChan** [magmafoundation/Magma#244]
**Describe the issue**
Server randomly takes ages to start and sometimes just stalls. 

**To Reproduce**
1. I don't know if it's reproduce-able or its just how my setup is configured but it didn't take ages to load on the first time.

**Expected behavior**
A clear and concise description of what you expected to happen:
Normal load speed with mods and plugins was around 3 to 4 minutes, just like my other modded server.

**Screenshots**
https://prnt.sc/udrn9d - info on screenshot
https://prnt.sc/udro2d - info on screenshot

**Info (please complete the following information):**
 - Magma Version: Magma Dev HEAD-ade7751
 - OS: Ubuntu 18.04.5 LTS x86_64

**Additional context**
Add any other context about the problem here:

I started noticing the weird load times on discordsrv ( when it stops and the time it takes to load)

[latest.log] (Please upload your latest.log to https://mclo.gs and replace this text with the url)
Latest log that was able to log the server fully starting: https://mclo.gs/0REIxmF

**Comment by kwright02** [comment]
Please give your post a tittle

**Comment by YuiiiPTChan** [comment]
LOL sorry, firefox prob shit itself while opening it
