### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ghosty366** [magmafoundation/Magma#246]
**Describe the bug**
when my friend joined multiple times he got this

**To Reproduce**
have someone join the server with mods and plugins

**Expected behavior**
he should be able to join the server just fine

**Screenshots**
![Screenshot (51)](https://user-images.githubusercontent.com/32891973/92647828-2cea3800-f2ae-11ea-87d0-dd63bcf916e6.png)

**Info (please complete the following information):**
- Mod Name: i have multiple mods
 - Mod Version: i have  multiple mods
 - Magma Version: Magma-ade7751-server
 - OS: Windows 10

**Additional context**
no other context

**Comment by kwright02** [comment]
Please title your post and include a server log uploaded to https;//mclo.gs

**Comment by Ghosty366** [comment]
i think i found the problem now

**Comment by Ghosty366** [comment]
i found the problem, missed a mod
