### ISSUE TITLE
[BUG] crash server 1.12.2

### ISSUE THREAD

**Issue by BikiniClubRP** [magmafoundation/Magma#247]
**Describe the bug**
When the TNT explodes with a hanging plant, the server shuts down. The bottom block of the plant is the cause. It only happens in the server.

**Screenshots**
https://fotos.subefotos.com/e53e3eaebd7e5b64b0c963a26337bf45o.png

**Info:**
- Mod Name: **plant megapack**   http://www.9minecraft.net/plant-mega-pack-mod/
 - Mod Version:  1.12.2
 - Magma Version:  1.12.2 (happens in all previous released versions of 1.12.2)

**Comment by kwright02** [comment]
You _**MUST**_ include a log uploaded to https://mclo.gs
