### ISSUE TITLE
[BUG]  Unable to log-in using the LPX plugin

### ISSUE THREAD

**Issue by UknownGino** [magmafoundation/Magma#248]
**Describe the bug**
When i try to join my magma server with the plugin "LPX" (even without any mods installed on the server) it kicks me with the message "Unable to inject in your netty"

**To Reproduce**
1. Install LPX on the server (https://www.mc-market.org/resources/15709/)
2. Try to join the server

**Expected behavior**
Log into the server normally

**Additional infos**
Full Log: https://mclo.gs/lYzBJJn

**Info:**
 - Plugin Name: LPX (https://www.mc-market.org/resources/15709/)
 - Magma Version: HEAD-ade7751
 - OS: Ubuntu 16.04.1 LTS

**Comment by UeberallGebannt** [comment]
could you link the whole log using mclo.gs please?

**Comment by UknownGino** [comment]
> could you link the whole log using mclo.gs please?

here's to you: https://mclo.gs/lYzBJJn

**Comment by kwright02** [comment]
This is impossible to test because I do not own the plugin. Please re-open this if you have a copy that you're willing to use for testing.

**Comment by UknownGino** [comment]
> This is impossible to test because I do not own the plugin. Please re-open this if you have a copy that you're willing to use for testing.

I have a copy of it but I can't give it to you because the plugin license is linked to the machine's ip. If you tell me what to do to debug the plugin that i own, I will do.
