### ISSUE TITLE
[Issue] Plugin not loading when mods are installed

### ISSUE THREAD

**Issue by staridiot** [magmafoundation/Magma#249]
**Describe the issue**
A clear and concise description of what the bug is:
I've discovered installing [Skript](https://github.com/SkriptLang/Skript) and a mod that adds items/blocks will break the plugin. Running **mods** such as [WorldBorder](https://www.curseforge.com/minecraft/mc-mods/worldborder-forge) and [WorldEdit](https://www.curseforge.com/minecraft/mc-mods/worldedit) will work fine with Skript but mods such as [TerraFirmaCraft](https://github.com/TerraFirmaCraft/TerraFirmaCraft) or [IndustrialCraft2](https://wiki.industrial-craft.net/index.php?title=Main_Page) will break the plugin.

**To Reproduce**
Install Skript of any version above 2.3.2 and some mods, run `/skript`. If you get [this](https://i.imgur.com/jtm0znp.png), it broke.

**Expected behavior**
A clear and concise description of what you expected to happen:
Skript should load properly regardless of what mods are installed.

**Screenshots**
If applicable, add screenshots to help explain your problem:
Running a server with IndustrialCraft2 and Skript gave me [this](https://i.imgur.com/jtm0znp.png) when I ran `/skript reload`. However it gave me [this](https://imgur.com/a/qTumYLw) when I only loaded WorldGuard and WorldEdit - the mod editions.

**Info (please complete the following information):**
- Plugin Name: Skript
- Plugin Version: 2.3.2+
- Magma Version: Magma-ade7751-server.jar (latest at the time)
- OS: Ubuntu 20.04 LTS
- Java Version: 8u265

**Additional context**
Add any other context about the problem here:
I should also note I was running ProtocolLib as a plugin as well, however I was getting the same non-loading issue with Skript even without it.
[latest.log](https://mclo.gs/givCwxq)
[debug.log](https://mclo.gs/ORnfBbb)

**Comment by Amgelo563** [comment]
I believe latest version of Skript that works on hybrids is Skript 2.2dev36c or 2.2dev37c, try with those and see if it works out.

**Comment by staridiot** [comment]
> 
> 
> I believe latest version of Skript that works on hybrids is Skript 2.2dev36c or 2.2dev37c, try with those and see if it works out.

Version 2.2dev36c did indeed work with IndustrialCraft2. Has the developers of Skript removed it's ability to run with mods or is this still a Forge/Spigot integration issue?

**Comment by Amgelo563** [comment]
I believe it's something Skript included from that release that made it incompatible with Forge. According to a post I found:

> Skript versions 2.3+ will no longer work with mods due to how aliases work.

Alongside saying 2.2dev36 is the version you should use.

**Comment by staridiot** [comment]
> 
> 
> I believe it's something Skript included from that release that made it incompatible with Forge. According to a post I found:
> 
> > Skript versions 2.3+ will no longer work with mods due to how aliases work.
> 
> Alongside saying 2.2dev36 is the version you should use. But someone else mentioned on Magma's Discord that 2dev37c may work as well.

That's right 1.13 had the stupid change of removing item IDs caused a lot of plugins to quit. This makes more sense now, thanks.
