### ISSUE TITLE
[BUG]WorldEdit mod

### ISSUE THREAD

**Issue by mozomenku** [magmafoundation/Magma#250]
Hello, I have a problem with Essentials plugin and WorldEdit mod running on Magma server. Essentials override the /info command from, so I can't use it for WE and I don't know how to fix it as disabling it or overriding in Essentials config doesn't work. Somebody has an idea?

**Comment by kwright02** [comment]
This issue is being closed because you didn't follow the format. Follow the format or contact us on discord.
