### ISSUE TITLE
[BUG] no credits after killing the dragon.

### ISSUE THREAD

**Issue by CatChomusuke** [magmafoundation/Magma#254]
We create a portal in the end, kill the dragon, go to the portal and there are no titles after entering the portal.
also after exiting the END a portal to the Lower world appears and the player immediately teleports there
video:
https://www.youtube.com/watch?v=kMehKCiIq_A&feature=youtu.be

there is no difference with or without mods as well as plugins
 - Magma Version: Magma Dev HEAD-3a65e28
 - OS: win 10 pro

**Comment by kwright02** [comment]
I'm closing this ticket because you didn't follow the format. Please edit your ticket to follow the format and I will re-open it. Please ensure that you include a log from your server when you experience this issue.
