### ISSUE TITLE
[BUG] Crash with Simply Jetpacks 2 in Omnifactory 1.2.2

### ISSUE THREAD

**Issue by Irgendwer01** [magmafoundation/Magma#256]
**Describe the bug**
Crash with Simply Jetpacks 2 in Omnifactory 1.2.2

**To Reproduce**
1. start server
2. see error

**Expected behavior**
A clear and concise description of what you expected to happen:
working without issues
**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: Simply Jetpacks 2
 - Mod Version: 2.2.14.67
 - Magma Version: 12a54a3
 - OS: Ubuntu 18.04

**Additional context**
Add any other context about the problem here:
crash log: https://paste.ubuntu.com/p/3RcXFK2Kgs/

**Comment by kwright02** [comment]
I simply (hah) don't get the error you have, nor have I been able to replicate it, so i'm going to have to mark this as closed.

**Comment by Irgendwer01** [comment]
@kwright02 the Issue is when LibrarianLib and Simply Jetpacks 2 are together installed in a Forge + Bukkit Server Software, due to the Librarianlib dev won't will fix it i found a temporarily solution by adding -noverify in the JVM arguments to let Java ignore the error
