### ISSUE TITLE
[BUG] 100% one core load at idle (reopen)

### ISSUE THREAD

**Issue by KweezyPlay** [magmafoundation/Magma#258]
Hello, after 21 days of waiting this issue still is not fixed https://github.com/magmafoundation/Magma/issues/245 so i think i should reopen it
![image](https://user-images.githubusercontent.com/36813920/94920700-74d03980-04bf-11eb-8320-7b67e01d7806.png)

**Comment by KweezyPlay** [comment]
![image](https://user-images.githubusercontent.com/36813920/94920738-8580af80-04bf-11eb-8bfe-b548060bb601.png)
server is empty, nobody playing, no mods, no plugins, just downloaded

**Comment by Zilacon** [comment]
This issue is not fixed. I personally messaged you @kwright02 about this problem.

**Comment by KweezyPlay** [comment]
why you closed it :(
problem is here https://github.com/magmafoundation/Magma/commit/ade7751f92ba98bc68b5171cc84672a863c068ec
