### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Irgendwer01** [magmafoundation/Magma#265]
**Describe the bug**
Maybe an incompatibility with Mob Grinding Utils
**To Reproduce**
1. Start Server
2. See Crash
**Expected behavior**
Not an Crash with Mob Grinding Utils
**Info (please complete the following information):**
- Mod Name: Mob Grinding Utils
 - Mod Version: 0.3.13
 - Magma Version: 12a54a3
 - OS: Ubuntu 20.04
**Additional context**
Crash Log: https://paste.ubuntu.com/p/vhVn83fHkP/

**Comment by kwright02** [comment]
Please edit the name of your issue to include the name of the bug you have. IE Mob Grinding Utils bug or something like that so we know what it is
