### ISSUE TITLE
[BUG] Crash with Villager Trades

### ISSUE THREAD

**Issue by Irgendwer01** [magmafoundation/Magma#266]
**Describe the bug**
Maybe an Incompatibility with Villager Trades
**To Reproduce**
1. Start server with Villager Trades
2. See Crash
**Expected behavior**
Not an Crash with Villager Trades
**Info (please complete the following information):**
- Mod Name: Villager Trades
 - Mod Version: 0.6.4
 - Magma Version: 12a54a3
 - OS: Ubuntu 18.04
**Additional context**
crash log: https://paste.ubuntu.com/p/HKvbm99xR6/

**Comment by kwright02** [comment]
fixed, will be published in next release.
