### ISSUE TITLE
[BUG] Mystcraft is crashing server

### ISSUE THREAD

**Issue by remplerus** [magmafoundation/Magma#267]
**Describe the bug**
A clear and concise description of what the bug is:

Server is crashing when Mystcraft is installed.

**To Reproduce**
1. Put Mod in Mods Folder
2. Start server
3. Wait

**Expected behavior**
A clear and concise description of what you expected to happen:
Server not crashing

**Info (please complete the following information):**
- Mod Name: Mystcraft
 - Mod Version: 0.13.7.06
 - Magma Version: 12a54a3
 - OS: Windows 10

**Additional context**
Add any other context about the problem here:
Crashlog: https://mclo.gs/F3ZGRLY (same crashlog also here: https://hasteb.in/ajokoqim.swift )

**Comment by UeberallGebannt** [comment]
Mystcraft works with that release: https://github.com/magmafoundation/Magma/releases/tag/v40c88e5
Every release after that isnt working.
