### ISSUE TITLE
[BUG] Extra Alchemy mod is not working correctly

### ISSUE THREAD

**Issue by ArtifactyNight** [magmafoundation/Magma#268]
**Describe the bug**
look likes NBT is reset when I put in inventory
https://youtu.be/jMckHuWpwWI

**To Reproduce**
1. Download Mod Extra Alchemy & Minerva 
2. Drag some potion in that mod to inventory
3. See what happen

**Expected behavior**
A clear and concise description of what you expected to happen:
It's should be not reset potion material when I put it on inventory

**Screenshots**
If applicable, add screenshots to help explain your problem:
https://youtu.be/jMckHuWpwWI

**Info (please complete the following information):**
- Mod Name: **Extra Alchemy**
 - Mod Version: **build11-0.5.4.jar**
 - Magma Version: **e69a953**
 - OS: Window 10 Pro 2009

**Additional context**
Add any other context about the problem here:

Download Extra Alchemy: https://www.curseforge.com/minecraft/mc-mods/extra-alchemy/download/2937550
Download Minerva (Library of Extra Alchemy): https://www.curseforge.com/minecraft/mc-mods/minerva-library/download/2728693

**Comment by kwright02** [comment]
Can you try this on the latest version and see if it's still an issue?

**Comment by ArtifactyNight** [comment]
yes

**Comment by kwright02** [comment]
It appears the way the mod works it will not be compatible with Magma sadly.
