### ISSUE TITLE
First Aid [BUG]

### ISSUE THREAD

**Issue by superpurplegamer** [magmafoundation/Magma#269]
**Describe the bug**
When running rlcraft through magma people are indestructible. People say the cause for this is First Aid but I don't want to remove it. Is there anyway to fix this bug.

**To Reproduce**
1. Die

**Expected behavior**
Player To die

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: First Aid
 - Mod Version: 1.6.14
 - Magma Version: Latest

**Additional context**
Add any other context about the problem here:

**Comment by Hexeption** [comment]
#86
