### ISSUE TITLE
[BUG] Server won't start up

### ISSUE THREAD

**Issue by SoterDave** [magmafoundation/Magma#270]
**Describe the bug**
A clear and concise description of what the bug is: 
Basically, I cannot start up my Minecraft server. It crashed last night while one person was AFK farming, and I can't start it up since. Apex support told me it was a Java issue.

**To Reproduce**
All the mods on my server: https://drive.google.com/file/d/111qFj2wVHfNrwUGy5TWRIu7MpAdFqUsi/view?usp=sharing
We also have Clearlagg.

**Info (please complete the following information):**
- All the mods on my server: https://drive.google.com/file/d/111qFj2wVHfNrwUGy5TWRIu7MpAdFqUsi/view?usp=sharing
We also have Clearlagg.
 - Magma Version: 1.12.2

**Additional context**
Add any other context about the problem here: 
The server has been up for weeks, the issue just manifested today.

I can provide all information as needed.

**Comment by kwright02** [comment]
lol you didn't even provide a server log, we can't help you without one.

**Comment by kwright02** [comment]
Closing this because there's no information to go on.
