### ISSUE TITLE
[BUG] Advanced Fishing Mod

### ISSUE THREAD

**Issue by losmochos** [magmafoundation/Magma#271]
**Describe the bug**
When using the fishing rod the client throws an error, and you can't see the fishing float.

**To Reproduce**
1. Go to water
2. Put the rod
3. Use this.

**Expected behavior**
A normal use of the minecraft fishing system

**Info (please complete the following information):**
- Mod Name: Advanced Fishing
 - Mod Version: 1.3.3
 - Magma Version: Magma Dev HEAD-e69a953
 - OS: Microsoft Windows 10 [Version 10.0.19041.572]

**Comment by kwright02** [comment]
bruh, you didn't even include the error you get. Is this a joke?

**Comment by losmochos** [comment]
[crash-2020-10-27_22.22.56-client.txt](https://github.com/magmafoundation/Magma/files/5455325/crash-2020-10-27_22.22.56-client.txt)

**Comment by kwright02** [comment]
Couldn't replicate this issue on latest version.
