### ISSUE TITLE
[BUG] Players getting kicked from server when entering certain chunks. (EncoderException)

### ISSUE THREAD

**Issue by Zilacon** [magmafoundation/Magma#272]
**Describe the bug**
Players getting kicked when entering certain chunks.
Once they have that chunks position in their player data, they will always get kicked, until the Pos data is wiped from their player.dat file.

[08:11:01] [Server thread/INFO]: Hellcat_69420 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 4738893 into 3
[06:58:39] [Server thread/INFO]: Uhjoebilly lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 4738893 into 3
[15:42:06] [Server thread/INFO]: Sanjeevo lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: unable to fit 3550256 into 3

**To Reproduce**
Unknown how to reproduce, certain chunks on the server at random areas in the world just do this.
There is no stack traces, errors, or other information to determine the cause. Just their disconnect message.

**Expected behavior**
Obviously not to get kicked from the server lol.

**Info (please complete the following information):**
- Mod Name: Modpacks: Tekxit 3, 1.12.2 Pack, RL Craft, Sky Factory 4, and MC Eternal
 - Mod Version: Too many.
 - Magma Version: 153
 - OS: Linux Lubuntu 64 Bit

**Additional context**
This server is being used on a bungeecord.

**Comment by kwright02** [comment]
Honestly man, at this point I'm 99% sure you're custom bungeecord is corrupting connections

**Comment by kwright02** [comment]
Have you added or removed any mods? Did you restore any backups? Do you have and world-editing mods or plugins?

**Comment by Zilacon** [comment]
Ive added performance mods and patching mods. But these issues have been happening since last year, and most of these i wasnt using back then so i dont think they are the cause. Ill list them anyways.

EventHelper
Grimoire
Phosphor
AI Improvements
AI Reducer
Better FPS
Foam FIx
Performant
Random Patches
RL Tweaker
Born in a Barn
Chunk Gen Limiter
Fast Leaf Decay
Signal Catcher
Surge

Also my developer @Fox2Code says its not the bungeecord, if you could provide some information that links it to the bungeecord that would be much appreciated.

This issue can be reproduced on ALL public bungeecord forks, not just our custom one. Hexacord, Bungeecord, Travertine, Waterfall, all have this issue.

**Comment by kwright02** [comment]
Understandable, I was under the assumption that it was only happening on your bungecoord jar. We will dive into this soon

**Comment by kwright02** [comment]
Closing this as there isn't enough information to reveal anything significant. It's most likely some conflict with one or more of your performance/patching mods or tools
