### ISSUE TITLE
[BUG] Crash With Grinder From Mob Grindings Utils

### ISSUE THREAD

**Issue by MathisSkate** [magmafoundation/Magma#273]
**Describe the bug**
When a Grinder kill a mob the Server Crash

**To Reproduce**
1- Place a Grinder
2- Activate it
3- Kill a mob with it

**Expected behavior**
A clear and concise description of what you expected to happen:
Just kill the mob and don't crash

**Info (please complete the following information):**
- Mod Name: Mob Grindings Util
 - Mod Version: 0.3.13
 - Magma Version: Latest e69a953
 - OS: Linux

The Serveur Crash Report

https://pastebin.com/Trp1HZp8

**Comment by Ashley123477** [comment]
Also having this issue

**Comment by kwright02** [comment]
it seems the mob the grinder kills is being cast as a player and most mobs don't have the player functions. Working on fix

**Comment by kwright02** [comment]
I'm going to have hex look at this one
