### ISSUE TITLE
[BUG] Custom NPC Mod | Cant create NPC's with NPC Wand Item

### ISSUE THREAD

**Issue by DaDiGui** [magmafoundation/Magma#274]
**Describe the bug**
I can't create NPC with the NPC wand. Right button on the floor and neither the NPC nor the configuration menu appears, however, if I right click in the air with the tool, the list of NPCs opens, in short, I can use the other tools without problem

**To Reproduce**
1. Go to 'Run the server'
2. Click on 'Choose the NPC Wand'
3. Scroll down to 'Click on the ground to open/create the NPC menu'
4. Nothing happens even the consolo nothing to show up.

**Info (please complete the following information):**
- Mod Name: Custom NPC Mod
 - Mod Version: CustomNPCs_1.12.2-(01Oct19) and CustomNPCs_1.12.2-(05Jul20)
 - Magma Version: Magma-12a54a3-server
 - OS: W10

**Comment by kwright02** [comment]
fixed in latest test build, will be pushed in next release.
