### ISSUE TITLE
[BUG] magma 1.12.2 no credits after killing the dragon

### ISSUE THREAD

**Issue by CatChomusuke** [magmafoundation/Magma#275]
Аfter the release of their end there are no titles and instant creation of a portal to hell t teleportation there

step 1: go to the END
step 2: kill the dragon
step 3: go to the portal (no credits)
step 4: appear in Overworld in (above) the portal in the Nether
step 5: we are teleported to the Nether

After exiting end to see the credits and will appear on the spawnpoint

There is a video so it will be better to understand (https://youtu.be/v9k85Cq-y-E)
There is also a screenshot but it is not mine: 
![CvHXRoBh](https://user-images.githubusercontent.com/71904884/97618456-18b1f400-1a30-11eb-8bb8-49ff5abff925.jpg)
video of the screenshot owner (https://youtu.be/y8jgccPGVQw)

mods don't matter
- Magma Version: Magma-e69a953-server
- OS: windows 10 pro

**Comment by UeberallGebannt** [comment]
Please add a log using mclo.gs or hastebin

**Comment by CatChomusuke** [comment]
Latest.log (https://mclo.gs/EF57OEZ)
Debug.log(https://mclo.gs/L33GVWM)

**Comment by UeberallGebannt** [comment]
These logs dont show any errors, are you sure that are the ones from the screenshot?

**Comment by CatChomusuke** [comment]
Debug.log (https://mclo.gs/9JAuOwD)
Latest.log (https://mclo.gs/4XqFpkU)

**Comment by kwright02** [comment]
This is a known issue and will be taken care of when a fix is found
