### ISSUE TITLE
[Issue] Server Crash after update the new magma v.5db17b2

### ISSUE THREAD

**Issue by DaDiGui** [magmafoundation/Magma#278]
**Describe the issue**
`[14:07:01] [Server thread/ERROR] [FML]: The mod wumpleutil is expecting signature @FINGERPRINT@ for source wumpleutil-1.12.2-2.12.9.jar, however there is no signature matching that description

[14:07:01] [Server thread/WARN] [wumpleutil]: Invalid fingerprint detected! The file wumpleutil-1.12.2-2.12.9.jar may have been tampered with. This version will NOT be supported by the author!
--
821 | [14:07:01] [Server thread/WARN] [wumpleutil]: Expected fingerprint "@FINGERPRINT@" found "[]"```

`[14:07:01] [Server thread/ERROR] [FML]: The mod foodfunk is expecting signature @FINGERPRINT@ for source foodfunk-1.12.2-4.9.6.jar, however there is no signature matching that description

[14:07:01] [Server thread/WARN] [foodfunk]: Invalid fingerprint detected! The file foodfunk-1.12.2-4.9.6.jar may have been tampered with. This version will NOT be supported by the author!
--
845 | [14:07:01] [Server thread/WARN] [foodfunk]: Expected fingerprint "@FINGERPRINT@" found "[]"`

**To Reproduce**
1. Run.bat the server
2. Wait to load all the files
3. Server Crash

**Expected behavior**
Let the server load.

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: Foodfunk | Wumpleutil
 - Mod Version: 1.12.2-4.9.6 | 1.12.2-2.12.9
 - Magma Version: 5db17b2
 - OS: W10

**Additional context**
Add any other context about the problem here:

[latest.log] https://mclo.gs/ilr1VrM

**Comment by kwright02** [comment]
I believe your issue is located near the end of the log 
https://gyazo.com/83741f63d6737ebb0d57d7755ef1cae9
