### ISSUE TITLE
[BUG] Libary doesn't exist

### ISSUE THREAD

**Issue by UeberallGebannt** [magmafoundation/Magma#28]
**Describe the bug**
The libary "org.apache.commons.lang" doesn't exist in magma.

**To Reproduce**
1. Create a plugin using Magma.
2. Try to import org.apache.commons.lang,

**Expected behavior**
You should be able to import it.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50475262/69832316-e4392500-122d-11ea-817e-c14566d776c1.png)

**Info (please complete the following information):**
 - Magma Version: 09ac1b3

*This was reported to me by an external developer!*

**Comment by Hexeption** [comment]
We don't ship our jars with libraries shaded.

we will take a look into this at another time
