### ISSUE TITLE
[BUG] Go brush don't work :-(

### ISSUE THREAD

**Issue by SuperMax8** [magmafoundation/Magma#280]
**Note**
Please be gentle with my english I'm french student

**Describe the bug**
When I use go brush tool I have a "normal" /wea basic but my /wea is already activate + I have the region restriction false in my config.

**Screenshots**
![image](https://user-images.githubusercontent.com/73855070/97919032-63e14500-1d57-11eb-8f5b-7d023c1f1294.png)

**Info (please complete the following information):**
- Plugin Name: Go brush
 - Plugin Version: The last version for the 1.12
 - Magma Version: The last version

I realy love Magma and I realy love go brush I realy want harmony :) plz fix the bug for all terraformer !
(the plugin work with mohist your competitor but I stay with magma because is best)

**Comment by kwright02** [comment]
What plugin are you using that has region restrictions? Are you using like Towny, PlotSquared, or something similar?

**Comment by SuperMax8** [comment]
World Guard normaly but even with out worldguard and with just don't work
![image](https://user-images.githubusercontent.com/73855070/98691034-e5476180-236d-11eb-83bf-ba2bdfce4b20.png)

**Comment by SuperMax8** [comment]
Ah the plugin work if the 3D MOD is on but we can't use the flat mod
