### ISSUE TITLE
[BUG] Magma don't recognized Voice chat

### ISSUE THREAD

**Issue by SuperMax8** [magmafoundation/Magma#281]
**Describe the bug**
When I start magma with voicechat the server don't recognized the mod  : - (

**Screenshots**
![image](https://user-images.githubusercontent.com/73855070/97919523-347f0800-1d58-11eb-868e-c53d35181cd2.png)

**Info (please complete the following information):**
- Mod Name: Gliby's Voice Chat
 - Mod Version: The last in 1.12
 - Magma Version:  The last

**Additional context**
I make mmorpg in minecraft and I want a vocal in game ! Please fix God of the new cauldron

**Comment by UeberallGebannt** [comment]
Is this mod installed on the server?
If yes, are there any logs/errors?

**Comment by SuperMax8** [comment]
Have found ... Is just a idiot friend who add ChunkAnimator ... The worst mod for optimisation btw excuse me for the loss of time
But we have found something ChunkAnimator(the worst mod) + GlybisVoiceChat don't work

**Comment by kwright02** [comment]
Does the voice chat mod work without the ChunkAnimator?

**Comment by kwright02** [comment]
Fixed on latest version
