### ISSUE TITLE
[BUG] Fake player does not work in mods

### ISSUE THREAD

**Issue by perezzloy** [magmafoundation/Magma#282]
**Describe the bug**
I was faced with the fact that the fake player does not work correctly with Magma. I use fake players for mod compatibility with the WorldGuard plugin using the EventHelper. I found that on the mod side, everything works as expected, but Magma cannot handle the fake player on her side.

**To Reproduce**
It is difficult to describe. I used the debugger.

**Info (please complete the following information):**
- Mod Name: any mod with fake players
- Magma Version: 5db17b2
- OS: any

**Comment by joaoespanhol** [comment]
fake players, work here.
have to give them permission to login plugin

**Comment by perezzloy** [comment]
> fake players, work here.
> have to give them permission to login plugin

By default, they receive all the permits. In this case, all permissions are for a private region. But I did not give it to them.
In magma settings:
`fakeplayer:
  permissions: []`

**Comment by joaoespanhol** [comment]
no, i need write name fake player mod

**Comment by perezzloy** [comment]
I configured like this: 
```
fakeplayer:
  permissions:
  - '[Botania]'
```

But it doesn't work.

Perhaps Magma is not expecting some of the behavior that EventHelper provides.
There it is done like this: 
https://github.com/gamerforEA/EventHelper/blob/1.12.2/src/main/java/com/gamerforea/eventhelper/nexus/ModNexusFactory.java.

The mod uses an annotation with the name of the fake player, for example, like this:
```
@ModNexus(name = "Botania")
public final class ModUtils
{
	public static final ModNexusFactory NEXUS_FACTORY = NexusUtils.getFactory();
	private static final String ITEM_TAG_THROWER_CHECK_RES_ALLOW = "ItemThrowerCheckResAllow";
	private static final String ITEM_TAG_THROWER_CHECK_RES_DENY = "ItemThrowerCheckResDeny";

	public static boolean canThrowerInteract(@Nullable EntityItem entityItem, @Nonnull BlockPos pos)
	{
		if (entityItem == null)
			return false;

		Set<String> tags = entityItem.getTags();
		if (tags.contains(ITEM_TAG_THROWER_CHECK_RES_ALLOW))
			return true;
		if (tags.contains(ITEM_TAG_THROWER_CHECK_RES_DENY))
			return false;

		boolean result = canThrowerInteract0(entityItem, pos);
		if (result)
			entityItem.addTag(ITEM_TAG_THROWER_CHECK_RES_ALLOW);
		else
			entityItem.addTag(ITEM_TAG_THROWER_CHECK_RES_DENY);
		return result;
	}

	private static boolean canThrowerInteract0(@Nullable EntityItem entityItem, @Nonnull BlockPos pos)
	{
		if (entityItem == null)
			return false;

		String throwerName = entityItem.getThrower();
		if (Strings.isNullOrEmpty(throwerName))
			return !EventConfig.paranoidDropProtection;

		World world = entityItem.getEntityWorld();
		EntityPlayer player = world.getPlayerEntityByName(throwerName);
		if (player == null)
			return !EventConfig.paranoidDropProtection;

		return !EventUtils.cantInteract(player, EnumHand.MAIN_HAND, pos, EnumFacing.UP);
	}
}
```
The class object is initialized on the server side in preInit(). This is then used to get a fake player named [Botania].

![image](https://user-images.githubusercontent.com/8365261/98245539-20b6ea00-1f82-11eb-9888-d8020e7061f2.png)

**Comment by kwright02** [comment]
Fake players work fine. They all share the same permissions so the array in the magma.yml is the permission set.

**Comment by perezzloy** [comment]
You write that you need to add permissions. But I need to have no default permissions. And they are available. If I don't write anything there, then all the fake players still have full access as operators.

**Comment by joaoespanhol** [comment]
> You write that you need to add permissions. But I need to have no default permissions. And they are available. If I don't write anything there, then all the fake players still have full access as operators.

i have plguin worldguard.
I no have problem fakeplayer, you need give permission plugin login fake player

**Comment by joaoespanhol** [comment]
UnrestrictedName: ['[MonnuSDR]','[Mekanism]','[Buildcraft]','[Draconic_Evolutio]','[CoFH]','[IndustrialCraft]','[Forestry]','[MineFactory]','[extrautils2]','[ActuallyAdditions]']
      
Is permission my plugin login for fake player.

**Comment by SSKirillSS** [comment]
> i have plguin worldguard.
> I no have problem fakeplayer, you need give permission plugin login fake player

You should try to use EventHelper before asking something like this.
