### ISSUE TITLE
[BUG] Spigot Plugin | AdvancedTabOverlay 

### ISSUE THREAD

**Issue by DaDiGui** [magmafoundation/Magma#283]
**Describe the bug**
With this plugin installed you can't access any block/machine/anything coming from any mod and having to open the menu of that block with the right button, for example: 
-Create an NPC with CustomMODNpc
-Opening an IC2 machine

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen:

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Plugin Name: https://www.spigotmc.org/resources/advancedtaboverlay.78905/
 - Plugin Version: 1.2.2 & 1.3.0 SNAPSHOOT
 - Magma Version: Magma-5db17b2-server
 - OS: w10

**Additional context**
Add any other context about the problem here:

**Comment by joaoespanhol** [comment]
i no have problem my magma 1.12.2 last version.
Is problem plugin.

**Comment by kwright02** [comment]
You didn't fill out over half of the ticket format......
