### ISSUE TITLE
[BUG] Pixelmon Command Permissions

### ISSUE THREAD

**Issue by NovaPixell** [magmafoundation/Magma#285]
**Describe the issue**
Normal users, not ops in the server, are unable to execute mod commands. These have the right permissions on luckperms

**Info (please complete the following information):**
- Mod Name: PixelmonGenerations
 - Magma Version: Lates
 - OS: Ubuntu 18

Permissions Nodes: https://pastebin.com/Ss9zM2Zb

**Comment by Rasgnarok** [comment]
What version of Magma are you using, and what version of Luckperms?

**Comment by NovaPixell** [comment]
both are latest

**Comment by NovaPixell** [comment]
this is the commit they made on mohist to fix the problem.

https://github.com/Mohist-Community/Mohist/commit/ac8c93d5997d370b45e76e5adf8300faab4dc630

**Comment by Rasgnarok** [comment]
Latest is not a version number, please precise. I am going to try and reproduce your problem, but I need version numbers.

**Comment by joaoespanhol** [comment]
there is no problem with pixelmon at the command level, the default group is not allowed.
Closed ticket, is no problem magma

**Comment by NovaPixell** [comment]
I'm telling you it's your problem, I had it with mohist and I had it solved. instead of believing that I'm a moron, check the magma code well thanks
