### ISSUE TITLE
[BUG] RedProtect Error in Console

### ISSUE THREAD

**Issue by NovaPixell** [magmafoundation/Magma#286]
Logs of the Error in chat: https://pastebin.com/k7wwCG9v

**Comment by joaoespanhol** [comment]
i no have is problem my server.
call me discord for send plugin: Jony Bravo#3124

**Comment by NovaPixell** [comment]
what? whait

**Comment by joaoespanhol** [comment]
https://discord.com/channels/612695539729039411/612695539729039417/773653563473526846
