### ISSUE TITLE
[BUG] Pixelmon NPCWand cannot spawn certain NPCs

### ISSUE THREAD

**Issue by Rasgnarok** [magmafoundation/Magma#288]
**Describe the bug**
A clear and concise description of what the bug is: Pixelmon's NPC wand is used to spawn NPCs. At the moment, the Move Relearner, Trader and the Move Tutor do not spawn.

**To Reproduce**
1. Load up Magma with Pixelmon 8.1.2.
2. In creative, use the NPC wand, right-click. 
3. Select 'Move Relearner'. It should attempt to spawn it at the cursor's location.

**Expected behavior**
A clear and concise description of what you expected to happen: The NPC wand should create a Pixelmon non-despawnable Move Relearner NPC at the cursor location. This does not happen, it spawns nothing.

**Info (please complete the following information):**
- Mod Name: Pixelmon Reforged
 - Mod Version:  Pixelmon 8.1.2
 - Magma Version: 5db17b2-server
 - OS: N/A

**Additional context**
Add any other context about the problem here:
- Could be related to https://github.com/magmafoundation/Magma/issues/153 , though we've not managed yet to reproduce the general despawning. 
- All NPCs created by the wand should be immune to automatic despawning. Only wild-spawned NPCs should despawn.

**Comment by Rasgnarok** [comment]
Update, confirming that this is related to https://github.com/magmafoundation/Magma/issues/153 . NPCs in the ticket linked are failing to load from save data, which is in and of itself failing to spawn. NPCWand is failing to spawn, same bug.

**Comment by Rasgnarok** [comment]
https://github.com/magmafoundation/Magma/blob/master/patches/net/minecraft/entity/EntityLiving.java.patch#L90

**Comment by Rasgnarok** [comment]
stacktrace for reference, func_70692_ba = canDespawn
```
at net.minecraft.network.datasync.EntityDataManager.func_187225_a(EntityDataManager.java:151) ~[nb.class:?]
        at com.pixelmonmod.pixelmon.entities.npcs.EntityNPC.getAIMode(EntityNPC.java:929) ~[EntityNPC.class:8.1.2]
        at com.pixelmonmod.pixelmon.entities.npcs.NPCRelearner.func_70692_ba(NPCRelearner.java:227)

**Comment by Rasgnarok** [comment]
༺Phil༻10/16/2020
https://pastebin.pl/view/b05ad240
error when trying to spawn Mover relearner or tutor.. pls can someone help me

Magma 1.12.2 

Pixelmon-1.12.2-8.1.2-universal

ModList:
BiomesOPlenty-1.12.2-7.0.1.2444-universal
Gameshark-1.12.2-6.0.4-universal
jei_1.12.2-4.16.1.301
journeymap-1.12.2-5.7.1
LegendaryPlus-6.0
MouseTweaks-2.10-mc1.12.2
NaturesCompass-1.12.2-1.8.5
PixelExtras-1.12.2-2.5.10-universal
Pixelmon-1.12.2-8.1.2-universal
PlaceholderAPI-4.0

https://i.gyazo.com/93aa0d33a4b5a95d8375ee6e98f62c85.png

OS? I am on windows 10.. Idk what os is

**Comment by kwright02** [comment]
fixed on test build, will be pushed in next release.
