### ISSUE TITLE
[BUG] The shop closing itself

### ISSUE THREAD

**Issue by Kennar** [magmafoundation/Magma#29]
After entering the command /shop, the store closes itself

https://youtu.be/0z1FH7r7qf8

 - Plugin Name: ShopGUI+
 - Plugin Version: 1.21.1
 - Magma Version: 09ac1b3-server

**Comment by Hexeption** [comment]
This is a paid plugin how am i meant to debug this?

**Comment by Kennar** [comment]
All I can do is send you the plugin myself, I don't know if it will help

**Comment by Hexeption** [comment]
Sure dm me

**Comment by Kennar** [comment]
Send here or on discord on pv?
