### ISSUE TITLE
[BUG] Command block doesn't execute mods commands

### ISSUE THREAD

**Issue by perezzloy** [magmafoundation/Magma#291]
**Describe the bug**
Command block doesn't execute mods commands. Tested on many mods. Only vanilla commands are executed.

**To Reproduce**
Try to execute any command of any mod in the command block.

**Info:**
 - Mod Name: all
 - Magma Version: 5db17b2
 - OS: any

**Comment by kwright02** [comment]
Do you get an error in the console?

**Comment by perezzloy** [comment]
No. Empty, as if the command block does not see the command.
