### ISSUE TITLE
[Issue] Server Crash 

### ISSUE THREAD

**Issue by NovaPixell** [magmafoundation/Magma#294]
**Describe the issue**
My server has crashed in the night with this error. https://mclo.gs/Op0VBwQ
it seems related to liquid blocks or something similar

**To Reproduce**
At the moment i don't know how.

**Info (please complete the following information):**
 - Magma Version: 1.12.2 bdf8d6d
 - OS:  Ubuntu 18.04

**Comment by kwright02** [comment]
You likely have the wrong version of that mod installed because it's trying to access something in the net.minecraft.World class that it can't find

**Comment by NovaPixell** [comment]
What mod?

**Comment by UeberallGebannt** [comment]
We can't really say that, you can list all mods and we can try to figure it out.

**Comment by NovaPixell** [comment]
[crash-2020-11-16_23.00.43-server.txt](https://github.com/magmafoundation/Magma/files/5553906/crash-2020-11-16_23.00.43-server.txt)
Hi, another server crash

**Comment by kwright02** [comment]
If this is a separate issue please open a different ticket. From what I can see in the above crash report you have a pixelmon issue
