### ISSUE TITLE
[BUG] astralsorcery

### ISSUE THREAD

**Issue by joaoespanhol** [magmafoundation/Magma#295]
**Describe the bug**
this console errors appear when players are playing.

**Screenshots**
![image](https://user-images.githubusercontent.com/22871432/98710704-ed0e0280-237b-11eb-90e8-81d54b03f878.png)

Log-laster: https://mclo.gs/cddzFUg

**Info (please complete the following information):**
- Mod Name: astralsorcery
 - Mod Version:  1.12.2 (AstralSorcery-1.12.2-1.10.27.jar)
 - Magma Version: bdf8d6d 
 - OS: Linux

**Comment by kwright02** [comment]
Do you have the FirstAid mod installed?

**Comment by joaoespanhol** [comment]
> Do you have the FirstAid mod installed?

nope.
because?

**Comment by kwright02** [comment]
It's an incompatible mod, and it relates to Entity Damage and things. Please share your log file by uploading it's content to a pastebin: https://pastebin.com

**Comment by joaoespanhol** [comment]
> It's an incompatible mod, and it relates to Entity Damage and things. Please share your log file by uploading it's content to a pastebin: https://pastebin.com

https://mclo.gs/vCDMUVh

**Comment by kwright02** [comment]
outdated log, closing
