### ISSUE TITLE
[Issue] Docker MAGMA crash on start

### ISSUE THREAD

**Issue by Acenia0** [magmafoundation/Magma#296]
im using itzg minecraft server and have set the type to magma but for some reason it dosent wanna work, also using a custom jar file didnt work either, i set the type to custom and changed the filename but it still didnt want to work.

Here is some more information.
its a synology nas and im trying to run magma through docker but it crashes on start here is the logs, https://mclo.gs/68F9LFn

is there something i have done wrong? or is the issue not on my end, would like to get help with this since i have tried myself for hours now and havent been able to get it to work.

**Comment by kwright02** [comment]
Please re submit your log in a pastebin
