### ISSUE TITLE
Cant leave mystcraft dimensions[BUG]

### ISSUE THREAD

**Issue by lazr58** [magmafoundation/Magma#297]
**Describe the bug**
When trying to use linking books in mystcraft to get out of a dimension, you get teleported to the same dimension with those coordinates. 

**To Reproduce**
1. Go to a mystcraft dimension
2. Use a linking book to try to leave
3. Get teleported to the same dimension, with the coordinates it shouldve teleported you back to the overworld

**Expected behavior**
Mystcraft linking books teleporting me out of the dimension

**Info**
- Mod Name:Mystcraft
 - Mod Version: 1.12.2-0.13.7.06
 - Magma Version: Any 1.12.2
 - OS:Ubuntu Server

**Additional context**
The terminal it will say onPlayerChangedDimension brings me to the overworld, even though you are still in the same dimension.

**Comment by Xiantrius** [comment]
Stop @lazr58 
It is also not possible if I go over vanilla, for example. End portal try to teleport.
That is not shown in the log which is strange, but with a mod it is shown like Mystcraft. Nevertheless, neither is possible.

**Comment by kwright02** [comment]
@lazr58 Please try again on the newest version and re open this issue if it still doesn't work

**Comment by lazr58** [comment]
Im still experiencing the same issue, I will reopen
