### ISSUE TITLE
[Feature] Paper Inquiry + Context

### ISSUE THREAD

**Issue by Segmentational** [magmafoundation/Magma#298]
**Describe the feature**
Beta implementation of `Paper` feature(s) -- e.g. the `paper` **branch**.

**Reason why this feature should exist**
*N/A* - It's more so a **Request**.

**Screenshots**
*N/A*

**Note**
I'm willing to do so (that is resolve an issue or two & make a merge request)* myself, but I suppose I'm looking for more context. Specifically, is the `paper` branch ready to also be in beta? If not, why? If the issues are associated with current merge conflicts, cool -- I can fork and resolve them. Otherwise if I can get a **List** of the current issues associated with `paper`, we (myself and ~ 4 other developers) can fork and attempt applicable fixes. 

Thank you to those involved with the project!

**Comment by Segmentational** [comment]
@kwright02, hello hello. Could we include anyone who'd be able to further discuss with? I'm just looking for some additional information on paper and what's going on with the branch before I begin a fork.

**Comment by kwright02** [comment]
@Segmentational Hex is the only one that was working on it so I'm not sure of its current state. But I know that it broke quite a few things when he merged it over.
