### ISSUE TITLE
[Issue] Updating Documentation & Creating "-Installer" Issue

### ISSUE THREAD

**Issue by Segmentational** [magmafoundation/Magma#299]
**Documentation** - `README.md`
- [ ] `README.md` -- Update the section that states "*(Do not use the "-installer" version as it is broken right now)*" to include reference to the specific issue(s), or remove it if the CICD is already a sufficient solution. 
- [ ] Create an issue related to the above point if one doesn't already (I couldn't find one) and if still applicable. Please note I'm also willing to contribute to the specific issue if one has to be created, but I would request context from those aware of the issue.

**Comment by kwright02** [comment]
In forge 1.12.2 the installer jar is broken for some unknown reason
