### ISSUE TITLE
End dimension does not load[BUG]

### ISSUE THREAD

**Issue by liampearson96** [magmafoundation/Magma#300]
**Describe the bug**
A clear and concise description of what the bug is:
The end dimension is not created when Magma is installed, if the end is created before magma is installed, once magma is loaded it will not allow you to teleport to the end. Nor will you be able to use the end portal. Tested without Magma and can go to the end just fine

**To Reproduce**
1. make/find end portal
2. jump in
3. no teleportation commences

**Expected behavior**
A clear and concise description of what you expected to happen:
The player should be sent to the end dimension

**Info (please complete the following information):**
 - Tested Magma Versions: Magma-bdf8d6d-server.jar , Magma-32d1d93-server.jar 
 - OS: Linux

**Comment by Xiantrius** [comment]
Me to problem End Dimension.
In Nether i can Teleport.
Is Unload problem Dimension 1 and -1 
without unload is all ok

**Comment by liampearson96** [comment]
@Xiantrius how have you made it so it doesn’t unload?

**Comment by Xiantrius** [comment]
> 
> 
> @Xiantrius how have you made it so it doesn’t unload?

With old Magma-40c88e5-server.jar i can all Dimension teleport, with new version i not can in End Dimension from Vanilla End-Portal and from Mods how Mystcraft.
I not know why this so broken Codes. I not understand why other code, how old better function with Dimension Teleport.

**Comment by liampearson96** [comment]
@Xiantrius Yeah your version doesn't work for me either.

**Comment by Xiantrius** [comment]
sooo @liampearson96 
u must in config Magma.yml and all unload dimension delete.

exemple:

  autoUnloadDimensions:
  - '0'
  - '1'
  - '-1'

to

  autoUnloadDimensions:

**Comment by kwright02** [comment]
Fixed in latest version.
