### ISSUE TITLE
Server crashes, issue with OTG

### ISSUE THREAD

**Issue by crossfirearena** [magmafoundation/Magma#303]
**Describe the bug**
Server crashes shortly after start, OTG seems to be the issue. Problem exists on Mohist as well.
https://hastebin.com/teweyanuse.rb

**To Reproduce**
Start with fresh server, crashes on start, every time, tried several new installs. 

**Screenshots**
https://imgur.com/a/OfGdcfk

**Info (please complete the following information):**
- Mod Name: OTG looks to be the cause
 - Mod Version: V9.0 (Cant change)
 - Magma Version:  Newest - Dev HEAD-50f320e
 - OS: Linux - Ubuntu 18.04.3 LTS

**Comment by crossfirearena** [comment]
Tried removing unloader, server still crashes. Still signifies problem with OTG

**Comment by 0H4rl3qu1n0** [comment]
OTG has always been a total shitshow with compatibility

**Comment by crossfirearena** [comment]
> OTG has always been a total shitshow with compatibility

I 100% agree, I think there are better options out there. I wanted to remove it completely, but it doesnt allow the user to connect to the server at all. Server boots and is stable though

**Comment by kwright02** [comment]
OTG is not supported by Magma
