### ISSUE TITLE
[BUG] [FML]: Parsing error loading recipe 

### ISSUE THREAD

**Issue by joaoespanhol** [magmafoundation/Magma#304]
Flood console error:
when you disable the mod configuration item, magma does not recognize correctly.
Being that it leaves the server a floodar error.
With another server forge it doesn't happen
https://mclo.gs/i7xXUec

 - Magma Version:  Magma-50f320e-server.jar
 - OS: linux

**Comment by kwright02** [comment]
Please reupload your log

**Comment by kwright02** [comment]
normal part of forge.
