### ISSUE TITLE
[Bug]/[Issue]Advancement Issues 

### ISSUE THREAD

**Issue by Plasman888** [magmafoundation/Magma#305]
**Describe the issue**
Advancements repeat as shown in the gif
also occurs on mohist(probably a mod which i have yet to identify)
the advancements json file prevent the server from bein started again unless deleted

**To Reproduce**
1. Use (the mod)
2.Run the server and log in a player
3. Stop the server
4. Try to start again

**Expected behavior**
Just starts normally the subsequent times

 - Magma Version: Magma-50f320e
 - OS:windows

[First run log]https://mclo.gs/5wa5Rzw
[Subsequent logs](https://github.com/magmafoundation/Magma/files/5612016/Subsequent.logs.log)
![Minecraft-1122-2020-11-30-08-58](https://user-images.githubusercontent.com/71266194/100690337-412b6600-33c1-11eb-95f2-5d12095fb4de.gif)

**Comment by Plasman888** [comment]
Update it happens whenever I make a change; either removing/adding or plugin or mod etc. then i have to delete the world and make a new one

**Comment by kwright02** [comment]
Mod list, Plugin list, and log please.

**Comment by Plasman888** [comment]
Well I have too many mods so I'm trying to troubleshoot to find out which mod is causing the problem and it's definitely not a plugin cause I removed all and I did put the logs

**Comment by kwright02** [comment]
This is caused by whatever gravestone mod you have.
