### ISSUE TITLE
[BUG] faf2949 broke crafting

### ISSUE THREAD

**Issue by Company-Captain** [magmafoundation/Magma#309]
**Describe the bug**
Some items can't be crafted in faf2949. All works fine on magma 50f320e.

**To Reproduce**
1. Run a server on a curseforge modpack Poetica
2. Try to craft dough

**Screenshots**
50f320e (works fine):
![50f320e](https://user-images.githubusercontent.com/34135160/100756670-8326cd00-33fe-11eb-84c9-e343dc288e11.gif)

faf2949 (broken):
![faf2949](https://user-images.githubusercontent.com/34135160/100756722-90dc5280-33fe-11eb-8550-92f3475f71b8.gif)

**Info:**
- Mod Name: TerraFirmaCraft (could be a CraftTweaker issue, no idea tbh)
 - Mod Version: 1.12.2-1.0.12.141
 - Magma Version: faf2949
 - OS: Ubuntu

**Comment by kwright02** [comment]
Identified as a craft-tweaker issue.
