### ISSUE TITLE
[BUG] TokenManager error

### ISSUE THREAD

**Issue by Kennar** [magmafoundation/Magma#31]
We have a plugin that is responsible for the premium currency on each server, connected to the MYSQL database, we have a problem on magma that after entering /token the following message appears: https://imgur.com/6tO5zdH
Server logs are the same as on any server where this plugin is located, on other servers the number of tokens normally appears.
Log: https://hastebin.com/ayabudurud.md

 - Plugin Name: TokenManager
 - Plugin Version: 3.2.4
 - Magma Version: d55bb16-server

**Comment by kingdevnl** [comment]
Do there show up any errors in the console when executing the command?

**Comment by Kennar** [comment]
No errors whatsoever

**Comment by Kennar** [comment]
I don't know if this is due to this authorization error I sent some time ago.

**Comment by Hexeption** [comment]
This is working in the latest version.
