### ISSUE TITLE
[BUG]Ticking entity

### ISSUE THREAD

**Issue by martin1194** [magmafoundation/Magma#310]
after the player shot some arrow somewhere and ran into a portal(The Twilight Forest). The arrow will make a bug and let the game crash.
I hope Manga will fix this bug too.

 - Magma Version: Magma-50f320e-server
 - OS: window 10

This crash log is from Magma
[crash-2020-12-05_13.38.27-server.txt](https://github.com/magmafoundation/Magma/files/5647306/crash-2020-12-05_13.38.27-server.txt)

Sponge will fix this bug. I hope Manga have this function too
`[18:17:58] [Server thread/WARN] [Sponge]: EntityTFNagaSegment['unknown'/2134, l='DIM7', x=-272.04, y=33.69, z=43.34] is not in chunk (-17, 2) and is instead in chunk (-18, 2) within world DIM7, skipping save. This is a bug fix to a vanilla bug. Do not report this to Sponge or Forge please.`

**Comment by kwright02** [comment]
This is a vanilla bug and this is also edge case behavior. This is not going to be fixed by us.
