### ISSUE TITLE
[Feature] EssentialsX not support forge mod item ID

### ISSUE THREAD

**Issue by martin1194** [magmafoundation/Magma#311]
EssentialsX said they will not do anything about this problem. That why I report the problem here.

https://github.com/EssentialsX/Essentials/issues/3814

"I run my Magma server and use EssentialsX. I can't use give command to get any forge mod item. I really sure item ID is right. I hope it can be fix and i can add something in blacklist."

**Describe the feature**
A clear and concise description of what the feature is:

**Reason why this feature should exist**

**Screenshots**
If applicable, add screenshots to help explain your feature:

**Comment by kwright02** [comment]
This isn't an issue with magma or essentials. In order to get modded items in essentials you have to populate the essentials items.csv. We are working on a feature to implement this automatically.

**Comment by UknownGino** [comment]
I've actually created a plugin that auto-populates the EssentialsX's items.csv file. You can find it here https://github.com/UknownGino/ModdedIntegration
