### ISSUE TITLE
[BUG] skull will destory by hand without any mod/plugin

### ISSUE THREAD

**Issue by martin1194** [magmafoundation/Magma#316]
- Mod Name:  N/A
 - Mod Version:  N/A
 - Magma Version:  9e0b1b1 
 - OS: WINDOWS 10
video link : https://www.youtube.com/watch?v=mNZilUG63t4&feature=youtu.be

Skull of monther will destory when the server haven't any mod and plugin.
minecraft version: 1.12.2
![image](https://user-images.githubusercontent.com/18354205/102016790-04d70d00-3da6-11eb-91bf-e1d9aa47fbe4.png)
![image](https://user-images.githubusercontent.com/18354205/102016792-07d1fd80-3da6-11eb-89df-16fcf49ba61a.png)

**Comment by kwright02** [comment]
Will be fixed in the next PR
