### ISSUE TITLE
[BUG] Mod failed to find Forge class

### ISSUE THREAD

**Issue by KorewaLidesu** [magmafoundation/Magma#318]
**Describe the bug**
ProjectE can't find class if GTCE installed

**To Reproduce**
Start server with GTCE and ProjectE 

**Expected behavior**
GTCE should be able to patch the code while ProjectE able to find out that class

[**Logs**](https://mclo.gs/N5x8oIB)

**Info (please complete the following information):**
- Mod Name: 
 > GregTech Community Edition (1.12.2-1.10.0.546)
 > ProjectE (1.12.2-PE1.4.1)
- Magma Version: 9e0b1b1
- OS: Window 7 Pack 1

**Additional context**
> Caused by: java.lang.RuntimeException: Patching failed, patch code wasn't injected Patch target: [net/minecraftforge/common/ISpecialArmor$ArmorProperties.applyArmor(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/util/NonNullList;Lnet/minecraft/util/DamageSource;D)F]; injection point: [net/minecraft/util/CombatRules.func_189427_a(FFF)F]; (point not found)

**Comment by kwright02** [comment]
This is a GTCE issue, not a Magma issue.
