### ISSUE TITLE
[BUG]Essentials

### ISSUE THREAD

**Issue by joaoespanhol** [magmafoundation/Magma#323]
**Describe the bug**

Error version plugin Essentials v2.18.1.0
https://mclo.gs/16A6QIk
https://mclo.gs/mv9RfUl
Error new version Essentialsx-2.19.0
https://cdn.discordapp.com/attachments/612695539729039417/785826870196699146/unknown.png

 - Magma Version: last
 - OS: linux

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
This issue is known. An announcement will be made when essentials support is fixed.
