### ISSUE TITLE
[BUG]when typing command "ebalancetop" will throw out "java.util.ConcurrentModificationException"

### ISSUE THREAD

**Issue by martin1194** [magmafoundation/Magma#325]
Magma: HEAD-9e0b1b1
MC: 1.12.2
OS: WIN10

The server will crash when issue command "ebalancetop"
 

[crash-2020-12-19_08.17.11-server.txt](https://github.com/magmafoundation/Magma/files/5719369/crash-2020-12-19_08.17.11-server.txt)

[2020-12-19-2.log.zip](https://github.com/magmafoundation/Magma/files/5719368/2020-12-19-2.log.zip)

**Comment by kwright02** [comment]
I was unable to replicate this issue on the latest version.
