### ISSUE TITLE
[Issue] Missing Chat Component Classes

### ISSUE THREAD

**Issue by XZot1K** [magmafoundation/Magma#326]
After reviewing the source and comparing, most plugins 1.12 and above are now utilizing the `player.spigot().sendMessage()` method variations to handle JSON messaging. The class found in the bukkit packages [here](https://github.com/magmafoundation/Magma/blob/master/src/main/java/org/bukkit/entity/Player.java) in Magma includes these variations and options; however, the project seems to be missing all component API methods from the ComponentBuilder which is actually is built-in to SpigotAPI. In addition, Spigot uses the BungeeCord patch found [here](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/browse/Bukkit-Patches/0013-BungeeCord-Chat-API.patch) to implement the reset of the API. To make things more globally compatible, please consider implementing this patch to resolve issues. Returning most of all our plugins to direct packets to handle JSON (which changes every version since 1.13 now) can result in unethically slow update times for other developers. To further support my claims, HEX support (1.16) was added to md_5's ChatColor found in the BungeeCordAPI patch as well. This currently is the only profitable way to implement and utilize HEX without jumping through several hoops. Again this is all just something I hope is considered to help bring everything to a may streamline resolution.

**Comment by kwright02** [comment]
I urge you to retry this because I just manually went through that patch file and we have all of the code in it :)
