### ISSUE TITLE
[BUG] Fake Player Can't Spawn Wither

### ISSUE THREAD

**Issue by Star1a** [magmafoundation/Magma#333]
**Describe the bug**
A clear and concise description of what the bug is: Fake player can't Spawn Wither

**To Reproduce**
1. Open up modpack- power up a wither builder
2. Simply input resources and it'll build wither
3. Wither won't spawn
4. No errors anywhere in console

**Expected behavior**
A clear and concise description of what you expected to happen: Normally as soon as it builds the wither it would spawn. If you put extra resources it would spawn more than one too. Something is stopping it from doing so, although if a regular player does it it works fine.

**Screenshots**
If applicable, add screenshots to help explain your problem:
https://gfycat.com/sparsebrightfiddlercrab  (a short video)
**Info (please complete the following information):**
- Mod Name:  Industrial Foregoing (Part of FTB Revelations modpack)
 - Mod Version: 1.12.2 (Specifically for Industrial Foregoing 1.12.13)
 - Magma Version: 1656508
 - OS: Windows

**Additional context**
Add any other context about the problem here:
I had a discord ticket for this issue open and we attempted a plugin to fix it but it didn't work.

**Comment by kwright02** [comment]
please edit your title to contain: 'Fake player can't Spawn Wither'
