### ISSUE TITLE
[BUG]ExentialX It gives error when executing commands.

### ISSUE THREAD

**Issue by diaverso** [magmafoundation/Magma#335]
**Describe the bug**
A clear and concise description of what the bug is:
I have the permissions set with luckperms, but when I run the tpa command it gives an error.

**To Reproduce**
We write the command / tpa and the name of the person and it gives us an error.

**Expected behavior**
A clear and concise description of what you expected to happen:

**Screenshots**
https://i.imgur.com/gYfirXf.gif

**Info (please complete the following information):**
- Mod Name: BOP-Patch-1.0,Gameshark-1.12.2-6.0.4-universal,PixelExtras-1.12.2-2.5.10-universal,Pixelmon-1.12.2-8.1.2-universal
 - Mod Version: 
 - Magma Version: Magma-46f4149-server
 - OS: Windows server 2019

**Additional context**
latest: https://gist.github.com/diaverso/40304c69c54c0487b364f8ce21822f8f

**Comment by kwright02** [comment]
This is a known issue, an announcement will be made when its fixed
