### ISSUE TITLE
[BUG] Magma problems and crashes update (even after making a new server)

### ISSUE THREAD

**Issue by RealMugman** [magmafoundation/Magma#336]
**Describe the bug**

I'm having a problem after the Magma 1.12.2 auto update with EssentialsX, EssentialsXChat, PlaceholderAPI, MOTD that were working before and I can't also make ForgeEssentials work as a replacement for Essentials, and it crashes every time I reload a plugin.

**To Reproduce**

Reloading any plugin is enough to trigger the crash.

**Expected behavior**

It crashes whenever I reload any plugin. It also does this with and without mods and/or other plugins.

**Screenshots**

![image](https://user-images.githubusercontent.com/69798658/103445491-ec576580-4c74-11eb-8396-a9dbf681ca46.png)

In this last one I only had clearlagg for example, and it still crashed after reloading the plugin.

**Info:**
- Mod Name: -
 - Mod Version: -
 - Magma Version: 4a8d6af
 - OS: Windows 10

**Additional context**

The crash error's pastebin

https://pastebin.com/Sg0btfHW

**Comment by reconsolidate** [comment]
same issue as me =(

**Comment by kwright02** [comment]
The latest magma version contains v2 timings which broke a ton of stuff. Please wait for a patch to be released, and if the issue continues to happen re open this ticket.
