### ISSUE TITLE
[BUG] ServerSigns Plugin not working

### ISSUE THREAD

**Issue by Qumoo** [magmafoundation/Magma#337]
**Describe the bug**
A clear and concise description of what the bug is:
When trying to create a ServerSign with e.g. "/svs add say hello" it says "Right-click the sign to bind the command to it" when right-clicking the sign nothing happens. No Error in the console, no feedback ingame and it the sign doesn't work.

**To Reproduce**
1. Go to https://dev.bukkit.org/projects/serversigns download a ServerSign Version and install it on your Magma-Server'
2. When ingame try using "/svs add say hello" 
3. Right click the sign
4. See that nothing happens.

**Expected behavior**
A clear and concise description of what you expected to happen:
After using the command "/svs add say hello" and right clicking the sign it should say "The command was added successfully". And right-clicking the sign should have the desired effect that the command "say hello" gets executed by the player clicking it.

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Plugin Name: ServerSigns
 - Plugin Version: 4.6.2
 - Magma Version: 4a8d6af (latest as of now 01.01.2021 23:51) and 73b26b7
 - OS: Windows 10 64bit with 6GB RAM allocated to the server

**Additional context**
Add any other context about the problem here:
Tried the same ServerSigns version on a spigot server and it works without problems.

**Comment by Qumoo** [comment]
This is also affected by my other ticket https://github.com/magmafoundation/Magma/issues/338.

ServerSign does work in Magma Build 5bff736.

**Comment by kwright02** [comment]
There is a known issue with the current latest magma version that has broken many plugins. Please wait for a patch to be released and then revisit this issue. If your issue persists after the patch has been released, please re-comment here.
