### ISSUE TITLE
[BUG]Not Compatible with AW2 and CodeChickenlib

### ISSUE THREAD

**Issue by Thorin48** [magmafoundation/Magma#339]
**Not Compatible with AW2 and CodeChickenlib **
A clear and concise description of what the bug is:
Magma seems to not support AW2 and CodeChickenLib

**To Reproduce**
1.) https://www.curseforge.com/minecraft/mc-mods/ancient-warfare-2/download/2766432 and https://www.curseforge.com/minecraft/mc-mods/codechicken-lib-1-8/download/2779848 here's the download for the mods
2) Put both in mod folder
Have the latest Magma version as the server jar.
3) Try to start up server.

**Expected behavior**
A clear and concise description of what you expected to happen: Run the server instead kicked this error https://pastebin.com/E2TMg4H2

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: ancientwarfare-1.12.2-2.7.0.772  CodeChickenLib-1.12.2-3.2.3.358-universal
 - Mod Version: 1.12.2
 - Magma Version: 4a8d6af
 - OS: Linix/Windows

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
Please note that the latest magma version has created many errors which are going to be patched by Hex soon. Please re open this ticket if the issue persists after that update is released.
