### ISSUE TITLE
[Feature] Support for forge mod permissions

### ISSUE THREAD

**Issue by blacksythe** [magmafoundation/Magma#343]
**Describe the feature**
Support for forge mods permissions to be passed to permissions plugins like Luckperms

See https://www.curseforge.com/minecraft/mc-mods/forge-to-bukkit-permissions
Support is somewhat limited though and a lot of commands feel unsupported
I feel that this should be more backend than an additional mod

Sponge also allows this feature but unfortunately this seems to be missing in hybrid software

**Reason why this feature should exist**
Cross compatibility is part of the reason software like magma exists, extending support to allow Luckperms and similar mods control permissions for mods as well as plugins should also exist

Thanks in advance for your superb work.

**Comment by Hexeption** [comment]
This is already a thing
