### ISSUE TITLE
[Issue]Unable to launch Magma server

### ISSUE THREAD

**Issue by MasterIMLG** [magmafoundation/Magma#344]
**Describe the issue**
While installed forge 14.23.5.2855, the server just can be launched and always prints that "We appear to be missing one or more essential library files." It just wont work with libraries of forge2855, where should I go get those missing libraries?

**To Reproduce**
Launch the server as README.md said.

**Expected behavior**
The server should be launched and auto-downloading the missing libraries.

**Screenshots**
No screenshots

**Info (please complete the following information):**
- Mod Name: No mods
 - Mod Version:  Null
 - Magma Version: Magma Dev HEAD-a4bc0a5
 - OS: Windows 10

**Additional context**
Add any other context about the problem here:

[https://paste.ubuntu.com/p/qzTSwhkMyj/] (Please upload your latest.log to https://mclo.gs and replace this text with the url)

**Comment by KorewaLidesu** [comment]
I dont think you need to install Forge
Just run the -server and you good

**Comment by UeberallGebannt** [comment]
@MasterIMLG Please redownload the newest version and try again

**Comment by Xplodin** [comment]
getting the same error
![image](https://user-images.githubusercontent.com/13007677/108178090-0a1c4500-70d2-11eb-8e12-86b9016e50dc.png)

**Comment by UeberallGebannt** [comment]
> getting the same error
> ![image](https://user-images.githubusercontent.com/13007677/108178090-0a1c4500-70d2-11eb-8e12-86b9016e50dc.png)

Dont use the installer, download the server jar directly
