### ISSUE TITLE
[Issue] Crash with MovingWorld

### ISSUE THREAD

**Issue by SlimefrogSocial** [magmafoundation/Magma#346]
**Describe the bug**
A clear and concise description of what the bug is:
Server crashed when adding Magma
I duplicated my server then added magma to it. The server crashes when running with magma but runs fine without. 
I have been using sponge, but it sucks so I removed it. I am very excited to find a replacement with actual support.

**To Reproduce**
1. Download all the mods, particularly MovingWorld
2. Run server
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen:
I hoped that the server would work and just boot up and run.
**Screenshots**
If applicable, add screenshots to help explain your problem:
N/A
**Info (please complete the following information):**
- Mod Name: MovingWorld
 - Mod Version: movingworld-1.12-6.353-full.jar
 - Magma Version: Magma-bb50f45-server.jar
 - OS: Windows 10

**Additional context**
Add any other context about the problem here:
[modlist.txt](https://github.com/magmafoundation/Magma/files/5761910/modlist.txt)
[crash-2021-01-03_11.48.50-server.txt](https://github.com/magmafoundation/Magma/files/5761911/crash-2021-01-03_11.48.50-server.txt)
[latest.log](https://github.com/magmafoundation/Magma/files/5761913/latest.log)

Pastebin Versions:
https://pastebin.com/eautWUZk
https://pastebin.com/g2Tpw1Ac
Latest.log is too big for pastebin, let me know if you need me to post it another way!

**Comment by kwright02** [comment]
There is no bug here, so please edit your title to this: '[Issue] Crash with MovingWorld'

**Comment by kwright02** [comment]
Also, if you have anything sponge leftover you have to remove it. All Sponge Plugins Any Sponge Mods including spongeforge

**Comment by SlimefrogSocial** [comment]
I believe I have done that so I'll have to check again

**Comment by SlimefrogSocial** [comment]
It seems I have removed all plugins and such from the server, I do believe that this issue may be similar to #44

**Comment by kwright02** [comment]
Your moving world config isn't properly setup, try fixing that.

**Comment by SlimefrogSocial** [comment]
Deleted the config folder, still crashes. I don't believe I edited that config.

**Comment by kwright02** [comment]
Can you verify that it's the _same_ crash?

**Comment by SlimefrogSocial** [comment]
Crash for after config removed:

[crash-2021-01-03_19.36.59-server.txt](https://github.com/magmafoundation/Magma/files/5762533/crash-2021-01-03_19.36.59-server.txt)
When I put a period in front of movingworld jar it has this crash:
[crash-2021-01-03_16.44.52-server.txt](https://github.com/magmafoundation/Magma/files/5762534/crash-2021-01-03_16.44.52-server.txt)
Usually with strange crashes like this I try moving around the load order but you can't exactly do that with Magma

**Comment by SlimefrogSocial** [comment]
Just checking in, I was very busy this last Sunday but I should be able to troubleshoot the rest of the week.

**Comment by SlimefrogSocial** [comment]
Hey I'm back and wanted to bring this back up, could we work through this soon?

**Comment by SlimefrogSocial** [comment]
I will make a duplicate of the entire server and remove moving world and try to find if moving world is only issue,
