### ISSUE TITLE
Draconic Shield[BUG]

### ISSUE THREAD

**Issue by DangerMage** [magmafoundation/Magma#348]
**Describe the bug**
https://youtu.be/nWTWbSIgNw0
The bug is that when a player is hit by a melee attack the shield blocks damage but not the damage tick, Note that it does block projectiles.

**To Reproduce**
1. Have full draconic (or probably wyvern armor works too)
2. Hit the person who has full armor with a melee attack, or get hit by one.
3. you should take a damage tick but still take no damage with some energy loss in the shield

**Expected behavior**
A clear and concise description of what you expected to happen:
The shield takes a bit of energy loss but you take no damage nor damage tick.

**Screenshots**
If applicable, add screenshots to help explain your problem:
I have a video: https://youtu.be/nWTWbSIgNw0

**Info (please complete the following information):**
- Mod Name: Draconic Evolution
 - Mod Version:  2.3.27.353
 - Magma Version: bb50f45
 - OS: ubuntu

**Additional context**
Add any other context about the problem here:
Projectiles are blocked without damage tick like expected.

**Comment by DangerMage** [comment]
Note melee damage from mobs also is blocked
same with creeper explosions

**Comment by UeberallGebannt** [comment]
Could you test additional damage sources like lava, fireballs, fire, ...

**Comment by DangerMage** [comment]
> 
> 
> Could you test additional damage sources like lava, fireballs, fire, ...

All of the above work as expected, This armor makes it so you can walk through fire and swim in lava without even damaging the shield at all, walking on magma blocks also works as expected with this armor.

**Comment by DangerMage** [comment]
Hey sorry, i know people are busy but i'm just wondering if there is any update on this? Just a little tired of taking knockback.

**Comment by UeberallGebannt** [comment]
Since you dont get any damage this is most likely going to be a low priority bug, i can try to make a small plugin that completly prevents you from taking damage as a temporary fix

could you send me the name of the item that you need in order to take no damage?

**Comment by DangerMage** [comment]
> 
> 
> Since you dont get any damage this is most likely going to be a low priority bug, i can try to make a small plugin that completly prevents you from taking damage as a temporary fix
> 
> could you send me the name of the item that you need in order to take no damage?

Draconic armor, Thing is it still drains the shield and you only take the tick from it, so you take knockback as though you have no armor but you still don't take damage, so it works, it's just more annoying when people punch me.

**Comment by UeberallGebannt** [comment]
I just tested it, it works as intended for me.
![grafik](https://user-images.githubusercontent.com/50475262/104046174-f67ee400-51df-11eb-9529-40627a47d9d0.png)

**Comment by DangerMage** [comment]
> 
> 
> I just tested it, it works as intended for me.
> ![grafik](https://user-images.githubusercontent.com/50475262/104046174-f67ee400-51df-11eb-9529-40627a47d9d0.png)

Odd, for us when we are hit by a player it gives us a damage tick and knockback

**Comment by UeberallGebannt** [comment]
Are you using the latest version or Magma and Draconic Evolution?

**Comment by DangerMage** [comment]
![image](https://user-images.githubusercontent.com/57050396/104092807-928e0700-5243-11eb-9ecd-d9d586b8aad6.png)

This is the magma we are using (not sure why there are 2) 

Draconic evolution is upto date as well (just checked curse forge real quick and we are using the latest)

**Comment by KorewaLidesu** [comment]
> This is the magma we are using (not sure why there are 2)
Oh, Petrodactyl.
Is "-dau" on your java augment?

**Comment by DangerMage** [comment]
> 
> 
> > This is the magma we are using (not sure why there are 2)
> 
> Oh, Petrodactyl.
> Is auto update disabled?

Magma's auto update or petrodactyl's auto update?

**Comment by KorewaLidesu** [comment]
There is a option in Petrodactyl that change server file that the panel will pick.
Make sure it is the latest one.

**Comment by DangerMage** [comment]
> 
> 
> There is a option in Petrodactyl that change server file that the panel will pick.
> Make sure it is the latest one.

Alright, Il have to contact the owner of the server and have him do that.

**Comment by DangerMage** [comment]
> 
> 
> There is a option in Petrodactyl that change server file that the panel will pick.
> Make sure it is the latest one.

![image](https://user-images.githubusercontent.com/57050396/104093945-13043600-524b-11eb-8892-2b4db5476732.png)
Owner just says this, I am now confused.

**Comment by DangerMage** [comment]
> 
> 
> There is a option in Petrodactyl that change server file that the panel will pick.
> Make sure it is the latest one.

![image](https://user-images.githubusercontent.com/57050396/104096097-a9d6ef80-5257-11eb-9f1e-3707c851deb2.png)
Is this right?

**Comment by kwright02** [comment]
Yes

**Comment by UeberallGebannt** [comment]
So all the files are updated?
Does it work now?

**Comment by DangerMage** [comment]
> 
> 
> So all the files are updated?
> Does it work now?

They were that version to begin with so i never had any updates, still doesn't work.
