### ISSUE TITLE
[BUG] Crash when right clicking

### ISSUE THREAD

**Issue by MrWhiteFlamesYT** [magmafoundation/Magma#352]
**Describe the bug**
When placing a fire pit down and right clicking it with mutton in [SevTech: Ages of the sky](https://www.curseforge.com/minecraft/modpacks/sevtech-ages-of-the-sky) it crashes the server.

**Expected behavior**
[part latest.log](https://mcpaste.io/9aa41afd6e46c662)
[crash report](https://mcpaste.io/b1c2bdd04751c7bc)

**Screenshots**
[plugins](https://prnt.sc/wk8ctg)

**Info (please complete the following information):**
- Modpack Name: [SevTech: Ages of the Sky](https://www.curseforge.com/minecraft/modpacks/sevtech-ages-of-the-sky)
 - Mod Version: [SevTech: Ages of the Sky 3.2.1 Beta 1](https://www.curseforge.com/minecraft/modpacks/sevtech-ages-of-the-sky/files/3123513)
 - Magma Version: bb50f45
 - OS: GNU/Linux 10 (buster)

**Additional context**
Full Latest.log : https://gist.github.com/MrWhiteFlamesYT/3e6e998daf6bf3961483a90ade09c3f8

**Comment by kwright02** [comment]
Seems to be an issue with progression tweaks

**Comment by MrWhiteFlamesYT** [comment]
ok so it is modpack fault?
