### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by Xenfo** [magmafoundation/Magma#357]
**Describe the issue**
A clear and concise description of what the bug is: Magma server crashes immediately.

**To Reproduce**
1. Download Magma
2. Run it with java -Xmx6144M -Xms2048M -jar magma-server.jar nogui
4. See error/issue: https://pastebin.com/7s3jAxVK

**Expected behavior**
A clear and concise description of what you expected to happen: Magma to start like usual

**Screenshots**
If applicable, add screenshots to help explain your problem: 
![image](https://user-images.githubusercontent.com/46873232/105346690-f4d7f780-5bb3-11eb-9616-0852453124e0.png)

**Info (please complete the following information):**
- Mod Name: RLCraft
 - Mod Version: 2.8.2
 - Magma Version: bb50f45
 - OS: Ubuntu Server x64 for Raspberry Pi

**Additional context**
Add any other context about the problem here: Working yesterday

[latest.log] No log as server doesn't start

**Comment by Xenfo** [comment]
Remade the server with new files and it fixed itself

**Comment by Creeperz653** [comment]
ok?
