### ISSUE TITLE
[BUG] BlockBreakEvent totally ignores #setDropItems

### ISSUE THREAD

**Issue by mfnalex** [magmafoundation/Magma#360]
**Describe the bug**
Setting BlockBreakEvent#setDropItems to false still drops the items

**To Reproduce**
Use this inside some registered listener:
```java
    @EventHandler
    public void onBlockBreakTest(BlockBreakEvent event) {
        event.getPlayer().sendMessage("DEBUG: setting BlockBreakEvent#setDropItems to false");
        event.setDropItems(false);
    }
```
And then break any block
**Expected behavior**
The broken block should not drop anything, but it does.

**Info (please complete the following information):**
 - Magma Version: 537f1d6

The message gets printed correctly and there are no console errors.
Plugin compiled against latest Spigot 1.16.5 API

**Comment by Zilacon** [comment]
I experienced this problem with the Drop2Inventory plugin. It basically duplicates every block you break and place.
It also creates ghost blocks, if you mine a sand or gravel block with other blocks above it, the falling blocks vanish on your screen.
But they still exist on the server, you'd have to re-login to see them.

**Comment by Cazcez** [comment]
Just tried with an "empty" Spigot plugin that does nothing but using the above listener, and I can confirm it does not work on latest Magma while it works perfectly on Paper and Spigot

**Comment by mfnalex** [comment]
> I experienced this problem with the Drop2Inventory plugin. It basically duplicates every block you break and place.
> It also creates ghost blocks, if you mine a sand or gravel block with other blocks above it, the falling blocks vanish on your screen.
> But they still exist on the server, you'd have to re-login to see them.

Just to mention: I am the author of Drop2Inventory and the duplication happens because of the mentioned "BlockBreakEvent#setDropItems" is ignored.

The ghost block stuff has nothing to do with the issue I mentioned here^^

**Comment by kwright02** [comment]
You compiled it with 1.16 spigot, try using 1.12 spigot

**Comment by mfnalex** [comment]
So you don't support ANY plugins compiled against 1.16? Most people HAVE to use a 1.13+ API if they want to maintain a 1.12 and a 1.13+ version

**Comment by UeberallGebannt** [comment]
> 
> 
> So you don't support ANY plugins compiled against 1.16? Most people HAVE to use a 1.13+ API if they want to maintain a 1.12 and a 1.13+ version

nope, this would have been a test, but the issue got resolved so it should work now

**Comment by mfnalex** [comment]
I don't really understand how it makes a difference whether it's compiled against 1.12 or 1.16. but did I understand correctly that with current Magma versions, it should?

**Comment by UeberallGebannt** [comment]
It was just an idea about what Could have caused this issue. But it wasnt the right idea, it doesnt habe anything to do with that.
Your issue is fixed in the latest version.

**Comment by mfnalex** [comment]
Thanks!
