### ISSUE TITLE
[BUG]No data value

### ISSUE THREAD

**Issue by rocogamer** [magmafoundation/Magma#370]
**Describe the bug**
No data value
https://pastebin.com/zj0nWNk0

**To Reproduce**
1. Create an island
2. Put modded block
3. See error

**Info (please complete the following information):**
- Plugin Name: Iridium Skyblock
 - Plugin Version: 2.1.6
 - Magma Version: b2a81d7
 - OS: Debian

**Comment by kwright02** [comment]
The issue is unclear here. Please provide more detail
