### ISSUE TITLE
[BUG] World Border not visible, and a lot of lag of "WorldSave" in Timings

### ISSUE THREAD

**Issue by NovaPixell** [magmafoundation/Magma#372]
**Describe the bug**
the border set with the "WorldBorder" plugin is not visible. I also encounter this problem in another server running a plugin that goes to control the border. But evidently Magma has some incompatibilities.

**To Reproduce**
1. Set a WorldBorder

**Screenshots**
If applicable, add screenshots to help explain your problem:
![2021-02-14_19 02 52](https://user-images.githubusercontent.com/55632135/107884815-4182ca00-6ef7-11eb-9e0f-3b8d1f91b4d9.png)

**Info (please complete the following information):**
 - Magma Version: 8999645 Version (latest)
 - OS: ubuntu 18

**Comment by UeberallGebannt** [comment]
The WorldBorder plugin doesnt have a visible border.

**Comment by NovaPixell** [comment]
Mhh I don't think so. I use this plugin on 1.16.5 version and it is visible

**Comment by UeberallGebannt** [comment]
Maybe its different on 1.16, but on 1.12 there isnt a visible world border made by the plugin, the vanilla one is visible but not the pluign one

**Comment by NovaPixell** [comment]
Ok so, I'm using a Battle Royale plugin. Why on a spigot server the border is visible and on magma not? Please can we fix it? I really need it

**Comment by UeberallGebannt** [comment]
Are we talking about the worldborder from vanilla or the worldborder created by the plugin?
These are not the same.

**Comment by NovaPixell** [comment]
no no, created by plugin

**Comment by UeberallGebannt** [comment]
Ok, which plugin are you using?

**Comment by NovaPixell** [comment]
This plugin: https://www.spigotmc.org/resources/lastminerstanding-battle-royale-lastmanstanding.48445/

**Comment by UeberallGebannt** [comment]
Ok, and why did you say "the border set with the "WorldBorder" plugin is not visible."?

Or is this independent from each other?

**Comment by NovaPixell** [comment]
This plugin is compatible with magma, features as Item give and lootboxes are working. Only the border is the problem. he told me it's a magma related problem

**Comment by NovaPixell** [comment]
> Ok, and why did you say "the border set with the "WorldBorder" plugin is not visible."?
> 
> Or is this independent from each other?

actually this LMS plugin doesn't need any dependencies like WorldBorder. It was to see if the problem was fixed with the latter, but apparently it's the same. So the same problem applies to the Battle Royale plugin

**Comment by NovaPixell** [comment]
so?

**Comment by NovaPixell** [comment]
it is really important, put some urgency thanks

**Comment by NovaPixell** [comment]
On a normal Spigot server it works without problems
So is a Magma problem. maybe some API(?) related to the worldborder that was modified on magma, instead of a normal spigot server

**Comment by kwright02** [comment]
I can’t reproduce your issue on any magma version. Best of luck.

**Comment by NovaPixell** [comment]
I have talked with a Discord mod and we are solving :)

**Comment by NovaPixell** [comment]
To try, you should have the Battle Royale plugin that I refer to. So I would like to understand what test you have done.
