### ISSUE TITLE
[BUG] Problem to End portal

### ISSUE THREAD

**Issue by MrAfitol** [magmafoundation/Magma#379]
**Describe the bug**
When I go to the End Portal and kill the dragon, I jump to the end portal, after I appeared in the ordinary world, a portal to hell appears in me and I teleport to hell

**To Reproduce**
1. Go to End
2. killing the dragon
3. entered the portal to the exit
4. after appearing in the ordinary world, a portal to hell appears in me

**Video**
Video with a problem: [Click](https://youtu.be/juUMGVvSerA)

**Info (please complete the following information):**
 - Magma Version: b2a81d7, 8999645
 - OS: Win 10

**Comment by tabr** [comment]
The same as https://github.com/magmafoundation/Magma/issues/378
