### ISSUE TITLE
Modded server crashes with recurrent foundations

### ISSUE THREAD

**Issue by CaidenKehrer** [magmafoundation/Magma#381]
**Describe the bug**
A clear and concise description of what the bug is:
Magma server crashes with recurrentFoundations
**To Reproduce**
1. Install recurrent foundations
2. Try to log in

**Expected behavior**
A clear and concise description of what you expected to happen:
It shouldnt crash.

Crashlog:
https://pastebin.com/Nf6AcEbq

**Info (please complete the following information):**
- Mod Name: Recurrent Foundations
 - Mod Version: 1.4.8.1
 - Magma Version: 1.12.2 latest
 - OS:linux

**Comment by Irgendwer01** [comment]
@CaidenKehrer Can u please make an Paste that never expires that everyone can help with the problem?

**Comment by kwright02** [comment]
Closing for lack of response
