### ISSUE TITLE
[Issue] Unable to create a Magma server, console shuts down.

### ISSUE THREAD

**Issue by VirtualBear** [magmafoundation/Magma#385]
**Describe the issue**
A clear and concise description of what the bug is: The console would for some reason won't run the server to load the EULA and other files saying that there was a problem launching the latest version of Magma. (there's not much I can tell as that's mostly all)

**To Reproduce**
1. Download the RLCraft 1.12.2 Server Pack (2.8.2)
2. Download Magma (version 045a413)
3. Open the RLCraft server pack and extract to another file (right click > extract files)
4. Drop in the Magma file.
5. Create a new text document and type the code (code I used is down below)
6. Save as run.bat and all files.
7. Click on 'run.bat'
8. See error/issue

**Expected behavior**
A clear and concise description of what you expected to happen: The server should have loaded the EULA and other following documents that are required to run the server

**Screenshots**
If applicable, add screenshots to help explain your problem:

![image](https://user-images.githubusercontent.com/79763788/109396479-626e0500-7964-11eb-9fad-14666d65c291.png)

**Info (please complete the following information):**
 - Mod Name: RLCraft
 - Mod Version: 2.8.2
 - Magma Version: HEAD-045a413
 - OS: Windows 10 (64-Bit)

**Additional context**
Add any other context about the problem here:

The code that I used for run.bat is 

java -jar Magma.jar nogui

PAUSE

(There are no other plugins, just the RLCraft modpack)

[latest.log] https://mclo.gs/mtBKFTC

**Comment by Doc94** [comment]
looks like a permission error.

**Comment by BobbyBear1** [comment]
Is there anyway to solve or stop the problem? I've tried everything possible. this even happens without using RLCraft and just making a normal server also doesn't work. I checked my AntiVirus logs to see if there was anything blocked but nothing?

**Comment by TheAwesome98-Real** [comment]
Make sure the libraries.zip archive has the same permissions you're running the server with (usually your user, not sudo).

**Comment by tabr** [comment]
Use TAKEOWN windows command:
TAKEOWN /f "PATH_TO_MC_FOLDER" /r /d y

**Comment by kwright02** [comment]
Update please

**Comment by VirtualBear** [comment]
I used the TAKEOWN command, but it said that the system cannot find the file specified.

No other message but that one.

**Comment by tabr** [comment]
> I used the TAKEOWN command, but it said that the system cannot find the file specified.
> (I did delete the server files after they 'don't work, does this affect this?)

The problem is: you don't know how works your operation system.
You cat use next suggestions:
1) Check free space
2) Extract your server pack
3) TAKEOWN /f "PATH_TO_MC_FOLDER" /r /d y (maybe as admin)
But better would be if you ask help you somebody who knows how to work with your OS.

**Comment by VirtualBear** [comment]
![Capture1](https://user-images.githubusercontent.com/79763788/112661178-d084e980-8e88-11eb-8058-85e3772cd64f.PNG)

**Comment by VirtualBear** [comment]
One question, does it work if you manually install the libraries into the server itself?

**Comment by TheAwesome98-Real** [comment]
> ![Capture1](https://user-images.githubusercontent.com/79763788/112661178-d084e980-8e88-11eb-8058-85e3772cd64f.PNG)
> 
> I ran this as an administrator, and I did extract my server pack

You haven’t specified the folder, you’ve just copied as is.

**Comment by VirtualBear** [comment]
Ok, the library error is gone. But now it won't load the EULA or server.properties

**Comment by VirtualBear** [comment]
O.K, I took control of the files and the library error is gone, I have the EULA and server properties but the plugins folder isn't there, the server properties haven't fully loaded and every time I run it, it just says that it failed to find the newest version and then quits.

**Comment by TheAwesome98-Real** [comment]
> O.K, I took control of the files and the library error is gone, I have the EULA and server properties but the plugins folder isn't there, the server properties haven't fully loaded and every time I run it, it just says that it failed to find the newest version and then quits.
> 
> EDIT: **I started the server by pressing the minecraft_server.1.12.2.jar file, server.properties fully loaded, but the plugins folder didn't load.** Using run.bat for some reason doesn't work. (run.bat is the file I'm using to load Magma.)

what's the error the run.sh displays?

**Comment by kwright02** [comment]
You need to watch an install guide on youtube. You clearly don't understand how to use your computer, nor how to install Magma.

**Comment by TheAwesome98-Real** [comment]
> You need to watch an install guide on youtube. You clearly don't understand how to use your computer, nor how to install Magma.

I don’t think they should use a install tutorial, I think they need a using computer tutorial
