### ISSUE TITLE
[BUG]? "no main manifest attribute"

### ISSUE THREAD

**Issue by Reithsaw** [magmafoundation/Magma#39]
**no main manifest attribute**
When i want to start my server in 1.14.4 i have this message " no main manifest attribute "

**To Reproduce**
1. Go to 'The folder where the server as be placed'
2. Click on 'start.bat'

**Screenshots**
![cmd](https://user-images.githubusercontent.com/51093339/70518900-659c8b80-1b3b-11ea-858f-338a6353ccec.PNG)
![start](https://user-images.githubusercontent.com/51093339/70518901-659c8b80-1b3b-11ea-8842-5673f7ffe4ba.PNG)

**Info (please complete the following information):**
- Mod Name: None
 - Mod Version: None
 - Magma Version: magma-unknown.offset-1.14-full.jar
 - OS: Win10 x64

**Comment by Hexeption** [comment]
Magma 1.14 is not ready or out yet
