### ISSUE TITLE
Items with custom tooltips are reverting to regular versions [BUG]

### ISSUE THREAD

**Issue by MomoPewpew** [magmafoundation/Magma#390]
**Describe the bug**
When you give yourself an item with custom display data, it will revert back to normal state when you move it in your inventory. 

**To Reproduce**
Step 1: Give yourself a wool block with a custom name, such as
/give @p wool 1 0 {display:{Name:"Test Name"}}
Step 2: Pick up the wool block in your inventory and drag it to a different slot
The name will now revert to White Wool.

**Expected behavior**
We would expect it to retain its custom display data

**Screenshots**
If applicable, add screenshots to help explain your problem:
https://i.imgur.com/ACbdvwg.jpg
https://i.imgur.com/19uxHYZ.jpeg
https://media1.tenor.com/images/45acd6f53f2b4486ef941a7f52e79c8e/tenor.gif?itemid=20581317

**Info (please complete the following information):**
- Mod Name: None
 - Mod Version: None
 - Magma Version: 1bc8635.
 - OS: Windows.

**Additional context**
I first noticed this bug on january 27th. I have seen it happen with wool, mushrooms, cobblestone and stairs.

This still happens on a fresh server that is running nothing but Magma. It also removes the tooltips from menu inventories such as the ones used in CMI.

**Comment by MomoPewpew** [comment]
Update: This problem arose at either build 1656508 or build 46f4149.

I cannot confirm which of the two builds it is because 1656508  crashes my server. I just know that the build before it (81f47df) did not have the issue

**Comment by kwright02** [comment]
Will investigate this

**Comment by UeberallGebannt** [comment]
This build should fix the NBT error regarding the erasing of NBT data.
Please not that this version is **VERY EXPERIMENTAL**.
Use it for testing only and make a backup if you want to use it on your server.

Don't forget to disable the updater by adding `-dau` at the end of the start script

https://cdn.discordapp.com/attachments/764999121819533352/870375272095051796/Magma-cda8df2-CUSTOM-server.jar
