### ISSUE TITLE
[BUG] Whole Ticket From discord

### ISSUE THREAD

**Issue by MrWhiteFlamesYT** [magmafoundation/Magma#392]
All the info you need is added as an attachment, i allready did fill this in on the discord ticket so i am just forwarding that ticket as an html file.
[Magma Development Limited - 🎟 ┇ Tickets 1.12_ - version-issue [802537485917093898].zip](https://github.com/magmafoundation/Magma/files/6091428/Magma.Development.Limited.-.Tickets.1.12_.-.version-issue.802537485917093898.zip)
Had to zip it cause github does not support the format. This is also a full extract of the full ticket i have on discord.

**Comment by UeberallGebannt** [comment]
Please follow the format, it is much easier to solve then

**Comment by MrWhiteFlamesYT** [comment]
Wow lazy to read that .html file, dude it way harder to do it in the format if it is a ticket open in the discord that was asked to be moved over with all the info in that ticket already so try and read the file then you might understand and the thing is the details is in that html file at the very top so if you brought 
> 
> 
> Please follow the format, it is much easier to solve then
>
> 
Means you have not open the html file at all.

**Comment by kwright02** [comment]
Some of us don’t have constant pc access and can’t unzip it. For ours, and your convenience, please follow the format
