### ISSUE TITLE
[BUG] Clients other then forge cannot connect to a magma server via bungeecord.

### ISSUE THREAD

**Issue by refractored** [magmafoundation/Magma#393]
**Describe the bug**
A clear and concise description of what the bug is:
Clients other then forge cannot connect to the server.

**To Reproduce**
1. Join a magma server through bungeecord with a client without forge.

**Expected behavior**
A clear and concise description of what you expected to happen:
All clients to be able to connect.

**Info (please complete the following information):**
 - Magma Version: 045a413
 - OS: Linux

**Additional context**
Add any other context about the problem here:
1. I have only serverside mods. (The issue persists after removing all mods, and plugins)
2. A forge client with 0 mods connects to the server fine.
3. Logs of the player disconnecting. https://pastebin.com/jHmDqK4K
4. May be related to #380
5. Using Hexacord with forge support enabled

**Comment by kwright02** [comment]
This is intended, you can only connect to magma with forge
