### ISSUE TITLE
[BUG] Death bug with mods

### ISSUE THREAD

**Issue by MathisSkate** [magmafoundation/Magma#394]
**Describe the bug**
When someone dead in my server he lose perms with group manager, the /give not works with, when he reconnect or change world that fix that !

The bug is fix whithout any mods but plugins.

**To Reproduce**
1. Take my mods and plugins , (i try with just my mods, essentials and group manager, and without mods)
2. Die
3. The bug is produced

**Expected behavior**
I just wanna die and nothing change

**Info (please complete the following information):**
- Mods : **https://pastebin.com/6KksRU0n**
 - Magma Version: Magma Dev HEAD-1bc8635
 - OS: Linux

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
Do you have a gravestone mod or something?
