### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jwiley17** [magmafoundation/Magma#397]
**Describe the bug**
Upon death while holding a stack of spears from Spartan Weaponry, player will drop multiple stacks of spears.

**To Reproduce**
1. Have a stack of spears on your player.
2. Die to anything.
3. Instant duplication of spears, usually a random amount.

**Expected behavior**
Spears should not duplicate on death and should instead drop like any other item.

**Screenshots**
Here's a video I found in the Magma discord sent by another user: https://youtu.be/z7OEanNRjb0

**Info**
- Mod Name: Spartan Weaponry
- Mod Version: 1.12.2-beta-1.3.8
- Magma Version: 1bc8635
- OS: Linux 5.4.0-59-generic (amd64)

**Additional context**
Should be mentioned that this seems like an issue spoken on by other Magma users and is not isolated. It was unable to be reproduced in normal forge. This bug was found within RLCraft. It has not been observed to happen with any spear other than stone but other materials are not yet ruled out. My mod and plugin list can be found here: https://mcpaste.io/d50f5a6438d3bc2e

**Comment by kwright02** [comment]
We’ve seen this off and on for a while now, I have no information to investigate this so I have to close this. There is no reason for this behavior to happen
