### ISSUE TITLE
[BUG] MAGMA ISSUE!

### ISSUE THREAD

**Issue by RedLegend20** [magmafoundation/Magma#398]
**Describe the bug**
So, I am having difficulties with trying to start this magma server.
The .bat files will try to start it, but it keeps saying what u will see down below.
Please help a mans out.

**The console problem**
"Starting Magma
Checking for new version...
Failed to retrieve latest version.
A problem occurred running the Server launcher."

**Screenshot**
![Capture](https://user-images.githubusercontent.com/73206998/111795609-5d321500-8895-11eb-8b7d-8d3867361d6e.PNG)

**Info**
 - Platform: None, I made this server for only my PC resources.
 - Magma Version: Magma Dev HEAD-1bc8635

**Comment by kwright02** [comment]
There seems to be an error in the auto updater so just disable with updating for now

**Comment by RedLegend20** [comment]
> There seems to be an error in the auto updater so just disable with updating for now

How do I disable it?

**Comment by UeberallGebannt** [comment]
magma.yml

**Comment by RedLegend20** [comment]
> magma.yml

I found the auto-updater. and I turned it to false. but when I tried starting it up again it said the same thing.

**Comment by RedLegend20** [comment]
> magma.yml

never mind somehow it just started working
