### ISSUE TITLE
[BUG] Can't start Server at first time

### ISSUE THREAD

**Issue by nbartokos** [magmafoundation/Magma#402]
**Describe the bug**

I just downloaded the latest Magma (1.16) EA-Version and tried to run it with
"java -jar forge-1.16.4-35.1.28-34782a6.jar"
(I get this bug even with -Xmx and -Xms Parameters)

**Expected behavior**
Cant boot up the server

**Screenshots**
![grafik](https://user-images.githubusercontent.com/16653768/111850342-53012c80-8910-11eb-839d-67a7df4a2287.png)

**Info (please complete the following information):**
- Mod Name: /
 - Mod Version: / 
 - Magma Version: Magma 1.16.4-25.1.28-34782a6
 - OS: Windows 10 x64

**Additional context**
I tried using Java 8 and 11, but it didnt change anything.
I dont use any mods or plugins now, it was a clean install from the newest installer.

**Comment by UeberallGebannt** [comment]
This bug should be fixed in the latest release

**Comment by UeberallGebannt** [comment]
Also this is the wrong repository, please use the 1.16 repository for magma 1.16
