### ISSUE TITLE
[BUG] restart Unknown command 1.12.2 

### ISSUE THREAD

**Issue by MiFliK** [magmafoundation/Magma#403]
Server version 1.12.2 
Magma Version Magma-1bc8635
Screenshot https://imgur.com/a/BfABFRr
The essence of the error
When prescribing restart An unknown command gives an error
This command is present in spigot and Craft bukkit and paper
This is one of the most important commands

**Comment by Amgelo563** [comment]
Due to the way mods work, no restart command will be implemented in the near future. In Kwright's own words:

![image](https://user-images.githubusercontent.com/61554601/111857906-c9972d80-8902-11eb-9944-1533f42c076d.png)

**Comment by MiFliK** [comment]
the fact is that not (advertising) in the mohist core there is a reboot function

**Comment by Amgelo563** [comment]
Both softwares work quite differently so there are cases where some things work on one but it doesn't work on the other, and this may be one of these cases. For now I don't think it's priority to work for a fix as, as I said, there are some workarounds to it. Maybe on the future, just not top priority.

**Comment by MiFliK** [comment]
> Both softwares work quite differently so there are cases where some things work on one but it doesn't work on the other, and this may be one of these cases. For now I don't think it's priority to work for a fix as, as I said, there are some workarounds to it. Maybe on the future, just not top priority.

If you put the hosting server on there is a restart button, will it work?

**Comment by Amgelo563** [comment]
Yes, those panels just juse /stop and then start the server again using a script. It should work as intended.
