### ISSUE TITLE
[Issue] unable to close magma server

### ISSUE THREAD

**Issue by BookWyrm114** [magmafoundation/Magma#406]
I can’t open magma with terminal because I’m not on Java 8, but that is not an issue with magma, I can still open magma by double-clicking it, or right-clicking it and pressing “open”, but if I open it this way, no window pops up, the server runs, but is not visible at all, and cannot be closed without shutting down the computer.

**Comment by UeberallGebannt** [comment]
its just open in the background without a visible console, go to your taskmanager and close java/openjdk

**Comment by BookWyrm114** [comment]
I use Mac, rather than windows, but I tried going to the “force quit” window, which usually shows all open programs, but it did not show magma or Java open
