### ISSUE TITLE
[Feature] Player#setPlayerListHeaderFooter

### ISSUE THREAD

**Issue by GamingCrafthd** [magmafoundation/Magma#408]
**Describe the feature**
`org.bukkit.entity.Player.setPlayerListHeaderFooter(BaseComponent[])` from PaperMC

**Reason why this feature should exist**
Because it's better than using Packets.

**Screenshots**
If applicable, add screenshots to help explain your feature:
![grafik](https://user-images.githubusercontent.com/49761607/112758786-62f3cd00-8ff0-11eb-9eac-86430451c9c3.png)

**Comment by Hexeption** [comment]
This has been added ac882e6a8572ea1923becfd0aba22ac1de3e83a7
