### ISSUE TITLE
[BUG] Task genPluginJar borken because of forge maven repos

### ISSUE THREAD

**Issue by TroyNeubauer** [magmafoundation/Magma#417]
**Describe the bug**
When running ./gradlew genPluginJar gralde complains that it cannot resolve de.oceanlabs.mcp:mcp:1.12.2. 

**To Reproduce**
Follow plugin dev steps on the readme:
Clone repo
Init submodules
```./gradlew genPluginJar```

**Expected behavior**
Gradle spits out a plugin jar that I can use to start my plugin development

**Screenshots**
<details>
  <summary>Output from gradle</summary>
troy@troys-server ~/M/U/Magma (master)> gradle genPluginJar
Configuration on demand is an incubating feature.

> Configure project :
[Fatal Error] httpclient-4.3.6.pom:2:1: Content is not allowed in prolog.
[Fatal Error] httpcore-4.3.3.pom:2:1: Content is not allowed in prolog.
48ec0a1
This mapping 'snapshot_nodoc_20171003' was designed for MC 1.12! Use at your own peril.
WARNING: You are using an unsupported version of ForgeGradle.
Please consider upgrading to ForgeGradle 4 and helping in the efforts to get old versions working on the modern toolchain.
See https://gist.github.com/TheCurle/fe7ad3ede188cbdd15c235cc75d52d4a for more info on contributing.

> Task :extractMcpData FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':extractMcpData'.
> Could not resolve all files for configuration ':forgeGradleMcpData'.
   > Could not resolve de.oceanlabs.mcp:mcp:1.12.2.
     Required by:
         project :
      > Could not resolve de.oceanlabs.mcp:mcp:1.12.2.
         > Could not get resource 'https://mvnrepository.com/artifact/de/oceanlabs/mcp/mcp/1.12.2/mcp-1.12.2.pom'.
            > Could not GET 'https://mvnrepository.com/artifact/de/oceanlabs/mcp/mcp/1.12.2/mcp-1.12.2.pom'. Received status code 403 from server: Forbidden
      > Could not resolve de.oceanlabs.mcp:mcp:1.12.2.
         > Could not get resource 'https://repo.hexeption.dev/repository/magma/de/oceanlabs/mcp/mcp/1.12.2/mcp-1.12.2.pom'.
            > Could not GET 'https://repo.hexeption.dev/repository/magma/de/oceanlabs/mcp/mcp/1.12.2/mcp-1.12.2.pom'.
               > Connect to repo.hexeption.dev:443 [repo.hexeption.dev/185.173.26.93] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
1 actionable task: 1 executed

</details>

**Info:**
- Mod Name: N/A
 - Mod Version: N/A
 - Magma Version: master (48ec0a12fa66ae41fc1650db7e60c75adb0f8d49)
 - OS: Arch Linux 5.11.15

**Comment by TroyNeubauer** [comment]
It turns out that my system has gradle 6.8.3 installed and I muscle memory typed ```gradle genPluginJar``` thinking it would be the same as running ```./gradlew ...``` (which looks like its on gradle version 5.6). Apparently not. 

./gradlew genPluginJar gets further now but it fails while looking for bukkit:bukkit:1.12.2-R0.1.

<details>
<summary>Here is a complete log of the current error</summary>
<code>
troy@troys-server ~/M/U/Magma (master) [1]> ./gradlew genPluginJar
Configuration on demand is an incubating feature.

> Configure project :
[Fatal Error] httpclient-4.3.6.pom:2:1: Content is not allowed in prolog.
[Fatal Error] httpcore-4.3.3.pom:2:1: Content is not allowed in prolog.

This mapping 'snapshot_nodoc_20171003' was designed for MC 1.12! Use at your own peril.
WARNING: You are using an unsupported version of ForgeGradle.
Please consider upgrading to ForgeGradle 4 and helping in the efforts to get old versions working on the modern toolchain.
See https://gist.github.com/TheCurle/fe7ad3ede188cbdd15c235cc75d52d4a for more info on contributing.

> Task :patchMagmaJar
Patching failed: net/minecraftforge/common/ForgeVersion.java Cannot find hunk target
  3: Cannot find hunk target @ 0
  1/3 failed
  Rejects written to /home/troy/Minecraft/Upstream/Magma/patches/net/minecraftforge/common/ForgeVersion.java.patch.rej

> Task :makeJarMagma
------------------------
--------SUB-CALL--------
------------------------

> Task :Magma:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':Magma:compileJava'.
> Could not resolve all files for configuration ':Magma:compileClasspath'.
   > Could not resolve bukkit:bukkit:1.12.2-R0.1.
     Required by:
         project :Magma
      > Could not resolve bukkit:bukkit:1.12.2-R0.1.
         > Could not get resource 'https://repo.hexeption.dev/repository/magma/bukkit/bukkit/1.12.2-R0.1/bukkit-1.12.2-R0.1.pom'.
            > Could not GET 'https://repo.hexeption.dev/repository/magma/bukkit/bukkit/1.12.2-R0.1/bukkit-1.12.2-R0.1.pom'.
               > Connect to repo.hexeption.dev:443 [repo.hexeption.dev/185.173.26.93] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
1 actionable task: 1 executed

> Task :makeJarMagma FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':makeJarMagma'.
> Could not execute build using Gradle installation '/home/troy/.gradle/wrapper/dists/gradle-5.6-all/4chhpeaqtrfx4ih6mafwwr40u/gradle-5.6'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
13 actionable tasks: 6 executed, 7 up-to-date
</code>
</details>

**Comment by UeberallGebannt** [comment]
You can use the magma-server jar for coding plugins too while the `genPluginJar` command is broken, there are currently some issues with Forge's repos since they changed

**Comment by UeberallGebannt** [comment]
sorry for closing, pressed the wrong button xD

**Comment by kwright02** [comment]
Fixed on latest code. Just make sure to run it from IntelliJ
