### ISSUE TITLE
[Issue] Startup Crash

### ISSUE THREAD

**Issue by PapaWulf-Lunar** [magmafoundation/Magma#418]
What is wrong: 
Logs: (https://mclo.gs/0hFzALV)
Magma Version: Magma Dev HEAD-1bc8635
Mod Version: RAD 1.45 (https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons)
Mods List: 

[ANGRY PIXEL] The Betweenlands (by oily_oli)
Aether Continuation (by raptor4694)
Aether: Lost Content (by ModdingLegacy)
AI Improvements (by DarkGuardsman)
Akashic Tome (by Vazkii)
AppleCore (by squeek502)
AppleSkin (by squeek502)
Aquaculture 2 (by Shadowclaimer)
Aroma1997Core (by Aroma1997)
Aroma1997s Dimensional World (by Aroma1997)
AtomicStryker's Infernal Mobs (by atomicstrykergrumpy)
Atum 2: Return to the Sands (by Shadowclaimer)
AutoRegLib (by Vazkii)
Baubles (by Azanor13)
Better Advancements (by way2muchnoise)
Better Diving (by meldexun)
BetterFps (by Guichaguri)
BiblioCraft (by Nuchaz)
Bigger Packets Please (by ElNounch)
Bloodmoon (by Lumien231)
Bonsai Trees 2 (by davenonymous)
Bountiful (by ejektaflex)
Building Gadgets (by Direwolf20)
Cavern II (by kegare0127)
Chameleon (by Texelsaur)
Chance Cubes (by TurkeyDev)
Charm (by svenhjol)
Chest Transporter (by cubex2)
Chicken Chunks 1.8.+ (by covers1624)
Chisel (by tterrag1098)
Clumps (by Jaredlll08)
CodeChicken Lib 1.8.+ (by covers1624)
Colossal Chests (by kroeser)
Comforts (by TheIllusiveC4)
ConnectedTexturesMod (by tterrag1098)
Controlling (by Jaredlll08)
Cooking for Blockheads (by BlayTheNinth)
Corpse (by henkelmax)
Cosmetic Armor Reworked (by LainMI)
CplPibald's Tweaks (by cplpibald)
CraftTweaker (by Jaredlll08)
Creeper Confetti (by SR2610)
Crimson Revelations (by mobiusflip)
Cucumber Library (by BlakeBr0)
Custom Main Menu (by Lumien231)
Customized Dungeon Loot (by XxRexRaptorxX)
Cyclic (by Lothrazar)
Cyclops Core (by kroeser)
DefaultSettings (by PT400C)
DimensionalDoors (by DimensionalDevelopment)
DiscordSuite (by hrznstudio)
Doggy Talents (by percivalalb)
Doomlike Dungeons (by JaredBGreat)
Dungeon Tactics (by PegBeard)
Dynamic Surroundings (by OreCruncher)
Electroblob's Wizardry (by Electroblob)
Elenai Dodge (by ElenaiDev)
Embers Rekindled (by BordListian)
Embersified (by TheRealp455w0rd)
Enchantment Descriptions (by DarkhaxDev)
Engineers Workshop Reborn (by modmuss50)
Extra Alchemy (by zabi94)
Extra Spells (Electroblob's Wizardry) (by meldexun)
Extra Utilities (by RWTema)
FastFurnace (by Shadows_of_Fire)
FastWorkbench (by Shadows_of_Fire)
Foam​Fix (by asiekierka)
ForgeEndertech (by EnderLanky)
FTB Backups (by LatvianModder)
FTB Guides 2 (by LatvianModder)
FTB Library (by LatvianModder)
FTB Money (by LatvianModder)
FTB Quests (by LatvianModder)
FTB Utilities (by LatvianModder)
Heroic Armory (by skeddles)
Hooked (by Thecodewarrior1)
Hwyla (by TehNut)
Ice and Fire: Dragons in a whole new light! (by alex1the1666)
Improved Backpacks (by DreenDexTwitch)
Inventory Pets (by Purplicious_Cow_)
Inventory Tweaks (by JimeoWan)
Item Filters (by LatvianModder)
ItemPhysic Lite (by CreativeMD)
IvToolkit (by Ivorforce)
Jack-O'-Launcher (by ochotonida)
JourneyMap (by techbrew)
Just Enough Items (JEI) (by mezz)
JustEnoughIDs (by Runemoro)
LetsEncryptCraft (by CloudyPSP)
Level Up! Reloaded (by BeetoGuy)
LibrarianLib (by wiresegal)
LibraryEx (by LogicTechCorp)
LimeLib (by KidsDontPlay)
Living Enchantment (by Clownvin)
LLibrary (by _ForgeUser11902522)
Login Shield (by Glasspelican)
LunatriusCore (by Lunatrius)
MegaLoot (by Winter_Grave)
Minerva Library (by zabi94)
Mouse Tweaks (by YaLTeR)
Mowzie's Mobs (by bobmowzie)
Mystical Agriculture (by BlakeBr0)
Mystical Mechanics API (by BordListian)
Nature's Compass (by Chaosyr)
Neat (by Vazkii)
NetherEx (by LogicTechCorp)
NetherPortalFix (by BlayTheNinth)
No Recipe Book (by Seneschal_Luwin)
Nomadic Tents (by skyjay1)
OpenBlocks (by OpenMods)
OpenModsLib (by OpenMods)
Ordinary Coins (by flametaichou)
Ore Excavation (by Funwayguy)
OreLib (by OreCruncher)
Pam's HarvestCraft (by pamharvestcraft)
Patchouli (by Vazkii)
Phosphor (Forge) (by jellysquid_)
Placeable Items (by Ferdz_)
Placebo (by Shadows_of_Fire)
Portable Crafting (by gr8pefish)
Potion Core (by Tmtravlr)
Prefab (by wuestman)
Progressive Bosses (by InsaneGames_)
Project: Vibrant Journeys (by solis_nova123)
Pyramid Plunder (by Laton95)
Quality Tools (by Tmtravlr)
Quark (by Vazkii)
Quark Oddities (by Vazkii)
Random Loot Mod (by milomaz1)
Random Things (by Lumien231)
RandomPatches (by TheRandomLabs)
RandomTweaks (by TheRandomLabs)
ReAuth (by TechnicianLP)
Reborn Core (by modmuss50)
Recurrent Complex (by Ivorforce)
Reliquary v1.3 (by P3pp3rF1y)
Resource Loader (by Lumien231)
Roguelike Dungeons (by greymerktv)
Rope Bridge (by lordcazsius)
Rough Tweaks (by Lellson8)
Rustic (by mangoose3039)
Scaling Health (by SilentChaos512)
Shadowfacts' Forgelin (by ShadowfactsDev)
Signpost (by Gollorum)
Silent Lib (by SilentChaos512)
Simple Storage Network (by Lothrazar)
Skewers (by Casadis)
Sound Filters (by Tmtravlr)
Spartan and Fire (by cbkovak)
Spartan Shields (by ObliviousSpartan)
Spartan Weaponry (by ObliviousSpartan)
Spawn Temple (by Iastre)
Spice of Life: Carrot Edition (by lordcazsius)
Stackie (by Lunatrius)
stimmedcow : NoMoreRecipeConflict (by GotoLink)
Storage Drawers (by Texelsaur)
Straw Golem (by fradige95)
Stuff A Sock In It (by DarkhaxDev)
Subterranean Switcheroo (by Lordepos)
SwingThroughGrass (by exidex)
Terracart Reloaded (by Kreezxil)
Thaumcraft (by Azanor13)
Thaumic Augmentation (by TheCodex6824)
Thaumic Inventory Scanning (Thaumcraft Addon) (by BlayTheNinth)
The Aether (by GildedGames)
The Beneath (by Shinoow)
The Disenchanter Mod (by impelon)
The Twilight Forest (by Benimatic)
Tropicraft (by Cojomax99)
Unique Crops (by BlueNeenja)
Unique Enchantments (by Speiger)
Uppers (by vadis365)
VanillaFix (by Runemoro)
VanillaTweaks (by StrikerRocker)
ViesCraft - Airships! (by Vies)
V-Tweaks (by oitsjustjose)
Waystones (by BlayTheNinth)
XP Tome (by bl4ckscor3)

Removed: OTG & Biome Bundles

Plugin List: NONE

OS: Ubuntu

**Comment by UeberallGebannt** [comment]
Please disable the autoupdater by adding `-dau` at the end of your start file
