### ISSUE TITLE
[Issue] Server takes 20 minutes to boot

### ISSUE THREAD

**Issue by PapaWulf-Lunar** [magmafoundation/Magma#419]
What is wrong: 

Logs: (https://mclo.gs/rYaWGzK)
It waits on the foamfix for around 10 minutes. I tried removing all of the plugins and still didn't work. Am I doing something wrong? Or is it a magma issue? (And I know this is not my hardware as unfortunately sponge takes about 3-4 minutes to boot)

Magma Version: 1bc8635

Mod Version: RAD 1.45

MODS:

[ANGRY PIXEL] The Betweenlands (by oily_oli)
Aether Continuation (by raptor4694)
Aether: Lost Content (by ModdingLegacy)
AI Improvements (by DarkGuardsman)
Akashic Tome (by Vazkii)
AppleCore (by squeek502)
AppleSkin (by squeek502)
Aquaculture 2 (by Shadowclaimer)
Aroma1997Core (by Aroma1997)
Aroma1997s Dimensional World (by Aroma1997)
AtomicStryker's Infernal Mobs (by atomicstrykergrumpy)
Atum 2: Return to the Sands (by Shadowclaimer)
AutoRegLib (by Vazkii)
Baubles (by Azanor13)
Better Advancements (by way2muchnoise)
Better Diving (by meldexun)
BetterFps (by Guichaguri)
BiblioCraft (by Nuchaz)
Bigger Packets Please (by ElNounch)
Bloodmoon (by Lumien231)
Bonsai Trees 2 (by davenonymous)
Bountiful (by ejektaflex)
Building Gadgets (by Direwolf20)
Cavern II (by kegare0127)
Chameleon (by Texelsaur)
Chance Cubes (by TurkeyDev)
Charm (by svenhjol)
Chest Transporter (by cubex2)
Chicken Chunks 1.8.+ (by covers1624)
Chisel (by tterrag1098)
Clumps (by Jaredlll08)
CodeChicken Lib 1.8.+ (by covers1624)
Colossal Chests (by kroeser)
Comforts (by TheIllusiveC4)
ConnectedTexturesMod (by tterrag1098)
Controlling (by Jaredlll08)
Cooking for Blockheads (by BlayTheNinth)
Corpse (by henkelmax)
Cosmetic Armor Reworked (by LainMI)
CplPibald's Tweaks (by cplpibald)
CraftTweaker (by Jaredlll08)
Creeper Confetti (by SR2610)
Crimson Revelations (by mobiusflip)
Cucumber Library (by BlakeBr0)
Custom Main Menu (by Lumien231)
Customized Dungeon Loot (by XxRexRaptorxX)
Cyclic (by Lothrazar)
Cyclops Core (by kroeser)
DefaultSettings (by PT400C)
DimensionalDoors (by DimensionalDevelopment)
DiscordSuite (by hrznstudio)
Doggy Talents (by percivalalb)
Doomlike Dungeons (by JaredBGreat)
Dungeon Tactics (by PegBeard)
Dynamic Surroundings (by OreCruncher)
Electroblob's Wizardry (by Electroblob)
Elenai Dodge (by ElenaiDev)
Embers Rekindled (by BordListian)
Embersified (by TheRealp455w0rd)
Enchantment Descriptions (by DarkhaxDev)
Engineers Workshop Reborn (by modmuss50)
Extra Alchemy (by zabi94)
Extra Spells (Electroblob's Wizardry) (by meldexun)
Extra Utilities (by RWTema)
FastFurnace (by Shadows_of_Fire)
FastWorkbench (by Shadows_of_Fire)
Foam​Fix (by asiekierka)
ForgeEndertech (by EnderLanky)
FTB Backups (by LatvianModder)
FTB Guides 2 (by LatvianModder)
FTB Library (by LatvianModder)
FTB Money (by LatvianModder)
FTB Quests (by LatvianModder)
FTB Utilities (by LatvianModder)
Heroic Armory (by skeddles)
Hooked (by Thecodewarrior1)
Hwyla (by TehNut)
Ice and Fire: Dragons in a whole new light! (by alex1the1666)
Improved Backpacks (by DreenDexTwitch)
Inventory Pets (by Purplicious_Cow_)
Inventory Tweaks (by JimeoWan)
Item Filters (by LatvianModder)
ItemPhysic Lite (by CreativeMD)
IvToolkit (by Ivorforce)
Jack-O'-Launcher (by ochotonida)
JourneyMap (by techbrew)
Just Enough Items (JEI) (by mezz)
JustEnoughIDs (by Runemoro)
LetsEncryptCraft (by CloudyPSP)
Level Up! Reloaded (by BeetoGuy)
LibrarianLib (by wiresegal)
LibraryEx (by LogicTechCorp)
LimeLib (by KidsDontPlay)
Living Enchantment (by Clownvin)
LLibrary (by ForgeUser11902522)
Login Shield (by Glasspelican)
LunatriusCore (by Lunatrius)
MegaLoot (by Winter_Grave)
Minerva Library (by zabi94)
Mouse Tweaks (by YaLTeR)
Mowzie's Mobs (by bobmowzie)
Mystical Agriculture (by BlakeBr0)
Mystical Mechanics API (by BordListian)
Nature's Compass (by Chaosyr)
Neat (by Vazkii)
NetherEx (by LogicTechCorp)
NetherPortalFix (by BlayTheNinth)
No Recipe Book (by Seneschal_Luwin)
Nomadic Tents (by skyjay1)
OpenBlocks (by OpenMods)
OpenModsLib (by OpenMods)
Ordinary Coins (by flametaichou)
Ore Excavation (by Funwayguy)
OreLib (by OreCruncher)
Pam's HarvestCraft (by pamharvestcraft)
Patchouli (by Vazkii)
Phosphor (Forge) (by jellysquid)
Placeable Items (by Ferdz_)
Placebo (by Shadows_of_Fire)
Portable Crafting (by gr8pefish)
Potion Core (by Tmtravlr)
Prefab (by wuestman)
Progressive Bosses (by InsaneGames_)
Project: Vibrant Journeys (by solis_nova123)
Pyramid Plunder (by Laton95)
Quality Tools (by Tmtravlr)
Quark (by Vazkii)
Quark Oddities (by Vazkii)
Random Loot Mod (by milomaz1)
Random Things (by Lumien231)
RandomPatches (by TheRandomLabs)
RandomTweaks (by TheRandomLabs)
ReAuth (by TechnicianLP)
Reborn Core (by modmuss50)
Recurrent Complex (by Ivorforce)
Reliquary v1.3 (by P3pp3rF1y)
Resource Loader (by Lumien231)
Roguelike Dungeons (by greymerktv)
Rope Bridge (by lordcazsius)
Rough Tweaks (by Lellson8)
Rustic (by mangoose3039)
Scaling Health (by SilentChaos512)
Shadowfacts' Forgelin (by ShadowfactsDev)
Signpost (by Gollorum)
Silent Lib (by SilentChaos512)
Simple Storage Network (by Lothrazar)
Skewers (by Casadis)
Sound Filters (by Tmtravlr)
Spartan and Fire (by cbkovak)
Spartan Shields (by ObliviousSpartan)
Spartan Weaponry (by ObliviousSpartan)
Spawn Temple (by Iastre)
Spice of Life: Carrot Edition (by lordcazsius)
Stackie (by Lunatrius)
stimmedcow : NoMoreRecipeConflict (by GotoLink)
Storage Drawers (by Texelsaur)
Straw Golem (by fradige95)
Stuff A Sock In It (by DarkhaxDev)
Subterranean Switcheroo (by Lordepos)
SwingThroughGrass (by exidex)
Terracart Reloaded (by Kreezxil)
Thaumcraft (by Azanor13)
Thaumic Augmentation (by TheCodex6824)
Thaumic Inventory Scanning (Thaumcraft Addon) (by BlayTheNinth)
The Aether (by GildedGames)
The Beneath (by Shinoow)
The Disenchanter Mod (by impelon)
The Twilight Forest (by Benimatic)
Tropicraft (by Cojomax99)
Unique Crops (by BlueNeenja)
Unique Enchantments (by Speiger)
Uppers (by vadis365)
VanillaFix (by Runemoro)
VanillaTweaks (by StrikerRocker)
ViesCraft - Airships! (by Vies)
V-Tweaks (by oitsjustjose)
Waystones (by BlayTheNinth)
XP Tome (by bl4ckscor3)

Removed: OTG & Biome Bundles

Plugin List: 

ArmorStandTools
BanItem
BetterRTP
ChatManager
ChatReaction
ChestShop
Citizens
Clearlag
CommandAlias
CoreProtect
CrazyCrates
CS-API
DailyBonus
DiscordSRV
DiscordSRV Staff Chat
dtlTradersPlus
EasyBackup
EpicSet-Tokens
Essentials
EssentialsChat
EssentialsGEOIP
EssentialsSpawn
FastAsyncWorldEdit
Featherboard
GriefPrevention
HeadDatabase
HolographicDisplay
InteractiveChat
InteractiveChatDiscord
KitAdder
LitePlaytimeRewards
LuckPerms
Multiverse-Core
MVdWPlaceholderAPI
OfflineTeleporter
OpenINV
PlaceholderAPI
PlotSquared
PlugMan
ProtocolLib (Suggested version)
Spark
UltimateAutoRestart
UltimateFreeze
Vault
WildLoaders
WorldEdit
WorldGuard

OS: Ubuntu

**Comment by kwright02** [comment]
Bruh look at the number of mods you have..... of course it's going to take a while. Especially if you don't have much ram allocated.

**Comment by PapaWulf-Lunar** [comment]
It doesn't even boot with magma though.. Sponge is loading everything so much faster, thats why I came for support.. And of course it's a lot of mods. That's what modpacks do

**Comment by blakedj012** [comment]
Use Mohist instead. It works great without Problems and with a active Development Team.

**Comment by kwright02** [comment]
Magma is not the same thing as sponge. If you try to use it the same you will not be happy with the results.

**Comment by blakedj012** [comment]
We are not speak about Sponge. We are speak about Mohist. Paper Forge Client.

**Comment by Picono435** [comment]
> We are not speak about Sponge. We are speak about Mohist. Paper Forge Client.

He was talking about this comment:
> It doesn't even boot with magma though.. Sponge is loading everything so much faster, thats why I came for support.. And of course it's a lot of mods. That's what modpacks do
