### ISSUE TITLE
[BUG] Server Crash 1.12.2 CraftServer.java Null value

### ISSUE THREAD

**Issue by austin4195** [magmafoundation/Magma#421]
**Describe the bug**
Server crash due to an error in CraftServer.java where any forge plugin not expecting a null value will break.

**To Reproduce**
1. Boot server with forge plugin attempting to register commands
2. Crash

**Expected behavior**
Server should boot normally and function.

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: BiShops
 - Mod Version: 2.0
 - Magma Version: 48ec0a1
 - OS: Linux

**Additional context**
Crash Report: https://mclo.gs/rryDjDv

Mods List: minecraft, mcp, FML, forge, adminpc, aquaauras, aquacensor, aquadaycare, aquaencounters, aquagyms, aquamarket, aquashards, aquaskills, aquaslots, aquavaults, aquaworlds, badgetracker, battletower, bishops, cable-libs, clearfairy, cranegame, dailies, flashplus, flashspec, forgelin, gameshark, gooeylibs, gooeylibs2, itemmodifiers, itemshrinefee, libcious, lunatriuscore, mapimages, modbanner, moveskillcontroller, partyspawns, pcsorter, pixelcasino, pixelextras, pixelhuntforge, pixelmon, pixelmonsts, pixeloptimizer, pixelplushies, pokedisplay, pokeshinybuff, radioklink, schematica, simpledexrewards, trainercommands, trainercooldown, towerbattle, trivia, wondertrade, yetanotherpokebuilder

Message from BiShops Dev: 

The issue can be found here https://github.com/magmafoundation/Magma/blob/1bc863502df8b28948243988bdb1db3f901470e4/src/main/java/org/bukkit/craftbukkit/v1_12_R1/CraftServer.java#L384

That is the line in question you should report, any plugin not expecting a null value will break (most won't since the field isn't annotated as Nullable nor does vanilla/forge pass in a null at any time)

They have another instance of this where they actually took that into consideration.

**Comment by kwright02** [comment]
Can you re-upload your log, please? it's expired.

**Comment by Licious17** [comment]
I'm the developer of the plugin that originally mentioned this to Austin, fixed in #438
This issue is present on other Java based plugins and most Kotlin based plugins unless the developer goes out of their way to make the param nullable.
