### ISSUE TITLE
Magma Server Crash | Roguelike Adventures & Dungeons Mod Pack

### ISSUE THREAD

**Issue by CrustTF2** [magmafoundation/Magma#422]
What is wrong: Server crashes after a while
Logs: https://haste.zneix.eu/urovygesov.rb (had errors trying to upload to hastebin so I used this alternative)
Magma Version: Magma 48ec0a1
Mod Version: Modpack is version 1.45
Mods List: https://www.modpackindex.com/modpack/4124/roguelike-adventures-and-dungeons
Plugin List: None

**Comment by Hexeption** [comment]
How long is a while and can we have a full log.
