### ISSUE TITLE
[BUG] Magma server chat glitchy

### ISSUE THREAD

**Issue by Arax678** [magmafoundation/Magma#424]
**Describe the bug**
A clear and concise description of what the bug is:
Every time i send a message in-game, it sends twice.

**To Reproduce**

**Expected behavior**
A clear and concise description of what you expected to happen: 
I just expected 1 normal Minecraft message, not duplicates.

**Screenshots**
If applicable, add screenshots to help explain your problem:

![](https://cdn.discordapp.com/attachments/781494300236185650/845360470428221470/unknown.png)

![](https://cdn.discordapp.com/attachments/781494300236185650/845360564959838278/unknown.png)

**Info (please complete the following information):**
- Mod Name:
>AbyssalDepths-1.12.2-0.3.2
>Aquaculture-1.12.2-1.6.8
>AutoRegLib-1.3-32 
>BetterMineshaftsForge-1.12.2-2.2.1
>Bloodmoon-MC1.12.2-1.5.3
>buildcraft-all-7.99.24.8
>camera-1.0.10
>CasinoCraft_1.12.2_v11
>Cavern_1.12.2-v2.3.1
>cc-tweaked-1.12.2-1.89.1
>CD4017BE_lib-1.12.2-6.5.1
>Chisel-MC1.12.2-0.2.1.35
>chiselsandbits-14.33
>coroutil-1.12.1-1.2.37
>CTM-MC1.12.2-0.3.3.22
>Farseek-1.12-2.5.1
>FastLeafDecay-v14
>Flan's+Mod-1.12.2-5.10.0
>furniture-6.3.1-1.12.2 
>HardcoreDarkness-MC1.12.2-2.0
>Hwyla-1.8.26-B41_1.12.2
>jei_1.12.2-4.16.1.301
>jev-1.12.2-2.0.0
>journeymap-1.12.2-5.7.1
>JustEnoughResources-1.12.2-0.9.2.60
>kidnapmod-1.12.2-1.3.0
>llibrary-1.7.9-1.12.2
>MCA-1.12.2-6.1.0-universal
>mowziesmobs-1.5.6
>obfuscate-0.2.6-1.12.2
>PTRLib-1.0.3
>Quark-r1.6-179
>RikMuldsCore_1.3.3
>SRParasites-1.12.2v1.8.2
>Streams-1.12-0.4.9
>subterraneanwaters-1.12.2-1.7.9
>The+Beneath-1.12.2-1.7.0
>TheCampingMod_2.4.3
>vehicle-mod-0.44.1-1.12.2
>VerticallyStackedDimensions-1.12.2-0.1.9
>worleycaves-1.12.2-1.5.2
>zombieawareness-1.12.1-1.11.16
>memory_repo (FOLDER)
 - Mod Version: 1.12.2
 - Magma Version: Magma-48ec0a1-server
 - OS: Windows 10

**Additional context**
Add any other context about the problem here:

**Comment by kwright02** [comment]
Couldn't reproduce this. One of your plugins or mods is causing this.
