### ISSUE TITLE
[BUG] enable-query forcefully set to true, cannot turn it off

### ISSUE THREAD

**Issue by Lucaskyy** [magmafoundation/Magma#425]
**Describe the bug**
The enable-query option in server.properties cannot be turned off, every time the server starts it is set to true.

**To Reproduce**
1. Set enable-query to false
2. Restart the server
3. enable-query is true again

**Expected behavior**
The enable-query option should not be set to true, and the query server should not start.

**Info (please complete the following information):**
- Mod Name: N/A
 - Mod Version: N/A
 - Magma Version: `ID: 41029204 | Tag: v48ec0a1`
 - OS: Linux

**Comment by kwright02** [comment]
There isn't really a need for it to be false, it's just how you get the server list information
