### ISSUE TITLE
[BUG] TabTPS plugin throws Exception

### ISSUE THREAD

**Issue by Irgendwer01** [magmafoundation/Magma#426]
**Describe the bug**
A clear and concise description of what the bug is:
When trying to use TabTPS Bossbar it throws an Exception of not found field in Class.

**To Reproduce**
1. Install TPS
2. Execute /tabtps toggle bossbar as player
3. See Error

**Expected behavior**
A clear and concise description of what you expected to happen:
That it works as intended and not throws an error

**Info (please complete the following information):**
- Plugin Name: TabTPS 1.3.5
 - Plugin Version: 
 - Magma Version:  48ec0a1
 - OS: Ubuntu 20.04

**Additional context**
Add any other context about the problem here:
When using /tabtps toggle actionbar or tab it not throws an Exception, but shows nothing on client
The Exception: https://paste.ubuntu.com/p/k2VchMPXM2/

**Comment by kwright02** [comment]
this happens because of reflection. Because of the way we handle code (We don't re-obfuscate) the reflection is never going to find the field "h"
