### ISSUE TITLE
[Issue] Magma servers not working with Java 16 installed

### ISSUE THREAD

**Issue by JustAssassinExists** [magmafoundation/Magma#442]
Magma does not work when Java 16 is installed, just adding Java 8 to the path does not fix this.

**How to reproduce**
1. Install Java 16
2. See that it does not work
3. try to install Java 8 separately
4. try to add Java 8 to the path
5. No results

**Expected behavior**
Magma ignoring Java 16 and using Java 8, this does not happen

**Screenshots**
https://imgur.com/a/PzRG0US

**Info (please complete the following information):**
- Mod Name: Any mod
 - Mod Version: Any version
 - Magma Version: Latest
 - OS: Windows 10

**Additional context**
Unsure what else to say

No log because the server wont even start.

**Comment by kwright02** [comment]
Well duh, 1.12 runs on Java 8

**Comment by JustAssassinExists** [comment]
as you can see I've tried running both but it doesn't work, I was hoping you all would have some advice

**Comment by Amgelo563** [comment]
Can you show your start script?

**Comment by JustAssassinExists** [comment]
I figured out java 8 didnt world because i had x86 java, fixed that. But i still can't use 1.17 forge with java 16 still installed.

**Comment by UeberallGebannt** [comment]
There isn't Forge for 1.17
