### ISSUE TITLE
Magma is unable to reference Custom (Pixelmon) Items

### ISSUE THREAD

**Issue by FuryFight3r** [magmafoundation/Magma#468]
What is wrong: 
Using minecrafts basic '/give <name> pixelmon:poke_ball' command returns a 'Unknown item name: pixelmon:poke_ball' error, this is also true while trying to use EssentialsX's /Kits to give the player some Poke Balls as a daily kit, with the same error of unknown item name. Pixelmon is working perfectly fine and same with all other mods currently running on the server, everything seems to be working fine with Pixelmon and other Plugins, though it seems Magma is blocking some sort of connection that allows plugins to access pixelmons custom items.
I was so very excited once I'd finally found this setup that works with Pixelmon that allows having extra plugins to stop griefers etc without being locked to a Mod Kit with very little flexibility for adjustment, but it is really a killer for me that I cannot reference any pixelmon Items, as it means all the shops I've made wont work, all the Kits I've made wont work, the Vote Rewards wont work, as they all rely on giving player pixelmon related items, which always returns a value of 'Unknown item name:' whereas pixelmon itself can access its own items, as it Drops pixelmon items from wild pokemon and you gain pixelmon items from Poke Chests, so its not like the items don't exist, its just that I am not allowed to reference them from another plugin it seems.

I also thought I may need to add the pixelmon items into EssentialX's 'CustomItems' file which I did, but that had not changed anything and still was unable to find the item.

Any help or work around would be greatly appreciated, I would really prefer not to have wasted a whole week by investing time in a server base that wont accept references to custom items.

Logs: https://pastebin.com/WbYBBidy (Log after Starting Server)

Magma Version: Forge 1.12.2 Magma (Mods + Plugins) (Magma-1.12.2-761933c)

Mod Version: Pixelmon - Reforged v8.2.0

Mods List:
Pixelmon Reforged v8.2.0 (1.12.2)
PixelmonExtras 2.5.13 (1.12.2)
World Edit Forge 6.1.10 (1.12.2)

Plugin List:
AntiXray v1.9.0
Deluxe Menus v1.13.3
EssentialsX 2.19.0 (+extras, Chat, Discord and Spawn)
LuckPerms v5.3.55
PlaceholderAPI v2.10.10
Vault (Unknown Version)

(I did have more until I started clearing them thinking they may have been the issue with items not working, so I just have the very basics now)

OS:
Myself: Windows 10
Server: I presume some sort of Linux or Windows

EDIT: I have added some screenshots to show that Minecraft is in fact detecting and am able to give myself the Pixelmon items through creative mode, though by using commands or having these items within kits and gui's etc they apparently cannot be found.
![Screenshot_59](https://user-images.githubusercontent.com/44615800/128289809-fb20c48c-7015-420f-869a-be8eb22b4502.png)
![Screenshot_60](https://user-images.githubusercontent.com/44615800/128289811-2516806c-e7b0-4050-8ade-1b7d7b859093.png)
![Screenshot_61](https://user-images.githubusercontent.com/44615800/128289812-89bd64b4-eaff-48cc-b5ba-c9a7a4ac8b66.png)

**Comment by UeberallGebannt** [comment]
You need to populate the Essentials items.csv
https://github.com/UknownGino/ModdedIntegration

**Comment by FuryFight3r** [comment]
> You need to populate the Essentials items.csv
> https://github.com/UknownGino/ModdedIntegration

Thank you for that, I was just about to update this issue as someone had given me this plugin on the Magma Discord, I appreciate the help! :)
