### ISSUE TITLE
[BUG] Crash starting server

### ISSUE THREAD

**Issue by Nagol12344** [magmafoundation/Magma#470]
**Describe the bug**
I start the server and it crashed

**To Reproduce**
1. Start server
2. See error
3. Crash

**Expected behavior**
The server starts

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Info (please complete the following information):**
- Mod Name: n/a
 - Mod Version: n/a
 - Magma Version: Magma-761933c-STABLE-server
 - OS: unknown

**Additional context**
The error in step 2 https://pastebin.com/5TX7i2iY

**Comment by Nagol12344** [comment]
Update: moving to 99be8c5 removes the error but it still crashes

**Comment by LeviPawlak** [comment]
Could you provide a full crash report or server log? I was able to start a server using the latest version https://github.com/magmafoundation/Magma/commit/dd991e7be752083cd151f0e74803dde909b06692.

**Comment by Nagol12344** [comment]
it was my mods, sorry
