### ISSUE TITLE
[1.12.2] [BUG] Registry issues on server

### ISSUE THREAD

**Issue by egg6900** [magmafoundation/Magma#49]
I've given most of the details on the discord already. Upon removing a mod from the world and then trying magma, nobody can join because they just get registry issues. No fix seems available. It's quite gamebreaking because nobody can join the server.
[latest (2).log](https://github.com/magmafoundation/Magma/files/4081671/latest.2.log)

**Comment by Hexeption** [comment]
Can't replicate this?

Steps to reproduce this, please

**Comment by egg6900** [comment]
1. I had a forge server with the latest 1.12.2 version
2. I removed some mods (specifically the Dalek Mod)
3. I then changed from forge to magma and got this issue

That's about it
