### ISSUE TITLE
Ticking entities crash, doesn't happen in forge only enviro[BUG]

### ISSUE THREAD

**Issue by MackBaggins** [magmafoundation/Magma#5]
**Describe the bug**
Server crashes with issues ticking entities

**To Reproduce**
1. Unknown, intermittent

**Expected behavior**
Not to crash

**Screenshots**
N/A

**Info (please complete the following information):**
- Mod Name:N/A
 - Mod Version: N/A
 - Magma Version: dcfd1c1
 - OS: Windows 10 x64

**Additional context**
https://hasteb.in/omaciren.sql

**Comment by Hexeption** [comment]
No longer happening
