### ISSUE TITLE
Problem with max health

### ISSUE THREAD

**Issue by BryceMalloy** [magmafoundation/Magma#501]
**Full Magma version:** Magma-761933c
**Java version:**
**A detailed description of your issue:** A mod (wuxiacraft) allows player to gain a high max health but it is directly conflicting with magma only allowing a person to heal to a maximum value of around 2050. I can't find any configs for magma to increase this maximum value of health.
**Logs (https://mclo.gs/):**
**Mod list:** wuxiacraft
**Plugin list:**
**local host or hosting service:** MC Pro Hosting
**Operating system:** Windows
**Start-up script/flags:**

**Comment by joaoespanhol** [comment]
you need check your file: spigot.yml
![image](https://user-images.githubusercontent.com/22871432/145575421-54bdf19a-ae61-40d5-abca-dd0eed334f93.png)

**Comment by joaoespanhol** [comment]
@Hexeption you can't close ticket, is no problem.
