### ISSUE TITLE
[Bug]: Overlapping enchantments can be accepted in basic forge, but not in magma server (google translation)

### ISSUE THREAD

**Issue by KEVIN910919** [magmafoundation/Magma#512]
### What happened?

I can't use nbtedit to overlap item enchants (basic forge is ok) (google translation)
No error report
Please fix
I need excellent stability of magma server (google translation

https://user-images.githubusercontent.com/84594248/147497900-e02dc687-d254-4ee6-8c22-819085fc3b59.mp4

)

### Mods

![image](https://user-images.githubusercontent.com/84594248/147498009-93b6a380-fef4-498a-8685-37801b2d9c43.png)

### Mod Version

![image](https://user-images.githubusercontent.com/84594248/147498013-335028eb-0ed1-448c-930f-7bb240eba67d.png)

### Magma Version

Magma-761933c-STABLE-server

### OS

Windows

**Comment by UeberallGebannt** [comment]
As far as I know, Bukkit/Spigot/Paper has a fix for this bug because it should not be possible to create items enchanted with the same enchantment multiple times
