### ISSUE TITLE
Critical Injection failure relating to astralsorcery mixins[BUG]

### ISSUE THREAD

**Issue by MackBaggins** [magmafoundation/Magma#52]
**Describe the bug**
Critical injection failure causes server to crash immediately upon launch

**To Reproduce**
1. have magma
2. launch server with astral sorcery
3. See error

**Expected behavior**
Server launches with no issues

**Info (please complete the following information):**
- Mod Name: Astral Sorcery
 - Mod Version: 1.10.21
 - Magma Version: e2b9ab6
 - OS: Windows 10 x64 Professional

https://pastebin.com/6U1y54B7

**Comment by Hexeption** [comment]
Just checked this and i cant replicate this? 
![](https://img.hexeption.co.uk/C9rlPCtZdn.png)
