### ISSUE TITLE
[BUG]Instalación librerias

### ISSUE THREAD

**Issue by javi9davi** [magmafoundation/Magma#53]
Al instalar las librerías en Magma-e2b9ab6-installer me aparece error
When I install the libraries in Magma-e2b9ab6-installer I get an error

**Screenshots**
![image](https://user-images.githubusercontent.com/60230696/73003287-48770000-3dfd-11ea-9c86-7c308c041d9a.png)

 - Magma Version: e2b9ab6
 - OS: Windows 10
HELP PLEASE!!!

**Comment by Hexeption** [comment]
Don't use the installer jar
