### ISSUE TITLE
[Bug]: ProtocolLib Issue Overnight (server console freezes)

### ISSUE THREAD

**Issue by cheesebobi** [magmafoundation/Magma#530]
### What happened?

I run a Modded Faction Server, inherently unstable as you'd expect, however, this newest issue has me beyond confused. The server has been running quite smoothly with no crashes and restarting without any issues. However, last night the server restarted and when booting back up froze on "[ProtocolLib] Started structure compiler thread." this sometimes would happen anyway but a simple restart often fixed it. I have tried restarting the server multiple times and every time it gets stuck on this issue. What makes matters worse is my online test server and home test server (both untouched since before the issue) have also both experienced the exact same issue. I have tried updating the plugin, and the server Jar (Magma) both to no solution.

From my testing it appears to be something to do with the plugin loading in around other plugins. For instance, on its own, launches without a hitch, however with luckPerms and Buycraft will freeze the console. The issue has also been reported on  ProtocolLib dev on their issue tracker: https://github.com/dmulloy2/ProtocolLib/issues/1546

Main and Online Test server run on Linux (to the best of my knowledge) and my home computer test server runs on Windows 10.

**Steps to reproduce the behaviour:**

1. Go to "https://magmafoundation.org/" and install a 1.12.2 server JAR, from my experience any variant but most recent testing has been with Version: v32e7e1a-DEV Date: 2022-03-23T00:47:38Z

2. Once installed add protocolLib (version 4.7.0 was originally on the server but with 4.8.0 the issue is still around)

3. Server at this point should start with no issues, however when I added Buycraft and LuckPerms it would no longer load
(Also other plugins seem to have this effect, these are just 2 I have narrowed down as repeating the problem the fastest, Worldedit, Worldguard and others seems to also reproduce the freeze but I had other plugins present)

4.You will see the console run as normal, but after the "[ProtocolLib] Started structure compiler thread." the server freezes, cannot type in console or even press enter to refresh on my home test setup.

![Home Server Showcase](https://user-images.githubusercontent.com/28841957/159711877-8550716b-110f-4f24-aef4-6f6c2dc25c60.png)

### Mods

The initial issue occurred on my modpack, modlist present in the #modpack-help channel on discord: https://discord.gg/vDnXxYjj

**HOWEVER**, I have since tested with no mods present and the issue still occurs.

### Mod Version

No mods present

### Magma Version

Many versions tested, but latest tests were on: Version: v32e7e1a-DEV Date: 2022-03-23T00:47:38Z

### OS

Linux

### Relevant log output

```shell
[13:34:47] [Server thread/INFO] [Minecraft]: Server permissions file permissions.yml is empty, ignoring it
[13:34:47] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin]: [LuckPerms] Enabling LuckPerms v5.4.13
[13:34:47] [Server thread/INFO] []:         __
[13:34:48] [Server thread/INFO] []:   |    |__)   LuckPerms v5.4.13
[13:34:48] [Server thread/INFO] []:   |___ |      Running on Bukkit - Magma
[13:34:48] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin]: [LuckPerms] Loading configuration...
[13:34:48] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin]: [LuckPerms] Loading storage provider... [H2]
[13:34:48] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin]: [LuckPerms] Loading internal permission managers...
[13:34:48] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin]: [LuckPerms] Performing initial data load...
[13:34:49] [Server thread/INFO] [me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin]: [LuckPerms] Successfully enabled. (took 1690ms)
[13:34:49] [Server thread/INFO] [com.comphenix.protocol.ProtocolLib]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[13:34:49] [Server thread/INFO] [com.comphenix.protocol.ProtocolLib]: [ProtocolLib] Started structure compiler thread.
>
```

**Comment by UeberallGebannt** [comment]
Could you try switching to version v4.5.1?
This version should work as a workaround until fixed

**Comment by hehseomeone** [comment]
Happening on me too, but not with protocolLib, i don't use protocolLib. It is happening on "Enabling Vault". After magma updated yesterday night, this problem occoured. The server just freezed starting, i get the message "Server is still starting" but it's not.

**Comment by PokeSantiTW** [comment]
Same problem, but with Vault v1.7.3-b131. Console justs freeze and I don't have other option that kill the process. This also happened with GriefDefender, but I delete it because of this. Now the problem is in Vault too.

![image](https://user-images.githubusercontent.com/61545363/159749190-398d47ba-0582-440a-be77-55ec0ab62a31.png)

**Comment by cheesebobi** [comment]
> 

I have tried this fix and can confirm the issue persists. I also have frequently had a similar issue with Vault and from memory Vault was indeed causing a similar issue for me when running a test without ProtocolLib

**Comment by cheesebobi** [comment]
I have managed to fix the issue, for both ProtocolLib and Vault. 

**How to Fix:**
Step 1: Install Magma 1.12.2 Version: vad7ca54-CUSTOM Date: 2021-07-08T19:40:39Z
Step 2: Use ProtocolLib v4.5.1 
Step 3: Keep vault the same, vault is not a problem with the version changes.
Step 4: in ProtocolLib config change "background compiler: false" (This step might not be necessary for some)
Step 5: Start the server and relax as life breezes past, have a cup of tea, enjoy a walk outside. 
Step 6: Go subscribe to cheesebobi on YouTube and watch his videos because you owe him for the fix ;p 

**Explanation of the problem to my understanding**
Magma issued an update overnight, on the 23/03/2022 to various instances for the Magma Jar. Some servers and platform also automatically updated. During this latest update round some dependencies became missing for ProtocolLib and Vault making them freeze on load. Going back to the specific versions above has seemingly fixed the issue as the dependency is no longer missing / incorrect or maybe even required.  So the Magma team needs to fix the dependency issue and update their latest Jar.

**Comment by Hexeption** [comment]
Revered change should work now
