### ISSUE TITLE
[Bug]: Pixelmon bug - POKEMONS NOT EVOLVING

### ISSUE THREAD

**Issue by Jesley69** [magmafoundation/Magma#533]
### What happened?

I'm having a problem with the magma API.

For some reason, using the pixelmon mod (minecraft version 1.12.2) the pokemon has a bug when it evolves normally by battling. It simply evolves into its current evolution, for example charmander evolves into charmander.

Is there a solution to this, or are you not aware?
I'm using the latest version of maga 1.12.2
And the pixelmon version is 8.3.8

As soon as I switch to another api (like catserver) the evolutions work again.

### Mods

Pixelmon Reforged

### Mod Version

1.12.2-8.3.8 forge 2860

### Magma Version

va549e0d-DEV 

### OS

Windows

**Comment by Zetthh** [comment]
I have the same problem, the pokemons do not evolve normally after playing normally for a period of X minutes.

If you force the evolution with candies it works, when reconnecting.
