### ISSUE TITLE
[BUG] [1.12.2] BedWars - if you put a block, it will disappear

### ISSUE THREAD

**Issue by Windows10-YT** [magmafoundation/Magma#57]
if you put a block, it will disappear, but if you put a block close to the bed, then it will not disappear https://www.youtube.com/watch?v=ZOAMO7rUn-s&feature=youtu.be

there were no errors in the console or others, the plugin in the screenshot I removed WorldGuard but the result is 0, the core server is Magma-d88b3f8-server.jar (1.12.2), BW BedWars-0.2.5-SNAPSHOT-431.jar
![unknown2](https://user-images.githubusercontent.com/52487964/73128571-32cb2b80-3ff3-11ea-9c8a-8666b9e5fd49.png)

**Comment by Hexeption** [comment]
Can you link the Plugin @Windows10-YT

**Comment by Windows10-YT** [comment]
> Can you link the Plugin @Windows10-YT

Do you need a link to the bedwars plugin?

**Comment by Mc88Donalds** [comment]
Thats what he said...

**Comment by Windows10-YT** [comment]
https://www.spigotmc.org/resources/screamingbedwars-1-9-1-15.63714/

SNAPSHOT https://jenkins.mtorus.cz/job/BedWars/
