### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by planyte** [magmafoundation/Magma#60]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
- Mod Name:
 - Mod Version: 
 - Magma Version: 
 - OS:

**Additional context**
Magma with the player weight mod.
https://cdn.discordapp.com/attachments/663114062061764622/671705739705843726/ScreenShot_20200128161811.png
https://cdn.discordapp.com/attachments/663114062061764622/671730167743250432/ScreenShot_20200128175502.png
https://cdn.discordapp.com/attachments/663114062061764622/671730433381236736/ScreenShot_20200128175642.png

**Comment by planyte** [comment]
Mod player weight 1.12.2 
[crash-2020-01-28_16.23.02-server.txt](https://github.com/magmafoundation/Magma/files/4123490/crash-2020-01-28_16.23.02-server.txt) 
[crash-2020-01-28_16.06.24-server.txt](https://github.com/magmafoundation/Magma/files/4123491/crash-2020-01-28_16.06.24-server.txt)

**Comment by planyte** [comment]
Windows 10

**Comment by planyte** [comment]
[crash-2020-01-28_19.56.17-server.txt](https://github.com/magmafoundation/Magma/files/4124340/crash-2020-01-28_19.56.17-server.txt)
[crash-2020-01-28_20.19.20-server.txt](https://github.com/magmafoundation/Magma/files/4124341/crash-2020-01-28_20.19.20-server.txt)

**Comment by planyte** [comment]
https://cdn.discordapp.com/attachments/663114062061764622/671806357267283968/ScreenShot_20200128225821.png plugins

**Comment by planyte** [comment]
When a player has died the console highlights this
https://cdn.discordapp.com/attachments/663114062061764622/671730167743250432/ScreenShot_20200128175502.png
https://cdn.discordapp.com/attachments/663114062061764622/671730433381236736/ScreenShot_20200128175642.png

**Comment by planyte** [comment]
Please don't use screenshots from discord we can't see them

**Comment by planyte** [comment]
https://pastebin.com/fAVEnKTS
https://pastebin.com/YDq444bi
https://pastebin.com/N2TDQyX3
версия сервера 1.12.2

**Comment by planyte** [comment]
Magma-d88b3f8-server

**Comment by Hexeption** [comment]
Can't replicate
