### ISSUE TITLE
[BUG] none of these plugins are being prosesed by the server and the mods arnt eather, custom npcs is being loaded but its not allowing me to  make npcs plz help.

### ISSUE THREAD

**Issue by EnderBoss2** [magmafoundation/Magma#61]
**Describe the bug**
when I try to make an npc with the npc wond it doesn't work. and when I try to do a command from any of the plugins it doesn't work.

**To Reproduce**
1.put mods in mods folder
2. put plugins in plugins folder
3. start server 
4. make npcs
5. do plugin commands
6. see error

**Expected behavior**
It doesn't make an npc when using the npc wond . and all of the plugins don't load.

**Screenshots**

**Info (please complete the following information):**
- Mod Name: custom npcs
 - Mod Version: CustomNPCs_1.12.2(30Jan19)
 - Magma Version: d88b3f8
 - OS:

**Additional context**
well ive got other mods and plugins in the server so they might be the problem so im linking them all here.  also as seen ubove there also not working with the server http://www.mediafire.com/file/egtdpdmm1s6cprz/mods_and_plugins_with_problems.zip/file

**Comment by Hexeption** [comment]
This issue looks like it has been fixed
