### ISSUE TITLE
[BUG]hellCrah

### ISSUE THREAD

**Issue by planyte** [magmafoundation/Magma#62]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
- Mod Name:
 - Mod Version: 
 - Magma Version: 
 - OS:

**Additional context**
When a player enters the portal of hell how does he teleport to hell crash server

**Comment by planyte** [comment]
[crash-2020-01-28_20.19.20-server.txt](https://github.com/magmafoundation/Magma/files/4124388/crash-2020-01-28_20.19.20-server.txt)
[crash-2020-01-28_19.56.17-server.txt](https://github.com/magmafoundation/Magma/files/4124389/crash-2020-01-28_19.56.17-server.txt)

**Comment by planyte** [comment]
When a player teleports to hell through a portal then the server crashes

**Comment by planyte** [comment]
https://cdn.discordapp.com/attachments/663114062061764622/671806357267283968/ScreenShot_20200128225821.png plugins

**Comment by planyte** [comment]
https://yadi.sk/d/PYuEBdvJOJVtiw logs

**Comment by planyte** [comment]
https://pastebin.com/fAVEnKTS
https://pastebin.com/YDq444bi
https://pastebin.com/N2TDQyX3
version server 1.12.2

**Comment by planyte** [comment]
Magma-d88b3f8-server

**Comment by xTrM-EN** [comment]
You know you're supposed to replace the text in the issue, not comment everything lmfao

**Comment by Hexeption** [comment]
I have no idea what this is
