### ISSUE TITLE
[BUG] Watering Can Crash

### ISSUE THREAD

**Issue by Hexeption** [magmafoundation/Magma#67]
**Describe the bug**
When using a watering can on Sky Factory 4 it will crash when using it on a crop or seed 

**To Reproduce**
Steps to reproduce the behaviour:
1. Use Watering Can on crop
2. Look at crash 

**Expected behaviour**

**Screenshots**
![](https://img.hexeption.co.uk/qEZFbbT0UB.png)

**Additional context**
Plugins 
1.     EssentialsX
2.     Vault
3.     GriefPrevention(Flags) - flag nogrowth is set on false for whole server
4.     Plugman
5.     HolographicDisplays
6.     WorldEdit + WorldGuard
7.     AuthMe
8.     ClearLag

**Comment by kwright02** [comment]
Is the crashed caused when watering ANY crop or just a specific one or few? The more information you can provide the better. Also, a log of the crash would be helpful too.
