### ISSUE TITLE
Magma client unable to download libraries on windows

### ISSUE THREAD

**Issue by tanker122** [magmafoundation/Magma#69]
Im running windows 10 pro, and when i go to install the client files, some fail to download, ive tried mutiple times on different computers with different wifi's the server downloads everything just fine but when i try to with the client it fails

![Screenshot (23)](https://user-images.githubusercontent.com/40444856/74208797-e6f6c400-4c39-11ea-8fc1-b2150a19a790.png)

 - Magma Version: Magma-1f2f94f-installer
 - OS: windows 10-

**Comment by Hexeption** [comment]
Don't use installer

**Comment by tanker122** [comment]
then what do i use for the clients?

**Comment by Hexeption** [comment]
You run this server side

**Comment by tanker122** [comment]
okay, but when i try to run forge with anything magma, it crashes the server

**Comment by Hexeption** [comment]
log?

**Comment by Hexeption** [comment]
http://mclo.gs/

**Comment by tanker122** [comment]
i dont have access to the server atm, i will upload tomorrow?

**Comment by tanker122** [comment]
wait, nvm i can run it on here

**Comment by tanker122** [comment]
will upload it in new bug form tomorrow, cant get connected
