### ISSUE TITLE
Server state invalid when joining with forge 1.12.2 

### ISSUE THREAD

**Issue by tanker122** [magmafoundation/Magma#71]
i launch magma for 1.12, but when i try to connect with forge 1.12.2 with mods, the server force stops and the last thing i see in the cmd prompt is "server state invalid"
(crash logs)
earliest:https://mclo.gs/cdTVijc 
latest: https://mclo.gs/SJPWnA4

 - Mod Version: 1.12.2
 - Magma Version: latest
 - OS: windows 10 pro

**Additional context**

**Comment by tanker122** [comment]
and now gives me error "please remove black listed mods"

**Comment by kingdevnl** [comment]
@tanker122 Yep i'm looking into the "please remove black listed mods" issue

**Comment by Hexeption** [comment]
This should be fixed
