### ISSUE TITLE
server crash for unknown reason when latest of forge 1.12.2 tries to connect

### ISSUE THREAD

**Issue by tanker122** [magmafoundation/Magma#72]
**Describe the bug**
i dont exactly what is causing it but i try to connect with the latest of forge 1.12.2 and it just crashes

**Info (please complete the following information):**
- Mod Name:
 - Mod Version: latest of 1.12.2
 - Magma Version: latest
 - OS: windows 10 pro

Logs
Latest.log: https://mclo.gs/qSKE2zc#L14171
Debug.log: for some reason wont load on mclo.gs
crash log: https://mclo.gs/Ho3cn1k

**Comment by tanker122** [comment]
Just checked the client side computer and it says theres an error with a furnace from crafting shared recipes produces unregistered item minecraft:furnace

**Comment by kwright02** [comment]
What are the names and exact versions of any/all mods you're using?

**Comment by tanker122** [comment]
crash: https://mclo.gs/ILbTf80

**Comment by tanker122** [comment]
Crash: https://mclo.gs/ILbTf80
[debug.log](https://github.com/magmafoundation/Magma/files/4199298/debug.log)      ((wouldn't upload to mclo.gs))
Latest log: https://mclo.gs/rzzhzCt 

Mods with 2 plugins: https://easyupload.io/8q0ohy    (had to upload it to easyupload.io because of file size)

**Comment by kwright02** [comment]
`[11:01:07] [Server thread/ERROR] [randompatches]: Failed to transform class: net.minecraft.network.NetHandlerPlayServer`

that's what's causing the crash. Try removing the RandomPatches mod and see if the error persists

**Comment by tanker122** [comment]
theres a problem with that, without it, theres so many mods that the clients fail to connect on normal forge servers but i'll give it a try on magma and see what happens

**Comment by tanker122** [comment]
so, i keep getting fatally missing registry's, even tho client and server have been both connected to wifi

**Comment by tanker122** [comment]
but just incase 
Latest: https://mclo.gs/wGy481K
Crash: https://mclo.gs/HHRco49
