### ISSUE TITLE
no /restart exists

### ISSUE THREAD

**Issue by Redd56** [magmafoundation/Magma#74]
/restart doesnt exist

in spigot, paper, and maybe base bukkit (idk on the last one only used spigot and paper)
there is a command to restart the server, it seems that magma doesnt have that yet....

**Comment by kwright02** [comment]
Restart is essentially a fancy way of saying "Stop the server, then run this script that I have defined in my Spigot/Bukkit yml" /stop will do exactly what you are expecting /restart to do as long as you're using a panel like multicraft. If you're not, then you should be advanced enough use to know how /restart functions and how to make an alternative to it. If you need further explanation I'd be happy to elaborate for you.

**Comment by josephworks** [comment]
Why do you need to use /restart? There is just no reason for magma to add this any time soon. And if I am correct, this was removed because using it is just a bad idea in the first place.

**Comment by RednedEpic** [comment]
> Why do you need to use /restart? There is just no reason for magma to add this any time soon. And if I am correct, this was removed because using it is just a bad idea in the first place.

Restart is fine, reload is the troublemaker.

**Comment by josephworks** [comment]
> > Why do you need to use /restart? There is just no reason for magma to add this any time soon. And if I am correct, this was removed because using it is just a bad idea in the first place.
> 
> Restart is fine, reload is the troublemaker.

Yes, that's right. I got them mixed up. But adding /restart does not sound like a priority rn anyways.

**Comment by kwright02** [comment]
@Hexeption This should be closed/archived

**Comment by Hexeption** [comment]
No need for this
