### ISSUE TITLE
Forge and magma version error?

### ISSUE THREAD

**Issue by tanker122** [magmafoundation/Magma#79]
**Describe the bug**
when trying to connect with the latest of forge 1.12.2, t gives me an error, "An established connection was aborted by host software". when it connects to a regular forge server just fine. i have looked on google for an answer as to whats causing it, and it seems to be caused when clients are at a lower java version than the server but i know thats not the case

**Screenshots**

**Info (please complete the following information):**
 - Mod Version: 1.12.2 
 - Magma Version: latest
 - OS: windows 10

crash log: https://mclo.gs/7ErADBP
Latest log :https://mclo.gs/ysKR6bR
screenshot: 
![Minecraft 1 12 2 2_18_2020 12_09_12 PM](https://user-images.githubusercontent.com/40444856/74773988-ca651800-5247-11ea-8faa-3edeb7bb4267.png)

**Comment by kwright02** [comment]
What's the output of `java -version` ?

**Comment by tanker122** [comment]
im sorry but i dont understand what your asking

**Comment by kwright02** [comment]
run that command I posted above in a command prompt/terminal window and paste the output here

**Comment by Hexeption** [comment]
This is a fastworkbench error please remove that mod
