### ISSUE TITLE
[BUG] Player in wrong world during Forge's PlayerEvent.Clone on respawn

### ISSUE THREAD

**Issue by Johni0702** [magmafoundation/Magma#81]
**Describe the bug**
https://github.com/Johni0702/BetterPortals/issues/480
https://pastebin.com/raw/BUgmiee1

**To Reproduce**
Steps to reproduce the behavior (based on above report, haven't tried myself):
1. Go to any dimension which sends you to a different dimension on death, e.g. nether, end
2. Get killed
3. Click Respawn
4. Note error in log and lack of chunks (Respawn packet was sent but chunks weren't)

**Expected behavior**
Respawn in the overworld.

**Info (please complete the following information):**
- Mod Name: BetterPortals
 - Mod Version: 0.3.7.7
 - Magma Version: master (based on details below, version in original report may differ)

**Additional context**
In the process of respawning a player after death, the `PlayerEvent.Clone` event is fired in `copyFrom` invoked from:
https://github.com/magmafoundation/Magma/blob/776897daa49d132ea08469c7f13d3e74c46247c0/patches/net/minecraft/server/management/PlayerList.java.patch#L534

Without Magma, the `entityplayermp` is already in the destination world during that call and BetterPortals relies on that to clean up its views of the worlds before the Respawn packet is sent:
https://github.com/Johni0702/BetterPortals/blob/af8e5489d0565d27488aaaea5d3145a6a08adcda/src/view/kotlin/de/johni0702/minecraft/view/impl/server/ServerWorldsManagerImpl.kt#L337-L340
With Magma, it's still in the old world, hence why BP later complains about not noticing the world change.

**Comment by Redd56** [comment]
next

**Comment by kwright02** [comment]
So i've come down to the conclusion that I'm going to have to manually re-write the respawn method till it works with better portals and is still compatible with regular MC.

**Comment by Redd56** [comment]
F

**Comment by kwright02** [comment]
This issue is fixed
