### ISSUE TITLE
[BUG] Better with mods Crash

### ISSUE THREAD

**Issue by UeberallGebannt** [magmafoundation/Magma#83]
**Describe the bug**
If you start the server and have the bounds modpack installed, it crashes. 
This is caused by the [Better with Mods Mod](https://www.curseforge.com/minecraft/mc-mods/bwm-suite).

**To Reproduce**
1. Download the [Minecraft Bounds modpack ](https://www.curseforge.com/minecraft/modpacks/bounds) and setup a server using magma.
2. Start the server.

**Expected behavior**
The server should start.

**Info (please complete the following information):**
- Mod Name: Better with Mods
 - Mod Version: 2.3.13
 - Magma Version: v6abd63f
 - OS: Linux

**Additional context**
Crash log: https://mclo.gs/Df4akch

**Comment by Hexeption** [comment]
The version of Better with Mods is not compatible with magma's forge version please update the mod to use the mod pack I've tested this mod with the latest version

**Comment by UeberallGebannt** [comment]
Ok, ill try to contace the modpack creator, thank you ^^
