### ISSUE TITLE
[BUG] NetherEX not generating

### ISSUE THREAD

**Issue by Amgelo563** [magmafoundation/Magma#85]
**Describe the bug**
NetherEX biomes and mobs won't generate on Nether, even with default configs. I think this is a Magma-related issue, since I tried generating a world on Single-player and it did generate (same mods, same default config).

**To Reproduce**
1. Install NetherEX
2. Install LibraryEX (dependency)
3. Go to the Nether
4. NetherEX mobs and biomes won't be generated.

**Expected behavior**
To mobs and biomes be generated.

**Screenshots**
Server problem (normal Nether generation). Note that the mod is correctly loaded, since mobs can be spawned via Spawn Eggs and blocks from the mod can be placed (obtainable in Creative Mode), but they won't be naturally generated.
![2020-03-09_02 43 01](https://user-images.githubusercontent.com/61554601/76193688-90d25d80-61b2-11ea-985c-a595dd616531.png)

Single-Player world (what was expected to be generated)
![2020-03-09_02 47 43](https://user-images.githubusercontent.com/61554601/76193717-9f207980-61b2-11ea-9849-8fe9ea2d8d76.png)

**Info (please complete the following information):**
- Mod Name: NetherEX (and dependency, LibraryEX)
 - Mod Version: NetherEX 2.0.15, LibraryEX 1.0.12
 - Magma Version: 0a0b4b5
 - OS: Aternos (Nether Enabled)

**Additional context**
- Server-side only mods: AI Improvements, FastLeafDecay and NetherPortalFix.
- Server Plugins: Authme, BetterSleeping, ColoredAnvils, CoreProtect, DeathMessagesPrime, EssentialsX, LaggRemover, LockettePro, LuckPerms, OpenInv, PlaceholderAPI, Plugman, SkinsRestorer, TAB Reborn, TogglePvp, Vault and WorldEdit.
- I don't know if it's normal on Magma, but from my experience on Paper/Bukkit, each dimension (Overworld/Nether/End) is created on a new World folder (Aternos). But on Magma, only one folder is present (Overworld), even after generating the Nether.

EDIT: After a long time flying around, found a single structure in the entire Nether:
![2020-03-09_03 45 04](https://user-images.githubusercontent.com/61554601/76196597-84e99a00-61b8-11ea-8b2a-b3662af425a6.png)
Still, this is not normal and a lot of these should be generated by now, but at least that's a sign that the mod is trying to generate structures. I have not found any biome nor mob yet.

**Comment by kwright02** [comment]
We need logs from the server startup when it's generating the world to be able to parse any issue. Pictures and being told what's happening doesn't provide enough info. Any kind of errors, crash-logs, anything like that will be necessary.

**Comment by Amgelo563** [comment]
Sorry, forgot to upload latest log, here it is: https://mclo.gs/maF1yIT , the server doesn't crash and as far as I know, no errors NetherEX-related can be seen on console.

**Comment by Amgelo563** [comment]
UPDATE: Tried to solve the problem by resetting the server and only adding NetherEX (and dependency) to the mod list. Turns out even with only that mod and no plugins installed, it won't be generated:
![2020-03-10_18 23 07](https://user-images.githubusercontent.com/61554601/76368074-05191800-62fd-11ea-80b2-21f750457eb3.png)
But on a single-player world it will:
![2020-03-10_18 30 49](https://user-images.githubusercontent.com/61554601/76368170-4d383a80-62fd-11ea-8305-e82358a640dc.png)

- Latest log: https://mclo.gs/e6xAxxA
- Versions: Magma 0a0b4b5, NetherEX 2.0.15 and LibraryEX 1.0.12
- OS: Aternos

**Comment by Sylensky** [comment]
Are there any news regarding this issue?
i am experiencing the same behaviour

**Comment by Forbidden-A** [comment]
> We need logs from the server startup when it's generating the world to be able to parse any issue. Pictures and being told what's happening doesn't provide enough info. Any kind of errors, crash-logs, anything like that will be necessary.

Catserver had this error, they fixed it by. https://github.com/Luohuayu/CatServer/issues/172

**Comment by Forbidden-A** [comment]
@kwright02

**Comment by kwright02** [comment]
Looking into potential fix soon

**Comment by kwright02** [comment]
Potential fix located [here](https://github.com/Luohuayu/CatServer/blob/d2395e455967c3624d23eb03545c4c4ffd2df0c8/patches/net/minecraft/world/gen/ChunkProviderServer.java.patch) I'll try and test this asap

**Comment by Forbidden-A** [comment]
any updates on this?

**Comment by kwright02** [comment]
Not yet, still testing

**Comment by Forbidden-A** [comment]
> Not yet, still testing

Ok

**Comment by Forbidden-A** [comment]
> Not yet, still testing

any updates?
