### ISSUE TITLE
[BUG] First aid Mod Conflict: not respawning

### ISSUE THREAD

**Issue by Tbear000** [magmafoundation/Magma#86]
**Describe the bug**
Server running most recent version of Magma and First aid mod players will die when their health goes to zero, then upon respawning they won't respawn, but just have access to their character again and they become invincible. First Aid Mod will show zero hearts, but the vanilla health bar stays full. The only way to fix this is to kill the player using server commands. First aid mod can have you die before your total health hits zero and I believe this is why the server doesn't properly respawn the player. Upon some research it appears that Magma does not use the datamanger for player.getHealth(), like the vanilla and forge implementation does. 

**To Reproduce**
1. Create Magma server and install RLCraft v2.8.1
2. Die in the server and select respawn.

**Expected behavior**
Expected that upon death in game the player selects respawn and is properly reset and spawned in a different location than where the death occurs.

**Info (please complete the following information):**
- Mod Name: First Aid
 - Mod Version: 1.6.12
 - Magma Version: 0a0b4b5
 - OS: WIndows 10 X64

**Additional context**
I would love any quick fix or work around if possible. Thank you in advance.

**Comment by kwright02** [comment]
Can you please provide a log of the server that includes when someone has died?

**Comment by kwright02** [comment]
Poking this, please read my above comment, without further context this issue will be closed and become irrelevant

**Comment by HarroldSaxon** [comment]
this issue still exists, i'll make a server and get a log for you

**Comment by HarroldSaxon** [comment]
[2020-04-01.log](https://github.com/magmafoundation/Magma/files/4417002/2020-04-01.log)
[debug.log](https://github.com/magmafoundation/Magma/files/4417003/debug.log)

steps i took
1 start server with first aid mod
2 join and give myself op so i can get flint and steal
3 light myself on fire and die
4 -experience respawn issue-
5 stop the server

**Comment by kwright02** [comment]
The log doesn’t reveal any direct issues, I’ll decompile the mod and see what I find

**Comment by HarroldSaxon** [comment]
Oh, it's open sorce.
https://github.com/ichttt/FirstAid
1.12.2 is listed as branch master

**Comment by Ahhyourbad** [comment]
Has this been fixed im currently having the same issue. When players dies they cant re-spawn they just can hit the title menu and that is it. And when the go to title and comeback they are full red and its like they never died.

**Comment by Ahhyourbad** [comment]
No still is an issue. I found where the problem is tho EntityDataManager

**Comment by Ahhyourbad** [comment]
kwright02 did you find the issue?

**Comment by TastefullBricodes** [comment]
Ive had the same issues as well

**Comment by kwright02** [comment]
Still investigating

**Comment by kwright02** [comment]
FirstAid is now declared incompatible for the time being. A fix will be found at some point
