### ISSUE TITLE
[BUG] Magma always use 100% of the cpu (even at 20 tps)

### ISSUE THREAD

**Issue by uiytt** [magmafoundation/Magma#88]
## How to replicate 
In a linux environment (not tested in windows)
Download server-jar
launch it with 8G of memory 
Look at cpu usage.
You should always see 100% of a cpu used. 

## Version :
Openjdk8
Magma : master-4690f1b 

#More infos
It's quite a burden because most hosting services use Linux and shut down the server when the cpu is way to high :/

**Comment by DokanBoy** [comment]
+1

**Comment by PunshWorld** [comment]
Same

**Comment by kwright02** [comment]
Most FREE hosts will do this yes, paid hosts will not. Either way, we're continuing to look into this issue over time.

**Comment by IcedHost** [comment]
On master-81086e0 I don't experience this issue, no matter how much memory etc. I allocate. tried switching to that version?

**Comment by IcedHost** [comment]
> 
> 
> On master-81086e0 I don't experience this issue, no matter how much memory etc. I allocate. tried switching to that version?

Using openjdk 8 btw

**Comment by DokanBoy** [comment]
> Either way, we're continuing to look into this issue over time.

I use paid hosting and the same problem.

**Comment by kwright02** [comment]
It seems that it could potentially be due to high core CPUs being used, but this has not been verified and will need further testing.

**Comment by uiytt** [comment]
I used paid hosting.
The problem also happen on my personal linux that I use for everything...

**Comment by IcedHost** [comment]
> 
> 
> It seems that it could potentially be due to high core CPUs being used, but this has not been verified and will need further testing.

I'm running on an i9 9900K 8c16t not having the issue. and I wouldn't expect to see higher core setups used for minecraft hosting. Doubt it is that

**Comment by IcedHost** [comment]
> 
> 
> I used paid hosting.
> The problem also happen on my personal linux that I use for everything...

I run linux with the server inside docker and don't have this issue

**Comment by kwright02** [comment]
it is possible then that @uiytt doesn't have a great setup, or whichever host is being used has older hardware that can't easily support the moded infrastructure.

**Comment by IcedHost** [comment]
There's a pretty easy way to test that. Are you able to use your own jars with this host @uiytt?

**Comment by uiytt** [comment]
> I run linux with the server inside docker and don't have this issue

I use Ubuntu 
> it is possible then that @uiytt doesn't have a great setup, or whichever host is being used has older hardware that can't easily support the moded infrastructure.
I don't have the greatest cpu but I can still run a forge server with 10 mods, but not magma with 0 mods...
P.S : My host service has a AMD Rayzen 
Anyway here is my cpu :
```
Cpu vendor: GenuineIntel
Cpu model: 158 Intel(R) Core(TM) i5-7300HQ CPU 
Cpu clock speed: 3,50 GHz
Cpu stepping: 9
 Cpu c/t: 4/4
```
As I said, not the greatest but still enough. 
And with my Host, I can run forge with 80 mods but not Magma with 0 mods :/

**Comment by kwright02** [comment]
We have found some data that suggests one of the internal server threads may be overloading itself for some reason. Testing will be required for this, and it will take time to iron out. Stay tuned for updates.
