### ISSUE TITLE
[BUG] Magma fails to start, D is not an option

### ISSUE THREAD

**Issue by andmagdo** [magmafoundation/Magma#92]
Magma Fails to start when downloading bukkit

**To Reproduce**
1. Start blank server with no other startup information
2. See error

**Expected behavior**
Startup of server

**Info (please complete the following information):** 
 - Magma Version: all 1.12.2
 - OS: Linux, remote server

**Additional context**
Found Fix: Run a Paper/Bukkit jar as server before running Magma jar
This fix seems to have worked.

**Output**

[INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}

Mar 28, 2020 3:43:23 PM org.bukkit.craftbukkit.v1_12_R1.Main main

SEVERE: D is not a recognized option

Option Description

------ -----------

-?, --help Show the help

-C, --commands-settings <File: Yml File for command settings (default:

file> commands.yml)

-P, --plugins <File: Plugin directory> Plugin directory to use (default:

plugins)

-S, --spigot-settings <File: Yml file> File for spigot settings (default:

spigot.yml)

-W, --universe, --world-container, -- World container

world-dir <File: Directory

containing worlds>

-b, --bukkit-settings <File: Yml file> File for bukkit settings (default:

bukkit.yml)

-c, --config <File: Properties file> Properties file to use (default:

server.properties)

-d, --date-format <SimpleDateFormat: Format of the date to display in the

Log date format> console (for log entries)

--demo Demo mode

-h, --host, --server-ip <String: Host to listen on

Hostname or IP>

--log-append <Boolean: Log append> Whether to append to the log file

(default: true)

--log-count <Integer: Log count> Specified how many log files to cycle

through (default: 1)

--log-limit <Integer: Max log size> Limits the maximum size of the log

file (0 = unlimited) (default: 0)

--log-pattern <String: Log filename> Specfies the log filename pattern

(default: server.log)

--log-strip-color Strips color codes from log file

--magma, --magma-settings <File: Yml File for magma settings (default:

file> magma.yml)

--mixin This argument is needed for proper

Mixin Framework work in the test env

--noconsole Disables the console

--nojline Disables jline and emulates the

vanilla console

-o, --online-mode <Boolean: Whether to use online authentication

Authentication>

-p, --port, --server-port <Integer: Port to listen on

Port>

--paper, --paper-settings <File: Yml File for paper settings (default:

file> paper.yml)

-s, --max-players, --size <Integer: Maximum amount of players

Server size>

--server-name <String: Name> Name of the server (default: Unknown

Server)

-v, --version Show the CraftBukkit Version

-w, --level-name, --world <String: World name

World name>

**Comment by johncsuti** [comment]
Have you removed the -D flag and tried it?

**Comment by andmagdo** [comment]
this is not a server start flag, this is a command inside the jar

**Comment by kwright02** [comment]
Have you verified that this problem persists if you use the latest version? I've tried every version and had no issues using Magma on Ubuntu or CentOS

**Comment by andmagdo** [comment]
It happens rarely, but it happened on many of the versions, every one i
tried ( most recent, second most recent, first version, second version) I
am using server.pro as a hosting company.

**Comment by kwright02** [comment]
@andmagdo this has been verified to be the cause of using a hosting service to use magma. The only host verified to have this issue with magma is Server.pro. Please use an alternative host for running Magma.

@Hexeption this should be closed or removed from bugs as it is not a Magma bug
