### ISSUE TITLE
Forgemod commands only work on op and not on other player. [HELP]

### ISSUE THREAD

**Issue by DeathSmurf** [magmafoundation/Magma#95]
**Describe the bug**
Forgemod commands only work on op and not on other player.

**To Reproduce**
1. Go to run **'magmaserver.jar'**.
2. Enter the server on minecraft.
3. Activate one command of a forge mod without being op: 
I click to Claim Daily Rewards. **(usage mod: oxygen core and oxygen daily rewards)**

![STEP 3](https://user-images.githubusercontent.com/63019055/78188738-1f02d200-7447-11ea-9536-4ce0461aa907.png)

    3.1 Shows the error:  I`m sorry, but you do not have permission to perform this command. Please contact the server administrators if oyu believe that this in error.

**Expected behavior**
Forge command works for all users without having to be op.

**Screenshots**
![magma yml](https://user-images.githubusercontent.com/63019055/78190342-31cad600-744a-11ea-9fac-f79cb6298c8b.png)

**Info:**
- Mod Name: **(1) =** Oxygen Core  - **(2)=** Oxygen Daily Rewards
 - Mod Version:  **(1)=** oxygen-core-1.12.2-0.11.0  - **(2)=** oxygen-daily-rewards-1.12.2-0.11.0b
 - Magma Version: Magma-81086e0-server.jar **(current lastest version** _01/04/2020_**)**
 - OS: Windows 10.

**Additional context**
Remove **all plugins** and keep giving error.

My file **magma.yml**:
[magma.zip](https://github.com/magmafoundation/Magma/files/4417898/magma.zip)

**Sorry my bad english, my mother tongue is spanish**

**Comment by DeathSmurf** [comment]
Hello @kwright02, **the error persists**, i don't know if it is due to magma or bukkit related problem, the situation is i am not able to grant default permissions so that players can use the forge internal mods commands.

I uploaded my **permission.yml** in the post.

Thank you for your work and I hope I do not cause any inconvenience.

**Comment by kwright02** [comment]
Are you using any permission plugins? If so they will override the permission override

**Comment by DeathSmurf** [comment]
@kwright02 Please remove all plugins when testing.

I even re-created a server from scratch with no plugins.

**Comment by kwright02** [comment]
Please try using [this](https://github.com/magmafoundation/Magma/releases/download/v81086e0/Magma-81086e0-server.jar) jar

**Comment by DeathSmurf** [comment]
@kwright02
Well, I downloaded it and it replaces even though it was the same version, the error still persists.

I'm pretty sure I'm following the steps to the letter, but I can't find a way for the forge commands to work.

**Comment by Jay113355** [comment]
I don't think this is a bug, but rather an unwanted feature for you.

The `bukkitPermissionHandler` setting in the magma.yml file is for whether or not magma should bridge the forge permissions API to bukkit's permission API. It has nothing to do with command permissions.

The problem you're seeing is a side effect of magma registering a permission node for all forge mod commands, which is needed for compatibility with permission plugins.

In short this isn't really something that can be 'fixed'. Magma could maybe add a config option about not forcing mod commands to have permissions checked, but honestly the intention behind doing this is so you can control what mod commands players have, its just better to install a permissions plugin here.

For those curious:
Mod command permissions are created here:
https://github.com/magmafoundation/Magma/blob/81086e0b0ffb1a2ac7995471ab57ba0d24fd0966/patches/net/minecraft/command/CommandHandler.java.patch#L60
And this is where the mod command's permission is checked: 
https://github.com/magmafoundation/Magma/blob/81086e0b0ffb1a2ac7995471ab57ba0d24fd0966/src/main/java/org/bukkit/craftbukkit/v1_12_R1/command/CraftSimpleCommandMap.java#L42-L48
The mod commands own .checkPermission() is called later on in the executeCommand() method after the permission check.

If you wanted to add a config option you could do that in the if on line 43. But again, a permission plugin is way better for this. :D

**Comment by DeathSmurf** [comment]
Thanks a lot #Jay113355 and #kwright02 for your help, it is good to know this ... but now if I wanted the forge commands to work in the default group I would have to write the node in the permission plugin, but what would be the node name of the forge commands? i can't find it.

**Comment by kwright02** [comment]
He explained in his post above how they're created.

They're structured like this: class name.commandname

For the class name, you'll either have to decompile the jar and look at the source to see what the name of the class is, or contact the mod author for help.

**Comment by DeathSmurf** [comment]
@kwright02 @Jay113355 

It would have been better if you could activate the global forge commands.

It would be interesting that after an update there is an option to skip the verification of the forge commands.

Thank you anyway.
I will try somehow to find a quick solution, because I don't see myself looking for all the nodes of the more than 80 mods that I have.

**Comment by Jay113355** [comment]
You can enable `debug.debugPrintCommandNode` in the magma.yml to have it print all the permission nodes per command, then its just a matter of figuring out what commands you need to give to the default rank. Still a lot of work though :/

**Comment by DeathSmurf** [comment]
@Jay113355 
No problem, as a workaround, I am setting players to "op" by default and banning "op" commands for the default group in luckperms.

**Comment by kwright02** [comment]
@DeathSmurf please do NOT do that! Just give the players permissions individually. Not all mods have permission nodes and if you follow what @Jay113355 said it shouldn't take you too long. Please do this the proper way!

**Comment by Hexeption** [comment]
This should be fixed
