### ISSUE TITLE
[Issue] Kickmessage and Black list mod (I can't add more than one mod to the list).

### ISSUE THREAD

**Issue by AsesinaGatitos** [magmafoundation/Magma#97]
**Describe the bug**

I cannot blacklist more than one mod.

Despite writing the correct mod IDs, they do not run or do not recognize them when they are more than one.

How should I write them?, I already tried in many ways, even listing them one below the other.

Another one that occurs is that I can't change the "kickmessage". (when starting the server, the message is restarted)
![asdsf](https://user-images.githubusercontent.com/63432719/78952928-23f9fe00-7aa5-11ea-959b-49739b69bdec.png)

**Screenshots**
For now I was only able to add a single mod to the list, if I add another one the mod lock doesn't work.
![nnñalsdfkasf](https://user-images.githubusercontent.com/63432719/78953008-70ddd480-7aa5-11ea-821d-53d59474b97a.png)

**Info
- Mod Name: none.
 - Mod Version: none.
 - Magma Version: Magma-81086e0-server. 
 - OS: Windows 10.

**Comment by kwright02** [comment]
Magma's config is as the file name (magma.yml) suggests a YAML file. Therefore you need to use a YAML list mechanic to do multiple mods. You can do it like so:
`blacklistedmods:
    enabled: true
    list:
        - xray
        - optifine
        - etc.
    kickmessage: 'Please remove blacklisted mods'`

**Comment by AsesinaGatitos** [comment]
@kwright02 
I did what you said but this happens: **(image below)**

I had the xray and customnpcs on and I was able to get in.

Before when only xray was listed if it kicked me.
![BEFORE - AFTER](https://user-images.githubusercontent.com/63432719/78955149-54916600-7aac-11ea-8bf4-701308690dd9.jpg)

**Comment by kwright02** [comment]
Interesting. What if you do it how you show in the before picture but put the mod id in single quotes?

**Comment by AsesinaGatitos** [comment]
So? - when i do this if it kicks me the problem is i cant add another mod id.
![asi](https://user-images.githubusercontent.com/63432719/78956706-19456600-7ab1-11ea-9b9c-dcb96a48c1a6.png)

![asfgaspgjaslk](https://user-images.githubusercontent.com/63432719/78956880-b86a5d80-7ab1-11ea-9e4b-44324f70845e.png)

**Comment by kwright02** [comment]
I'm saying that each one in the list after the - put it in single quotes exactly as I showed in my picture

**Comment by AsesinaGatitos** [comment]
@kwright02 
Nothing happens, it doesn't kick me.
![DONT KICKME](https://user-images.githubusercontent.com/63432719/78959712-d63bc080-7ab9-11ea-9627-cf9c771860e1.png)

**Comment by Jay113355** [comment]
Its a problem in magma not your config.

**Comment by AsesinaGatitos** [comment]
@Jay113355 okay, good to know. It looks like a good function I was going to add the existing 3 xray to the **MC 1.12.2**, but I'll wait for it to fix it. **Thank you.**
